### ISSUE TITLE
can't install version 1.4.0 in eclipse mars.2 release 4.5.2

### ISSUE THREAD

**Issue by christiankerl** [15knots/cmake4eclipse#10]
when trying to upgrade from 1.3.5 the plugin from the update site I get the following error:

Your original request has been modified.
  "CDT CMake build integration" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: CDT CMake build integration 1.4.0.201603051447 (de.marw.cdt.cmake.feature.group 1.4.0.201603051447)
  Missing requirement: CMake build integration 1.2.0.201603042155 (de.marw.cmake 1.2.0.201603042155) requires 'package org.eclipse.jetty.util.ajax 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: CDT CMake build integration 1.4.0.201603051447 (de.marw.cdt.cmake.feature.group 1.4.0.201603051447)
    To: de.marw.cmake [1.2.0.201603042155]

I also tried uninstalling/installing but gives the same error that org.eclipse.jetty.util.ajax could not be found

**Comment by 15knots** [comment]
`package org.eclipse.jetty.util.ajax` used to be in plugin org.eclipse.jetty.util_8.1.16.
But Mars comes with org.eclipse.jetty.util_9.2.13, which does (no longer) contain `package org.eclipse.jetty.util.ajax` and thus causes the above error.

Sorry, this will take time to resolve, as I will have to drop compatibility with Eclipse 3.8 and JRE 1.6.

As a quick workaround, you could try to place a plugin with org.eclipse.jetty.util.ajax in the dropins folder.

**Comment by christiankerl** [comment]
you know any plugin containing org.eclipse.jetty.util.ajax?

**Comment by 15knots** [comment]
Sorry, no. Will have to investigate, too.

2016-03-07 22:29 GMT+01:00 Christian Kerl <notifications@github.com>:

**Comment by christiankerl** [comment]
thanks, installs now
