### ISSUE TITLE
ParserDetecter for MSVC cannot distinguish between C and C++

### ISSUE THREAD

**Issue by euklid** [15knots/cmake4eclipse#101]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [ ] Bug Report  
- [x] Enhancement Request

## Brief Description

By default, all include paths for msvc compiler projects will be listed under "GNU C" language in Properties->C/C++ General -> Preprocessor Include Paths, Macros etc. , although it might be a C++ project.

### What is the expected behavior?

Compiler Parser should detect from command line options if C or C++ is the language used.

### What behavior are you observing?

MSVC C++ projects will only list the include paths provided by the compile commands json parser in the "GNU C" section.

### Provide the steps to reproduce the issue, if applicable:

1. 
1. 
## Useful Information
- cmake4eclipse version: 1.12.2
- Which OS do you use: Windows 10
- Cmake version: 3.12
- Used fix from #100 to get the include paths at all.
#### What is in Eclipse's Error Log?

Sanitized stack traces:

## (If Enhancement Request) Describe it. 

Parse the extensions of the files parsed or look for /TP option, see https://docs.microsoft.com/en-us/previous-versions/032xwy55(v=vs.140)

**Comment by 15knots** [comment]
Looking for /TP option does only make sense if cmake writes that option to the compile commands json  file. Does it actually write that?

**Comment by 15knots** [comment]
Maintaining complete compiler command argument parsers for each of the supported compilers is a time-consuming and tedious task.
I would prefer to use the source file extension to distinguish C from C++.

**Comment by euklid** [comment]
I thought the same, however there aren't any different versions of cl for C or C++. Only way round might be a wrapper script around `cl` for C++ files and the same for C files, set those as C++ and C compiler respectively for CMake if one wants to stick with identification by extension.

**Comment by 15knots** [comment]
**source** file extension to distinguish C from C++.
