### ISSUE TITLE
Project specific include folders scope issue 

### ISSUE THREAD

**Issue by daniel-dnil** [15knots/cmake4eclipse#105]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

Setup
=====
eclipse.buildId=4.10.0.I20181206-0815
CDT: 9.6.0.201812111211
cmake4eclipse: 1.13.0.201901031836
OS: Linux Mint 19
cmake version 3.10.2

Common Prepare
==============
git clone https://github.com/daniel-dnil/cm4e-tc.git && cd cm4e-tc

TC3: Project specific include folders scope issue 
=================================================

1) git checkout 219e723

2) Import two projects from folder proj-cn and proj-cn into empty new WS

3) Close both project and revert any changes done to language.settings.xml performed at import
   (due to issue in TC2 above).

4) Open both projects again. expand the "Includes" folder. Notice that the last include folder
   in the list is the same for both projects, which isn't correct. Each project should have an
   include folder matching the project name from the CMakeLists.txt. compile_command.json does
   contain the correct information, but what is displayed in the "Includes" folder isn't correct.

5) Close both project and restarts Eclipse. Open project "proj-cn" first and expand the "Includes"
   folder. This now shows the correct information. Next open project "proj-cx" and expand the
   "Includes" folder, it shows the same information as "proj-cn". This also works the other way
   around, seems like the information from the first project opened in the WS is used also for
   other projects in the WS.

6) Checking the entries from the CMAKE_EXPORT_COMPILE_COMMANDS Parser by selecting Properties
   on main.c and navigating to C/C++ General -> Preprocessor Include Paths, Macros etc. -> 
   Entries -> CMAKE_EXPORT_COMPILE_COMMANDS Parser shows the same problem that can be seen in
   the "Includes" folder of the project.

**Comment by 15knots** [comment]
Same project config ID as in #107?
Please fix your project setting, then report.

**Comment by daniel-dnil** [comment]
Re-creating both testcases projects from scratch makes this issue disappear. Based on using CDT together with other plugins I've never experienced issues with copying projects before, I've only experienced issues in combinations with this plugin. On the CDT Users mailing-list nobody seems to be away of limitations or other ways to create new projects based on existing projects.

**Comment by 15knots** [comment]
There is _File | Import... | C/C++ project settings_ which my be what you are looking for.

**Comment by daniel-dnil** [comment]
The way I understand that C/C++ project settings import/export is that it only handles include paths and symbols, both which are parameters that I'd like to keep in (and only in) cmake from now on.
