### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins flags issue

### ISSUE THREAD

**Issue by daniel-dnil** [15knots/cmake4eclipse#108]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

Setup
=====
eclipse.buildId=4.10.0.I20181206-0815
CDT: 9.6.0.201812111211
cmake4eclipse: 1.13.0.201901031836
OS: Linux Mint 19
cmake version 3.10.2

Common Prepare
==============
git clone https://github.com/daniel-dnil/cm4e-tc.git && cd cm4e-tc

TC6: CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins flags issue
=================================================================

1) Keep the same WS as in issue #107. Close all open projects in Eclipse

2) git checkout 93689e4

3) git clean -dfx to clean out all build files.

4) Open proj-cx which will now autobuild. Check compile_commands.json and notice the
   -std=gnu90 flag. This flag is set all the way back in the toolchain file for
   cmake and I expect this to also be present when the "Compiler Built-ins" provider
   runs

5) Check symbols again on proj-cx (like step 8) of TC5 above), notice __STDC_VERSION__
   not reflecting the C version set in the toolchain file. In my case set to 
   201112L. This isn't that much of an issue here with C in this simple project , but with C++ and STL it is 
   a major concern since the feature set of STL greatly depends on the C++ version and not 
   feeding the indexer with the correct information here makes the "Compiler Built-ins"
   provider more or less unusable with C++.

**Comment by 15knots** [comment]
Relates to issue  #96 (Missing include paths when --sysroot compiler option is given)

The "Compiler Built-ins" provider currently relies on **just the basename** of the compiler executable to determine, which options have to be passed to the compiler to make it spit out the values of its built-in macros and include paths.
It does **not** implement a parser that recognizes each argument of [each of the supported compilers](https://github.com/15knots/cmake4eclipse/blob/268f242619c05a430a4cf0e2425422458def7234/de.marw.cmake/src/main/java/de/marw/cmake/cdt/language/settings/providers/ParserDetection.java#L56), nor does it maintain an internal database telling it how to construct the proper compiler arguments to make that just report its built-ins. Regarding your issue: cmake4eclipse is not GCC-centric. To be non-GCC-centrice, the task to add compiler args from the `compile_commands.json` file to make the compiler _spit out the values built-in_  call, that database has to provide:
1. which arguments **have to be added** to the cc-basename argument to make the built-ins-detection-call to output the built-ins.
2. which arguments **have to be removed** from the command-line in `compile_commands.json` to make the built-ins-detection call **not** produce an error-exit-code.
3. compiler-_built-ins command output_ parsers that extract macros and include paths and feed those to the indexer; each parser has to be compiler-specific.

A soluiion is feasible, but a question of man-power. Feel free to usw...

**Comment by daniel-dnil** [comment]
Yes, I realize this is related to issue #96. The solution to analyze the compile_commands.json is as you state troublesome since it would require knowledge regarding which flags that are relevant for the extraction of the compiler built-ins and which one that are not. Instead of going this route I was hoping for either one of two (what I think is) are simpler solutions

1. Have the plugin write out a simple temporary CMakeLists.txt which contains only a temporary cmake target that have no additional compiler flags set. The only flags then set would be those specified in a cmake toolchain file for example (like my C++ standard example flag), or set through cmake symbols specified in the pluign interface. The plugin would run cmake once just to extract those flags, and later run the selected compiler with all those flags for the purpose of extracting the compiler built-ins. In my case this would be OK.

2. Allow to specify flags to be included to extract to compiler built-ins though the plugin provider GUI, just like how it is done in this CDT ARM Cross GCC Built-ins Compiler Settings provider;

![image](https://user-images.githubusercontent.com/5024783/52281015-71d51c80-295d-11e9-92d0-9adf1290372e.png)

**Comment by 15knots** [comment]
The question is: How often must/should the built-in detector run?
CMake has the commands `add_compile_options`, `target_compile_features` and `target_compile_options` which allow to specify the language standard and sysroot on a per-source-directory or per-artifact base.
Unfortunately, cmake4eclipse has no knowledge about the generated build system structure, the compile_commads.json file only reports source-files. To have perfect built-in detection, cmake4eclipse must run the detection for each source file. IMHO, that is not feasable if you have hundreds of projects and source files in your workbench.

But if we assume the compiler-flags relevant to built-in-detection (namely `-std` and `--sysroot` in the GCC case) are the same for each source-file in a CMake project, we could run detection just once per Eclipse project.
Do you think we could assume the above?

**Comment by daniel-dnil** [comment]
Yes, I understand the problem. The way I use this plugin in various native and cross C/C++ projects I don't see an issue assuming that we have the same compiler built-ins across all sources within one project so running the detection once per project seems OK!

**Comment by 15knots** [comment]
Implemented by passing the relevant commandline options...
@daniel-dnil Could you please test staged 1.15.0 p2 repo 
from here https://drive.google.com/drive/folders/0B-QU1Qnto3huZUZ0QUdxM01pR0U ?
Configure the provider to allocate a console and check the commandline args (--sysroot and -std).

**Comment by 15knots** [comment]
fixed in 65351f2

**Comment by daniel-dnil** [comment]
Hi,

I've been working to try to understand how this new feature works using this release from Google Drive
  cmake4eclipse	1.14.1.201905061832	de.marw.cdt.cmake.feature.group	Martin Weber
Is this the correct release to test?

I setup a simple project with only one source file, which builds using cmake like this;

```
/usr/bin/c++    -g   -DFOO=BAR -Wall -Wextra -Werror -std=gnu++11 -o CMakeFiles/testcpp.dir/main.cpp.o -c /home/daniel/ws1/testcpp/main.cpp
```

Was the intention then that the "compiler built-in" should run with the "-std=gnu++11" flag?

```9:38:00 PM Detecting compiler built-ins: testcpp::Debug for GNU C++
/usr/bin/c++ -E -P -dM -Wp,-v /home/daniel/ws1/.metadata/.plugins/de.marw.cmake/spec.cpp 
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/7"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/7/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/7
 /usr/include/x86_64-linux-gnu/c++/7
 /usr/include/c++/7/backward
 /usr/lib/gcc/x86_64-linux-gnu/7/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 ```
I haven't been able to quite figure out if I'm doing something wrong or if I'm not using the correct version of the plugin for test?

**Comment by 15knots** [comment]
It was cmake4eclipse 1.15.0, but since I found it was not working, I removed that from the google drvie. Sorry for the confusion.

> Was the intention then that the "compiler built-in" should run with the "-std=gnu++11" flag?

Yes, it is fixed now and will be published soon. Please re-open if you find any issues.
