### ISSUE TITLE
Build in Linux Docker container uses Windows path format

### ISSUE THREAD

**Issue by Flabbergabber** [15knots/cmake4eclipse#110]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [ ] Bug Report  
- [X] Enhancement Request

## Brief Description

When cmake command is launched inside a container, the source path corresponds to the Windows absolute path (ex. "C:\\\foo"). Shared drives in Docker(Linux) use the "//c/foo" notation when mounted inside the container. This results in cmake not finding the source directory, but it's just not referring to the correct path format.

I would like to be able to build inside Docker from a Windows host. This is due to our company issuing windows PCs and using Linux build servers.

### Provide the steps to reproduce the issue, if applicable:

1. Install Eclipse CDT and cmake4eclipse on Windows;
1. Build docker image with cmake;
1. Build a cmake project inside that container using the Eclipse container settings;
## Useful Information
- Eclipse CDT version: 2018-12 (4.10.0)
- cmake4eclipse version:  1.13.0.201901031836
- Which OS do you use: Windows 10 Pro
- Cmake version: 3.13.0-rc2
#### What is in Eclipse's Error Log?
CMake Error: The source directory "C:/foo" does not exist.

## (If Enhancement Request) Describe it. 

It would be interesting to be able to specify which container environment we're targeting in order to use the correct path format. Even more flexible would be to allow us to manually specify a source directory relative to the CWD.

**Comment by 15knots** [comment]
IMHO, it should be sufficient to make the plugin to detect, whether Eclipse runs on windows and whether the build is targeted to run in a docker container. If so, the plugin can translate the source directory "C:/foo" to "//c/foo" notation and pass that to the build command launcher.
But detection of in-container-builds would require a minimum version of Eclipse Photon. Currently the plugin requires Mars.

**Comment by 15knots** [comment]
> When cmake command is launched inside a container, the source path corresponds to the Windows absolute path (ex. "C:\\foo"). Shared drives in Docker(Linux) use the "//c/foo" notation when mounted inside the container.

AFAICT, CDT uses `/c/foo` notation (NOT `//c/foo`) inside a container.

After looking at the CDT code that handles in-container builds [ContainerCommandLauncher](https://github.com/eclipse-cdt/cdt/blob/0757b45da5db47a65f59911c42eb9dcccfbdf972/launch/org.eclipse.cdt.docker.launcher/src/org/eclipse/cdt/docker/launcher/ContainerCommandLauncher.java#L182-L199),  I see that **ContainerCommandLauncher itself** does translate windows paths to Docker(Linux)  paths if necessary.
So I doubt it would make sense to have cmake4eclipse do the translation.

Could you debug cmake4eclipse on windows to verify whether this is a bug in CDT, a problem with your eclipse project settings or really a bug in cmake4eclipse? I do not have access to a windows machine to do so.
To aid you, I added a target configuration in file `de.marw.cdt.cmake-target-9.4.target` that will help you to debug the ContainerCommandLauncher with source code available.

**Comment by Flabbergabber** [comment]
I would love to help but I've never debugged an eclipse plugin before. I looked around a bit and found varying methodologies. Would you have any suggestions for documentation for me to follow in order to debug? Thanks for your help.

**Comment by 15knots** [comment]
Thank you for trying to hel here.

You will need to install Eclipse PDE and (possibly m2e) in your workbench to debug.
I prepared some files to help you get started.

Steps to debug:
- Clone the git repo.
- Extract attached [de.marw.cdt.cmake-target.debug_CDT9.4.zip](https://github.com/15knots/cmake4eclipse/files/2895714/de.marw.cdt.cmake-target.debug_CDT9.4.zip) into `cmake4eclipse/releng/de.marw.cdt.cmake-target/` dir. These two files are a Eclipse launch configuration for debugging cmake4eclipse, plus a platform-configuration file that tells Eclipse about the plugins to use for debugging and building.
- Start Eclipse and import the projects from the checked out git repo.
- Open the `*.target` file in the target file editor and set it as the active target platform (upper right in the editor). This may take 2-3 minutes to complete, watch the Progress View..
- Set  breakpoints in project `de.marw.cdt.cmake.core`, at class  `de.marw.cdt.cmake.core.internal.BuildscriptGenerator.invokeCMake()`
and in `org.eclipse.cdt.docker.launcher.execute()`. If the latter soes not work, step down until you reach `ContainerCommandLauncher`.
- Open the Debug Configurations dialog, select _Eclipse Application_  :: _cmake4eclipse CDT 9.4_ and start debugging. It will fire up an Eclipse workbench under debugger control, with CDT and cmake4eclipse installed.
- Import your project to the new Eclipse workbench and start a build.

Please note that the launch configuration has not been tested on windows, so you might need to adjust it

**Comment by havogt** [comment]
It is a bug in CDT. I'll provide a fix tomorrow.

**Comment by havogt** [comment]
The trivial fix is here https://bugs.eclipse.org/bugs/show_bug.cgi?id=545192

**Comment by 15knots** [comment]
That's good news!
Will the fix be published in CDt 9.7.0?

**Comment by havogt** [comment]
Yes, the fix was just merged to the 9.7 branch, i.e. it will be in the 2019-03 release (March 20).

**Comment by Flabbergabber** [comment]
Awesome! I'll try it out once it's released.

**Comment by havogt** [comment]
@Flabbergabber It's released now. Can you try?

**Comment by Flabbergabber** [comment]
@havogt @15knots Sorry for the delay! The issue has been resolved, paths are correctly being transformed to their Unix style counterpart when fed to the cmake command.

Thank you!
