### ISSUE TITLE
Error upgrading to 1.14.0

### ISSUE THREAD

**Issue by Algomorph** [15knots/cmake4eclipse#111]
Could this be a typo similar to #25 ?

I tried to upgrade to 1.14.0 but I got the following error:
![image](https://user-images.githubusercontent.com/1050606/53506770-a764b580-3a84-11e9-8359-4be308de8d7c.png)

I have cmake4eclipse setup as a software site with URL https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/

I'm running Eclipse 4.10.0 with CDT 9.6.0 on Ubuntu 18.04

**Comment by 15knots** [comment]
Yes, same typo.
Fixed now.
