### ISSUE TITLE
cmake cache entries only saved for one configuration

### ISSUE THREAD

**Issue by daniel-dnil** [15knots/cmake4eclipse#112]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

Setup
=====
eclipse.buildId=4.10.0.I20181206-0815
CDT: 9.6.0.201812111211
cmake4eclipse: 1.14.0.201902262022
OS: Linux Mint 19
cmake version 3.10.2

Prepare
==============
git clone https://github.com/daniel-dnil/cm4e-tc.git && cd cm4e-tc

1) git checkout 0fcba31

2) Import project from folder proj-cn into empty new WS.

3) Close project and revert any changes done to language.settings.xml due to #104

4) Close and restart Eclipse, open WS created in step 2) above

5) Add cmake symbol under C/C++ Build -> Cmake4eclipse -> Symbols, "TESTSYMBOL" with value "DEBUG" of type string. Note that the active configuration of the project is "Debug". Change the active configuration of the project to "Release". Note that the symbol just added to Debug is gone which is expect. Again add symbol "TESTSYMBOL" with value "Release" of type string, this is now the expected value for the Release config of the project. "Apply and Close" the dialog.

6) Close the project in the Project explorer.

7) Check what settings have been stored in the .cproject file using git diff. Note that only one of the symbols entered via the GUI is actually saved in the project file.

8) Restart eclipse and re-open the project to verify that the edits are actually only present now for one of the configurations. 

9) Close the proj-cn project in the Project explorer, undo the edits to the .cproject file: git reset --hard HEAD

10) Re-open the project in the Project Explorer and again browse to the  C/C++ Build -> Cmake4eclipse -> Symbols GUI. Note the that symbol edit we just reverted is still there, we need to restart Eclipse to make them go away. They don't seem to actually be used though, only shown in the GUI...

**Comment by 15knots** [comment]
> 5. Add cmake symbol under C/C++ Build -> Cmake4eclipse -> Symbols, "TESTSYMBOL" with value "DEBUG" of type string. Note that the active configuration of the project is "Debug". Change the active configuration of the project to "Release". Note that the symbol just added to Debug is gone which is expect. Again add symbol "TESTSYMBOL" with value "Release" of type string, this is now the expected value for the Release config of the project. "Apply and Close" the dialog.
> 6. Close the project in the Project explorer.
> 7. Check what settings have been stored in the .cproject file using git diff. Note that only one of the symbols entered via the GUI is actually saved in the project file.

Cannot reproduce with CDT 9.5.5 and cmake4eclipse 1.14.0. "TESTSYMBOL"  is in the .cproject file for each of the configurations (with different values, of course).

**Comment by daniel-dnil** [comment]
Maybe I didn't explain step 5) above in a good way, I realize it shouldn't actually read "change the active configuration of the project". When adding the second symbol in the symbol tab of the cmake4eclipse properties just change configuration in the "Configuration: " dropdown without changing the active configuration of the project (in other words, try to edit both the active and a non-active configuration of the project at the same time).

Recreated this again on a different computer using the versions below;

Version: 9.6.0.201812111211
Build id: 20181214-0600
cmake4eclipse	1.14.0.201902262022

**Comment by 15knots** [comment]
Again, cannot reproduce with CDT 9.5.5 and cmake4eclipse 1.14.0 and **your project** _proj-cn_.

>  (in other words, try to edit both the active and a non-active configuration of the project at the same time).

Perhaps you misunderstand _active configuration_, that is the configuration that is used by default when you trigger a build. Changes in the project properties always affect the **selected** configuration only.

**Comment by daniel-dnil** [comment]
The GUI parts works as expected, I see symbols for the selected configuration. The only problem is that what I see in the GUI isn't saved to the .cproject file and parts of the changes are lost. Let's see if someone else can reproduce? I have reproduced this issue on 3 different machines now.

**Comment by 15knots** [comment]
Did you click 'Apply & Close'? Clicking just 'Apply' does not save your changed to disk.

**Comment by daniel-dnil** [comment]
Yes, "Apply & Close". Detailed steps:

* In project properties. C/C++ Build -> Cmake4eclipse, click tab Symbols
* Leave configuration drop-down at Debug.
* Hit Add... 
* Enter TESTSYMBOL in Variable name, leave Type: as STRING and enter DEBUG in Value: Click OK
* Change Configuration drop-down to Release
* Hit Add... 
* Enter TESTSYMBOL in Variable name, leave Type: as STRING and enter RELEASE in Value: Click OK
* Change Configuration drop-down back to Debug and watch TESTSYMBOL Value change to DEBUG
* Hit "Apply and Close"
* Close project in project explorer
* Do a git diff:
```
diff --git a/proj-cn/.cproject b/proj-cn/.cproject
index c48c79f..936bed9 100644
--- a/proj-cn/.cproject
+++ b/proj-cn/.cproject
@@ -47,6 +47,9 @@
                        <storageModule moduleId="org.eclipse.cdt.core.externalSettings"/>
                        <storageModule buildDir="build/${ConfigName}" moduleId="de.marw.cdt.cmake.core.settings">
                                <options/>
+                               <defs>
+                                       <def name="TESTSYMBOL" type="STRING" val="DEBUG"/>
+                               </defs>
                        </storageModule>
                </cconfiguration>
                <cconfiguration id="cdt.managedbuild.config.gnu.exe.release.751302918">
```
Only one of edits is saved.

* Open up the project again
* In project properties. C/C++ Build -> Cmake4eclipse, click tab Symbols
* Toggle Configuration drop-down between Debug and Release. The TESTSYMBOL is there in both configurations and has different and correct values (RELEASE and DEBUG), but this is just a memory copy and if Eclipse is restarted this isn't the case any longer.

**Comment by caselitz** [comment]
Not sure, but is [this](https://github.com/15knots/cmake4eclipse/issues/72#issuecomment-375598594) maybe related?

Maybe only things required for indexing are saved - and which these are is determined by the mentioned Indexer preferences.

**Comment by daniel-dnil** [comment]
@caselitz : I don't think #72 is related, this issue is specific to this plugin. If I instead of adding a cmake symbol under C/C++ Build -> Cmake4eclipse -> Symbols as a test just add a plain "Build Variable" under C/C++ Build -> "Build Variables" it all works as expected. The "Build Variables" GUI has the same Configuration: drop-down but there this bug isn't present (i.e. edits for both configurations are saved to .cproject and .cproject is also correctly parsed when the project is opened).

**Comment by 15knots** [comment]
Looking at the CDT-code, I found that the code handling the "Build Variables" page does **persist** the settings of the **currently selected** configuration to disk when the _Apply_ button is clicked.
Cmake4eclipse does not, it persists settings to disk if a 'Save' or 'OK' button is pressed. And CDT's _Apply and Close_ button is labeled 'OK' in older 8.x CDT versions, so AbstractCPropertyTab.performOK() -- but not AbstractCPropertyTab.performApply() -- should be the proper method to override to persist settings. (Guessed from the method names, interested persons may find the  [CDT documentation here](https://github.com/eclipse-cdt/cdt/blob/master/core/org.eclipse.cdt.ui/src/org/eclipse/cdt/ui/newui/AbstractCPropertyTab.java#L265-L276); my guessing [here](https://github.com/15knots/cmake4eclipse/blob/master/de.marw.cdt.cmake.core/src/main/java/de/marw/cdt/cmake/core/ui/QuirklessAbstractCPropertyTab.java#L61-L92)).

Observations, why I cannot reproduce this:
@daniel-dnil  Your issue report states that you pressed the _Apply and Close_ button to persist settings; you did not state when you selected a different configuration for editing. Apparently this is wrong.
@CDT lead  Document the code! Or stop complaining over your lack of volunteer maintainers.
@me Blog: `CDT instanceof Moribund`

**Comment by daniel-dnil** [comment]
@15knots : Please also note the final two steps of the original report : 

* Close the proj-cn project in the Project explorer, undo the edits to the .cproject file: git reset --hard HEAD

* Re-open the project in the Project Explorer and again browse to the C/C++ Build -> Cmake4eclipse -> Symbols GUI. Note the that symbol edit we just reverted is still there, we need to restart Eclipse to make them go away. They don't seem to actually be used though, only shown in the GUI...

Were you able to reproduce this? What I expect to happen is that the project properties are updated from the .cproject file when the project is opened. It seems this doesn't happen fully today, at least cmake symbols are displayed in the project properties GUI even though they have been removed from the .cproject file. Only way I've found to get the GUI in sync with .cproject is to restart Eclipse. This is again different from the behaviour of for example the build variables under C/C++ Build -> "Build Variables".
