### ISSUE TITLE
Use compile commands parser without calling cmake

### ISSUE THREAD

**Issue by GuilleDF** [15knots/cmake4eclipse#113]
**This is a...**  

- [ ] Bug Report  
- [x] Enhancement Request

## Brief Description
Use compile commands parser without calling cmake with this plugin

## (If Enhancement Request) Describe it. 
We're using a custom solution to call cmake and generate the compile_commands.json. We would like to use this plugin to parse the compile_commands.json, but we found it only works when the "Generate Makefiles automatically" option is ticked in the C/C++ Build settings. Would it be possible to enable these parsers to work when a compile_commands.json is found, even if the plugin is not configured to take care of calling cmake?

**Comment by 15knots** [comment]
When designing the parsers, I already had your use case in mind, So I think it should work independently from the settings on the CDT Build pages..
But maybe the json file is not found. If so, some info messages get written to the problem view.
You will have to enable info messages to see them.

**Comment by metalmumin** [comment]
![image](https://user-images.githubusercontent.com/7769358/65255886-f5afd380-dafe-11e9-9841-cec9cb3f9f47.png)
Expectation: If the compile_commands.json exists in _C/C++ Build -> cmake4eclipse -> "build output location"_, then this compile_commands.json should be used by cmake4eclipse's json parser. In this case particular case: build/Linux_x86_64/compile_commands.json.

Is this the case?

**Comment by 15knots** [comment]
> Expectation: If the compile_commands.json exists in C/C++ Build -> cmake4eclipse -> "build output location", then this compile_commands.json should be used by cmake4eclipse's json parser. In this particular case: build/Linux_x86_64/compile_commands.json.

> Is this the behaviour?

Yes, the plugin parses the compile_commands.json file. Parsing is triggered when, a build is run. You need a _Managed build project_ to make it work, it CDT's newer core build does not triiger parsing.

**Comment by metalmumin** [comment]
Already running _Managed build project_, which from what I can gather from [these docs](https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_prop_build.htmi) is a confusing Eclipse-term for having the following box unticked:
![image](https://user-images.githubusercontent.com/7769358/65857794-dddd1880-e364-11e9-9801-344613f32988.png)

Attempting cmake4eclipse to force the compile_commands.json Parser to run by setting:
![image](https://user-images.githubusercontent.com/7769358/65866906-e68a1a80-e375-11e9-8569-d5bebc182b37.png)

But to no avail. Is there a more reliable parser hook?

**Comment by 15knots** [comment]
The settings you refer to are related to build-script-generation. The CMAKE_EXPORT_COMPILE_COMMANDS parser can be configured in the project's settings on the C/C++ General | Preprocessot Include Path... tab.

**Comment by metalmumin** [comment]
From the very beginning of this conversation, the following has been set:
![image](https://user-images.githubusercontent.com/7769358/65919671-54b5f800-e3dd-11e9-8bb1-a71ce7a7cae2.png)
Not sure what to do, the alternative is ccls+vscode which I'm not too fond of..

**Comment by 15knots** [comment]
The pluginin print message of INFO level to the Problems View if it cannot find the json file. You will have to enable dissplay of INFO messages for the view to see them.
You may also put the plugin into trace mode which will print detailed information of the macros/include paths found to the Eclipse error log.

**Comment by 15knots** [comment]
Some things are wrong with your settings:
- You use one of the CMake Builders. This tells the plugin to generate the build scripts usings cmake. Either use a different build or try to set-up a Makefile project.
- You tell cmake to load cache entries from a file that does not exist on the first build.

**Comment by metalmumin** [comment]
I think the issue here is that there's literally nothing for the CMake Builder to generate. The cmake cache file exists since before, and so does the compile_commands.json. The build system has already been called once from outside Eclipse, project has been built, and "build/Linux_x86_64" folder is populated with files.

The C/C++ build system at work here has 0% integration with Eclipse, much less depends on it. It calls cmake, ninja etc. cmake4eclipse only has to find the already existing files and do its indexing magic.

Tried all Builders, no luck. Will try more when I get the time. As always thank you for replying and providing support 15knots!

**Comment by 15knots** [comment]
As of CDT 11, you could choose either
_CMake Compilation DB_ (coming from cmake4eclipse) or
_Compilation Database Parser_ (coming from CDT itself)
