### ISSUE TITLE
Add CMAKE_COMPILE_COMMANDS headers from docker to cache

### ISSUE THREAD

**Issue by ssweeny** [15knots/cmake4eclipse#118]
**This is a...**  

- [ ] Bug Report  
- [X] Enhancement Request

## Description
I have a fairly complex CMake/C++ project which uses [Conan](https://conan.io) to install library dependencies. One of the conveniences of this setup is that Conan will install the library headers to a known location and make that available as an interface target to CMake such that it's easy to add to `target_include_directories` for example. These paths are also added to the `compile_commands.json` file generated by CMake.

The problem I'm having is that if I use CDT's fancy Docker functionality to build inside of a container then:
1. The headers from Conan are not available to the indexer outside of the container, or
2. If I mount my `~/.conan` directory into the container such that they are available, the paths in `compile_commands.json` won't match unless the home directory path is the same in the container as the host.

I have seen that the system headers from the container image are cached by CDT into a path which is mapped properly by the CDT indexer such that the includes all resolve. I would like to request that include paths found via the `CMAKE_COMPILE_COMMANDS` source are cached in a similar way for docker builds.

**Comment by 15knots** [comment]
> I have seen that the system headers from the container image are cached by CDT into a path which is mapped properly by the CDT indexer such that the includes all resolve. I would like to request that include paths found via the CMAKE_COMPILE_COMMANDS source are cached in a similar way for docker builds.

Unfortunately, there is no way to programmatically tell CDT's Docker functionality to cache header files from a path other than CDT'S hardoced paths: 
<https://github.com/eclipse-cdt/cdt/blob/master/launch/org.eclipse.cdt.docker.launcher/src/org/eclipse/cdt/docker/launcher/ContainerCommandLauncher.java#L143>
