### ISSUE TITLE
usage description

### ISSUE THREAD

**Issue by amigo421** [15knots/cmake4eclipse#12]
could you extend readme with a description of the using ?
I used cmake in qtcreator and clion IDEs, there I have to just Open cmakelists,
and optionally pass command line parameters to cmake and IDE generates cmake cache and project files.

what is a scenario here? doesn't look that is here similary...

**Comment by 15knots** [comment]
The plugin already comes with online help, which explains how to activate it.

In Eclipse, goto
Help:Help Contents
then open the 'CMake for CDT User Guide' node.

Or read [this comment ](https://github.com/15knots/cmake4eclipse/issues/2#issuecomment-130846356).

**Comment by amigo421** [comment]
THank you for the reply , I see a lot of questions similar to my,
Seems I went wrong way, opened .cproject generated from command line.
but still have an issue:
the description of the using refers to other CDT version and currently no settings points as described.
In other hand, I found "Builders' setting sheet, but there is no cmake builder. that's oddly, plugin was installed without errors and I see this from Eclipse installation details .
Is the plugin compatible with latest MARS.2?

**Comment by 15knots** [comment]
Yes, the plugin is compatible with Eclipse 4.5.2.
 I guess you looked at the `C/C++ Build` page? You will find the `CMake Builder (portable)` entry on the `Tool Chain Editor` page.
Alternatively, you can try to import some of the [test projects](https://github.com/15knots/cmake4eclipse/tree/master/testprojects).

**Comment by amigo421** [comment]
thank you for reply, 
tried this , you were right - I had to perform those step-by-step , I suggest you to put that instructions (from a comment referred above) to plugin usage description 
However, still no success there.

I did all from the instructions, by the way "generate makefile automatically" was checked on and disabled (greyed and non-editable) .

when I tried to build I got this error:

_13:57:16 **** Clean-only build of configuration Debug for project algolist ****
make clean 
Cannot run program "make": Launching failed

Error: Program "make" not found in PATH
PATH=<various paths in my system>;**C:\dev\tools\mingw\mingw64\bin**;C:\dev\tools\eclipse]

13:57:16 Build Finished (took 90ms)

Buildfile generation error occurred..
Build stopped.._

why it refers to "make"? in usual build without cmake features ,eclipse always calls mingw32-make.exe executable from the path above

**Comment by 15knots** [comment]
`**** Clean-only build of configuration Debug for project algolist ****
make clean
Cannot run program "make": Launching failed`

Hmm weird, usually this should echo the full path to make, e.g. `/usr/bin/make`. In most of the cases, cmake refuses to generate build scripts, if it cannot find `make`.

What is the value of `CMAKE_MAKE_PROGRAM` in file `<proj-dir>/build/Debug/CMakeCache.txt`?
If you project is on github, I could have a look.

**Comment by professorpsih** [comment]
Install Error with MARS.2^
Unable to read repository at https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/content.xml.
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

**Comment by bugdanov** [comment]
Thanks a lot ! 

Definitely your comment above should appear in https://marketplace.eclipse.org/content/cmake4eclipse#details 
```
For instructions, goto
Help:Help Contents
then open the 'CMake for CDT User Guide' node.
```

**Comment by 15knots** [comment]
Leaving this open, so others with the same problem will find it.

**Comment by 15knots** [comment]
Closing this, as getting started instructions are now on the project page and the online help.
