### ISSUE TITLE
Target plattform x86/x64 for build.make generation cannot be set

### ISSUE THREAD

**Issue by Samsara81** [15knots/cmake4eclipse#123]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [ ] Bug Report  
- [x] Enhancement Request

### Provide the steps to reproduce the issue, if applicable:

1. 
1. 
## Useful Information
- cmake4eclipse version: 1.17.0
- Which OS do you use: Windows 10
- Cmake version: 3.15
## (If Enhancement Request) Describe it. 
I'm using prebuild libraries (injected by conan) they are bre-build for x64 target plattform, but the generate build.make ist automatically linking against a x86 target..
C:\Tools\VisualStudio2015\VC\bin\link.exe /lib  /machine:X86

resulting in a linker error:
fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'

Is there a work around or does this setting miss?

**Comment by 15knots** [comment]
AFAICT, you will have to pass a special symbol to cmake to accomplish that.
I've seen similar questions on the cmake mailing list [1].

[1] https://cmake.org/pipermail/cmake/
