### ISSUE TITLE
Recognize g++ if it has version number in suffix, e.g. x86_64-linux-gnu-g++-9.2.0

### ISSUE THREAD

**Issue by ineffective** [15knots/cmake4eclipse#124]
**This is a...**  
- [ ] Bug Report  
- [X] Enhancement Request

## Brief Description
It would be nice if g++ was recognized in cases such as:
```
arm-linux-gnueabihf-g++-9
x86_64-linux-gnu-g++-9.2.0
```
I checked documentation and fix for #122 and it seems that currently only g++ commands ending in "g++" are recognized. It would be great if at least "g\+\+(-\d.+)?(\.exe)" was recognized, for example on Debian one could have (without restoring to crosscompilers or custom gcc builds):
```
g++-6
g++-9
g++ (which is linked to one of them)
```
I have my own toolchain with suffix `-9.2.0` - I suppose there are more people with at least `-9.2` or similar. Of course I could provide compiler under different name, but maybe there is a chance for an update accommodating it. I don't think this is a rare situation, at least when it comes to people doing cross-compilations. For example I have the following versions of g++ on my machine:
```
arm-linux-gnueabihf-g++ (which is g++ 6.3.0 provided by Debian)
arm-linux-gnueabihf-g++-9.0.0 (custom build of 9.0.0)
arm-linux-gnueabihf-g++-9.2.0 (custom build of 9.2.0)
x86_64-linux-gnu-g++-9.2.0 (again custom build of 9.2.0)
g++-9 (g++ 9.0.0 provided by Debian)
g++-6 (g++ 6.3.0 provided by Debian)
g++ (link to g++-6)
```
### What is the expected behavior?
cmake4eclipse properly parses g++ versions with version is suffix and before optional ".exe".

### What behavior are you observing?
G++ with version number in suffix is not recognized as a proper compiler:
```
No parser for command '/usr/local/bin/x86_64-linux-gnu-g++-9.2.0  -DMQTT_USE_TLS ....
```
and so on.

This of course means that includes are not properly parsed, so files are not found, so there are unknown symbols and so on.

## Useful Information
- cmake4eclipse version:   cmake4eclipse	1.17.0.201909291254
- Which OS do you use:  Debian 9.11
- Cmake version: 3.15.4

#### What is in Eclipse's Error Log?
Sanitized stack traces:
Description	Resource	Path	Location	Type
No parser for command '/usr/local/bin/x86_64-linux-gnu-g++-9.2.0  -DMQTT_USE_TLS -I/opt/ZS/deps/include -I/home/jd/zs_pack/queues/mqtt_cpp_test_2/.  -g   -pthread -std=gnu++17 -o CMakeFiles/test.dir/tls_client.cpp.o -c /home/jd/zs_pack/queues/mqtt_cpp_test_2/tls_client.cpp'. Your workbench will not know all include paths and preprocessor defines.	compile_commands.json	/mqtt-cmake-test/build/Debug	de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser	CMAKE_EXPORT_COMPILE_COMMANDS Parser Problem

Aforementioned JSON is:
[
{
  "directory": "/home/jd/zs_pack/queues/mqtt_cpp_test_2/build/Debug",
  "command": "/usr/local/bin/x86_64-linux-gnu-g++-9.2.0  -DMQTT_USE_TLS -I/opt/ZS/deps/include -I/home/jd/zs_pack/queues/mqtt_cpp_test_2/.  -g   -pthread -std=gnu++17 -o CMakeFiles/test.dir/tls_client.cpp.o -c /home/jd/zs_pack/queues/mqtt_cpp_test_2/tls_client.cpp",
  "file": "/home/jd/zs_pack/queues/mqtt_cpp_test_2/tls_client.cpp"
}
]

## (If Enhancement Request) Describe it. 
As described earlier. It boils down to recognize GCC if there is "g++" or "gcc" anywhere in path - this doesn't seem that bad for g++. There are commands like "arm-linux-gnueabihf-gcc-nm-6" but it shouldn't be a problem - there is infinitesimal chance that they will be called in the scope that cmake4eclipse uses.

**Comment by 15knots** [comment]
according to the test added in d00b1353a3e8e5d19f2ca9ec593e0e867ba82499, `/usr/local/bin/x86_64-linux-gnu-g++-9.2.0 ` is properly recognized.

**Comment by ineffective** [comment]
I will check in newest version, after it is release, when I opened this issue it wasn't true. Thank you for an answer.

**Comment by ineffective** [comment]
I checked newest version and it seems to work fine, so I will close this issue. Thanks!
