### ISSUE TITLE
How to build and install plugin on my own

### ISSUE THREAD

**Issue by ineffective** [15knots/cmake4eclipse#125]
It is neither bug nor feature request - I simply want to make some changes to the plugin (namely implement #124), build it and install. But I don't fully understand the flow. I cloned sources and ran

```shell
mvn -f parent/pom.xml package
```
This created  quite a few jars, but there is nothing indicating what I should do next. I'd assume I should import all of some of generated jars into Eclipse but I have no idea how. Could you (15knots) provide some pointers as to how I should proceed or at least point me to some resources?

**Comment by 15knots** [comment]
To debug the plugin from Eclispe, first set the Plug-in Development Target platform of your workbench to cdt/8.7-eclipse/4.5.2, then run the Eclipse Application launch configuration named cmake4eclipse.

(just updated the readme)

For the futuer, please ask this kind of questions on the mailing list https://groups.google.com/forum/#!forum/cmake4eclipse-users

**Comment by ineffective** [comment]
Thanks, I will try it. I moved to vim + ycm + clangd as it is pretty fast, much faster than CLion and definitely faster than Eclipse after renaming g++ (which was x86_64-linux-gnu-g++-9.2.0 and as I wrote in other issue wasn't properly recognized) to simply `g++`, which was abysmally slow.
