### ISSUE TITLE
Relation to CDT 9.10's Compilation Database Parser

### ISSUE THREAD

**Issue by nolange** [15knots/cmake4eclipse#126]
**This is a...**  
- [ ] Bug Report  
- [X] Enhancement Request

## Brief Description
CD 9.10 now ships with a "Compilation Database Parser", supposedly filling the same role as the "CMAKE_EXPORT_COMPILE_COMMANDS Parser". (https://wiki.eclipse.org/CDT/User/NewIn910#Build)

Please explain if there are notable differences (from my short tests, both work fine). Maybe in the future the upstream parser should be preferred (and missing features added there)?

**Comment by 15knots** [comment]
I have not tried CDT's "Compilation Database Parser" yet, but looking at its [source code](
https://git.eclipse.org/c/cdt/org.eclipse.cdt.git/tree/build/org.eclipse.cdt.managedbuilder.core/src/org/eclipse/cdt/managedbuilder/internal/language/settings/providers/CompilationDatabaseParser.java) i guess it only recognizes the command-line options of GCC and microsoft's cl.exe. (See subclasses of AbstractBuildCommandParser).

The `CMAKE_EXPORT_COMPILE_COMMANDS Parser` recognizes command-line options of other compilers than `gcc` and `cl`; for example the CUDA compiler `nvcc`. See the [online-help](https://github.com/15knots/cmake4eclipse/blob/master/de.marw.cdt.cmake.core/doc/html/languageSettingsProviders.xhtml).
It also provides an extension point, allowing 3rd-party compiler vendors to integrate a compiler by simply providing an Eclipse plug-in.
