### ISSUE TITLE
GNU C++ CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins empty

### ISSUE THREAD

**Issue by daschuer** [15knots/cmake4eclipse#128]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

### What is the expected behavior?

The Entry CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins for GNU C++ should be populated with the internal compiler includes and definitions. 
On Properties -> C/C++ General -> Preprocessor Include Path  

### What behavior are you observing?

Unlike the same entry for GNU C it is empty. 

### Provide the steps to reproduce the issue, if applicable:

1. Checkout a cmake4eclipse-sample-projects
1. Convert C-flat into CPP-flat and rename main.c to main.cpp
1. Delete .project and .cproject 
1. New Project -> C Project (If you select C++ Project the Built-ins for GNU C are also empty) 
1. Select the CPP-flat folder and click finish 
 
## Useful Information
- cmake4eclipse version: 2.0.0.201912202000
- Which OS do you use: Windows 7 64 bit
- Cmake version: 3.15.1
- MinGW GCC: 6.3.0
#### What is in Eclipse's Error Log?

Sanitized stack traces:

**Comment by 15knots** [comment]
I cannot reproduce this here.
Did you also update the CMakeLists.txt to use `main.cpp` instead of `main.c`?
It looks like you have a stale version of `compile_commands.json` in your build-folder.

**Comment by daschuer** [comment]
Yes, the CMakeList.txt was also updated and the build succeeds. I have deleted the build folder before the test so 
compile_commands.json should not be staled. How it compile_commands.json related? The issue effects the Compiler build-ins. How are these generated? Why does it work for C but not C++?

**Comment by daschuer** [comment]
Ah, I think I am getting close. There seems to be an entry in the compile_commands.json that invalidates all earlier entries. 

Here is the failing compile_commands.json: 
[compile_commands.json.txt](https://github.com/15knots/cmake4eclipse/files/4058015/compile_commands.json.txt)

If I remove all ```-isystem C:\\Qt\\5.9.8\\mingw53_32\\.\\mkspecs\\win32-g++``` all includes are discovered. 

If I remove the tailing '++' or append a '1', it works as well. I guess the g++ is detected a compiler command and therefore everything before is discarded.

**Comment by 15knots** [comment]
> How is compile_commands.json related? 

It is used to get the path of the compiler in order to invoke it with arguments that make it spit out it built-ins. That output then gets parsed and is fed to the indexer.

> If I remove all -isystem C:\\Qt\\5.9.8\\mingw53_32\\.\\mkspecs\\win32-g++ all includes are discovered.

`-isystem C:\\Qt\\5.9.8\\mingw53_32\\.\\mkspecs\\win32-g++` is detected by the CMAKE_EXPORT_COMPILE_COMMANDS Parser (no builtins) and passed to the indexer. Maybe this confuses the indexer.
Do you have a project on github to test it?

**Comment by daschuer** [comment]
no, but you can use [compile_commands.json.txt](https://github.com/15knots/cmake4eclipse/files/4058015/compile_commands.json.txt) in any project to reproduce it. Just replace it with a more recent date that make does not overwrite it.

**Comment by 15knots** [comment]
To verify whether parsed the `-isystem ...` option confuses the CDT indexer, I added
`target_include_directories(main-cpp SYSTEM PRIVATE /usr/include/sysincl/win-g++)` to my CMakelLsts.txt (on Linux).
Looking at the Preprocessor Include Path page I can see it is **not** confusing the indexer.

Again, I cannot reproduce this issue on linux.

**Comment by daschuer** [comment]
I cannot prove it, but for me the include ending with g++ is the source of the problem. 
If it is available everything before is ignored and eclipse is not able to populate the compiler interns. 

I guess it uses the include instead of the real compiler call in front of the line. So it probably tries to execute the folder.

Maybe it works on Linux because the path does not exist?

**Comment by 15knots** [comment]
Sorry, without an minimal example to reproduce it and without a windows machine, I cannot examine this issue.
