### ISSUE TITLE
System includes not indexed

### ISSUE THREAD

**Issue by baldapps** [15knots/cmake4eclipse#129]
- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
System includes are not indexed when a cmake driven project is created

## Brief Summary
I created a new project using cmake driven option. It compiles correctly but system includes are not indexed. I tried to enable the "Gcc cdt built-in provider" but it doesn't change anything. Am I missing anything special in the project setup? Eclipse 2019-12 with cmake4eclipse 2.0.1

**Comment by 15knots** [comment]
Please provide more information, I cannot reproduce it here.
Are the #include <stdio.h> in a source Editor marked as 'Unresolved inclusion: <stdlib.h>' warnings?
Are there any messages related to this in the Problems View after you enabled the INFO severity in the Filter... dialog?
What is the filename of the compiler executable?

**Comment by baldapps** [comment]
I don't know what happened but now it works, maybe I needed to close and reopen eclipse, I don't know

**Comment by 15knots** [comment]
CDT sometimes has some issue in updating the UI in that area.
