### ISSUE TITLE
eclipse MARS.2 error

### ISSUE THREAD

**Issue by professorpsih** [15knots/cmake4eclipse#13]
Error In eclipse marketplace:

Unable to read repository at https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/content.xml.
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Thanks a lot.

**Comment by 15knots** [comment]
Do you use the eclipse marketplace client or the [marketplace website](https://marketplace.eclipse.org/content/cmake4eclipse)?
Did you already trie to install a different plugin? E.G. cmake editor?

Anyway, a little googling makes me think this is more a problem on your side: http://stackoverflow.com/a/6788682

**Comment by professorpsih** [comment]
You are right. 
Problem on certificate into the "/etc/ssl/certs/java/cacerts"
The topic is closed.
Thanks a lot.
