### ISSUE TITLE
Please switch to EPL 2.0

### ISSUE THREAD

**Issue by ruspl-afed** [15knots/cmake4eclipse#130]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
The EPL-1.0 has been deprecated, please use EPL-2.0

https://www.eclipse.org/legal/epl-2.0/faq.php#h.60mjudroo8e5

**Comment by 15knots** [comment]
Thank you for pointing me at this.

Do you you know of a tool to easily replace the license references in each of the source files?
