### ISSUE TITLE
Ignored #defines by indexer

### ISSUE THREAD

**Issue by Menion2k** [15knots/cmake4eclipse#131]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
Indexer does not consider build -D defines even if compile_commands.json is generated

## (If Bug Report) Brief Summary
I am building a code described by CMake. The code leverage on a set of defines which are correctly appended to the invoked compiler and found in the compile_commands.json
Eclipse indexed ignores the define set and consider them as undef (all of them)

Example of json entry

`{
  "directory": "C:/GNSS/GIT/TimeSync/build/Debug/common",
  "command": "C:\\STGNSSTools\\compilers\\rvct\\rvct_506b750\\bin\\armcc.exe -DACFQ_METRICS_LINKED -DAUTOSAR_E2E_LINKED -DBEIDOU_B2_LINKED -DCHAN_MONITOR_LINKED -DCOMPASS_DIFF_ENABLED -DCOMPASS_LINKED -DCP_EVENT_DRIVEN -DDEBUG_BACK_END -DENABLE_DHRYSTONE -DENABLE_GALILEO_PILOT -DENABLE_JTAG -DFREERTOS -DGALILEO_LINKED -DGAL_E5_LINKED -DGEO_USE_NOT_PREAMBLE_LOCKED -DGLN_TIME_MARK_RESYNC -DGLONASS_CODE_LINKED -DGLONASS_LINKED -DGLO_L2_LINKED -DGPS_L5_LINKED -DIFM_LINKED -DIRNSS_IONO_GRID_LINKED -DIRNSS_LINKED -DL2C_FRAMING_LINKED -DL2C_LINKED -DLEGACY_WRITE_CODE -DMCNF_AUTO_INSERTION -DMCNF_LINKED -DNAV_DUMP_ENABLED -DNMEA_LINKED -DNMEA_USE_DATUM -DNVM_SQI -DOBSQ_METRICS_LINKED -DPPS_UPDATE_BY_TRACKER -DQZSS_L1_CA_LINKED -DQZSS_L2C_LINKED -DQZSS_L5_LINKED -DRFM_LINKED -DRTCM3_LINKED -DRTCM_LINKED -DRTCM_PROP_MSG_ENABLED -DRTC_DRV_LOCAL_ENABLED -DSAGNAC_AT_RANGE_LINKED -DSDB_CCM_REV_1_0 -DSIGQ_METRICS_LINKED -DSIS_LAYER_LINKED -DSIS_MON_SQM_LINKED -DT5_CUTBx -DT5_SQIDIV2ENABLE -DT5_USE_OF_DMA -DTESEOV_VARIANT_APP -DTIME_SYNC_LINKED -DTRACKER_EVENT_ENABLED -DTRACKER_USE_OUTPUT_BUFFER -DUART_DEBUG -DVERSION_BINARY=5_8_4 -DVERSION_SDK=3.0.2 -DVERSION_SUFFIX=_ALPHA -DWAAS_LINKED -DWAITOSCIOKDISABLE -D__GPS_SINGLE_CORE__ -D__MST__ -D__STA8100__ -IC:\\GNSS\\GIT\\TimeSync\\clibs -IC:\\GNSS\\GIT\\TimeSync\\cmsis -IC:\\GNSS\\GIT\\TimeSync\\common -IC:\\GNSS\\GIT\\TimeSync\\lld -IC:\\GNSS\\GIT\\TimeSync\\os -IC:\\GNSS\\GIT\\TimeSync\\os\\common -IC:\\GNSS\\GIT\\TimeSync\\os_svc -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\adc -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\can -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\dma -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\fccu -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\fsw -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\gpio -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\i2c -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\mcu -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\msp -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\mtu -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\pwr -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\sqi -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\ssp -IC:\\GNSS\\GIT\\TimeSync\\os_svc\\uart -IC:\\GNSS\\GIT\\TimeSync\\modules\\antenna_sensing -IC:\\GNSS\\GIT\\TimeSync\\modules\\crypto -IC:\\GNSS\\GIT\\TimeSync\\modules\\datum -IC:\\GNSS\\GIT\\TimeSync\\modules\\debug -IC:\\GNSS\\GIT\\TimeSync\\modules\\dhry -IC:\\GNSS\\GIT\\TimeSync\\modules\\e2e -IC:\\GNSS\\GIT\\TimeSync\\modules\\error_handler -IC:\\GNSS\\GIT\\TimeSync\\modules\\gnss_events -IC:\\GNSS\\GIT\\TimeSync\\modules\\gnss_msg -IC:\\GNSS\\GIT\\TimeSync\\modules\\gnssapp_plugins -IC:\\GNSS\\GIT\\TimeSync\\modules\\in_out -IC:\\GNSS\\GIT\\TimeSync\\modules\\nmea -IC:\\GNSS\\GIT\\TimeSync\\modules\\nmea_ext -IC:\\GNSS\\GIT\\TimeSync\\modules\\nvm -IC:\\GNSS\\GIT\\TimeSync\\modules\\rtc -IC:\\GNSS\\GIT\\TimeSync\\modules\\rtcm3 -IC:\\GNSS\\GIT\\TimeSync\\modules\\sw_config -IC:\\GNSS\\GIT\\TimeSync\\modules\\time_sync -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\cnav -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\common -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\compass -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\dgps -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\dr -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\galileo -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\irnss -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\lband -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\sis -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\tracker -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\navigate -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\st_pp -IC:\\GNSS\\GIT\\TimeSync\\gpslib\\waas -IC:\\GNSS\\GIT\\TimeSync\\sta8100\\platforms -IC:\\GNSS\\GIT\\TimeSync\\sta8100\\frontend -IC:\\GNSS\\GIT\\TimeSync\\sta8100\\gnss_bsp -IC:\\GNSS\\GIT\\TimeSync\\sta8100\\gnssapp -IC:\\GNSS\\GIT\\TimeSync\\sta8100\\os_bsp -IC:\\GNSS\\GIT\\TimeSync\\sta8100\\sis_bsp -IC:\\GNSS\\GIT\\TimeSync\\modules\\sensors_lld -IC:\\GNSS\\GIT\\TimeSync\\modules\\sensors_manager -IC:\\GNSS\\GIT\\TimeSync\\modules\\crypto\\tls\\include -IC:\\GNSS\\GIT\\TimeSync\\lld\\arm -IC:\\GNSS\\GIT\\TimeSync\\sta8100\\os_bsp\\arm -IC:\\GNSS\\GIT\\TimeSync\\os\\freeRTOS\\portable -IC:\\GNSS\\GIT\\TimeSync\\os\\freeRTOS\\Source_FreeRTOS\\include -IC:\\GNSS\\GIT\\TimeSync\\os\\gpOStoFR   -c -O2 -Ospace --c99 --cpu=Cortex-M7.fp.dp --fpu=fpv5_d16 --apcs=/hardfp --no_unaligned_access --diag_suppress=1267,1296,9931 --debug --thumb --diag_style=gnu -JC:/STGNSSTools/compilers/rvct/rvct_506b750/bin/../include -JC:/GNSS/GIT/TimeSync/build/codeblocks/sta8100/gnss/ -g   -o CMakeFiles\\common_TeseoV_Bx_APP.dir\\fixpoint.o   -c C:\\GNSS\\GIT\\TimeSync\\common\\fixpoint.c",
  "file": "C:/GNSS/GIT/TimeSync/common/fixpoint.c"
},
`
No of the -D reflects to code highlights, while the -I seems ok since I can surf #include statements

### What is the expected behavior?
Syntax highlight should understand which defines are set and show them in code browser

### What behavior are you observing?
All the code portion between #ifdef and #if defined show as not compiled as the define is not set

## Useful Information
- cmake4eclipse version: 2.1.0
- Which OS do you use: Windows 10
- Cmake version: 3.14

**Comment by 15knots** [comment]
Did you install CDT indexer support for ARM C compilers?
It is in the extras category.

**Comment by Menion2k** [comment]
Do you mean in the Eclipse Software repository? I cannot see any extras category nor the CDT indexer support for ARM C compilers

**Comment by 15knots** [comment]
Indeed, ARM, HPE-nonstop and Intel support is not showing up in the repository on bintray.

**Comment by 15knots** [comment]
Fixed now.
Make sure you have 'Group items by category'  checked.

![Install_New_Software](https://user-images.githubusercontent.com/11367029/76235537-856f4880-622b-11ea-901b-96258a855301.png)

**Comment by Menion2k** [comment]
I probably need to add the bintray, so far I have installed cmake4eclipse from MarketPlace

**Comment by 15knots** [comment]
Sorry, I forgot to push to github.
Updates should be in the marketplace update site now.

**Comment by ChristianWalch** [comment]
I think I'm having the same issue:
The Eclipse C/C++ Editor does not recognize my symbols set in the CMakeLists.txt when using the arm-none-eabi-gcc compiler.
further described in this [group topic]https://groups.google.com/forum/#!topic/cmake4eclipse-users/_wSDzirhJpI)

I installed the cmake4eclipse plugin by copying the extracted zip folder into the dropins directory of eclipse.
"Available Software" shows that "CDT indexer support for ARM C compilers" is already installed:
![image](https://user-images.githubusercontent.com/32576309/86736913-2e8c4b00-c034-11ea-8d68-2c9c9cf7d7a0.png)

Did I forget anything else?

**Comment by gentooise** [comment]
Hi @15knots, I think I'm facing the same issue here, with ARM Compiler.

I also installed the compiler inside a very clean and simple folder (`C:\build\arm`) to avoid issues with dots and whitespaces, but the plugin doesn't work anyway.

I can correctly see include paths, but preprocessor macros are missing:

![image](https://user-images.githubusercontent.com/1735060/109505061-83397600-7a9c-11eb-967f-848649395c03.png)


Moreover, the built-in detector does not include the ARM include path (as workaround I had to add it manually as MBS entry):

![image](https://user-images.githubusercontent.com/1735060/109505422-de6b6880-7a9c-11eb-97a7-1b322eb97965.png)


Also, I cannot get to see error messages from the Problems View, even if I configured the view correctly (it seems):

![image](https://user-images.githubusercontent.com/1735060/109505724-32764d00-7a9d-11eb-91e7-302665d5b1a2.png)



This is an extract of my compile_commands.json:

```
{
  "directory": "C:/Users/myprojectdir/mybuilddir",
  "command": "C:\\build\\arm\\bin64\\armcc.exe -DMACRO1 -DMACRO2 [...] -Imyincludedir1 -Imyincludedir2 [...] --gnu --remarks --diag_suppress=1301,2530 -O0 --no_allow_fpreg_for_nonfpdata --split_sections --no_integer_literal_pools --no_float_literal_pools --no_string_literal_pools --bss_threshold=8 --dollar --fp16_format=ieee --asm --interleave -g --cpu=Cortex-A5.neon --fpu=VFPv4 --fpmode=fast --arm --apcs=/hardfp -o CMakeFiles\\project_build_dir.dir\\C_\\Users\\myprojectdir\\myfile.o -c C:\\Users\\myprojectdir\\myfile.c",
  "file": "C:\\Users\\myprojectdir\\myfile.c"
},
```

**Comment by 15knots** [comment]
> I can correctly see include paths, but preprocessor macros are missing:
> 
> ![image](https://user-images.githubusercontent.com/1735060/109505061-83397600-7a9c-11eb-967f-848649395c03.png)

You reference the macros passed from your cmakelists.txt to the compiler in that image. Do not trust the GUI too much, it is unclear when it gets updated.

> 
> Moreover, the built-in detector does not include the ARM include path (`../include` relative to the compiler executable). 

Does the Indexer Parser Log File show that include dir?

> Also, I cannot get to see error messages from the Problems View, even if I configured the view correctly (it seems):
...
You won't, `armcc` is a compiler well known to cmake4eclipse.

> **EDIT**: If I do `Index -> Create Parser Log File` for `myfile.c`, I actually see my macros from Indexer log.
> Macro definitions (option -D):
>    MACRO1=
>    MACRO2=

Fine. cmake4eclipse works as expected.

> and the Indexer is able to grey out regions correctly... however it does not completely work for included files.
> Let's suppose `myfile.c` includes `myfile.h`, containing:
> 
> ```
> //myfile.h
> #ifdef MACRO1
> // this is wrongly greyed out when I open myfile.h
> #define DERIVED_MACRO // this macro is used in myfile.c, but Indexer is not able to resolve it
> #endif
> ```
> 
> It seems that macros are not correctly passed to the Indexer for included header files (I see my macros are missing if I do `Index -> Create Parser Log File` for `myfile.h`).

I suspect you opened myfile.h before you started a build. `MACRO1` was not known to the indexer when you opened the file , hence the greyed out section. Additionally, the indexer seems to have skipped over the greyed out section, thus skipping the defintion of `DERIVED_MACRO`.
What does the editor look like if you close and re-open myfile.h when the build has finished?

**Comment by 15knots** [comment]
Closing after more tha one year of no responses
