### ISSUE TITLE
Unable to use cmake4eclipse with an existing Makefile project

### ISSUE THREAD

**Issue by eyalroz** [15knots/cmake4eclipse#135]
I've installed cmake4eclipse on Eclipse 4.9.0 (2018-09), and - I want to use it with existing projects (which I've imported as "Existing code as Makefile project"). However - I don't see how to do that; there doesn't seem to be anything in the UI which would make it happen.

I've tried consulting the user's guide, but it suggests cmake4eclipse will only work for new projects, and only of a certain type ("C Projects" or "C++ Projects" but not "C/C++ Projects").

**Expected behavior**

I expect cmake4eclipse to be able to recognize the fact that my project actually uses CMake, and generates its Makefile that way. Then I expected it to ask for my confirmation to "take over" the project in the sense of running CMake and overwriting the existing Makefile. Of course - with a confirmation dialog of course.

**Useful Information**
* cmake4eclipse version: 2.1.1.202003091558
* OS: Devuan GNU/Linux Beowulf (~= Debian Buster without systemd)
* CMake 3.13.4

**Comment by 15knots** [comment]
cmake4eclipse requires a project created as "C Project" or "C++ Project" to work.
Just select the CMake Driven tool chain and the CMake builder and make sure the source location point to the directory containing the top-level CMakeLists.txt file.

**Comment by eyalroz** [comment]
@15knots : I don't think it can require that, as projects are often simply imported.

**Comment by 15knots** [comment]
@eyalroz It **does** require that. Period.
