### ISSUE TITLE
Eclipse is not able to detect C++11

### ISSUE THREAD

**Issue by baldapps** [15knots/cmake4eclipse#137]
I'm using GCC 4.8.3 on RHEL 7.1. In a project I defined in CMakeLists.txt the CMAKE_CXX_STANDARD to 11, however Eclipse is not able to detect C++11 data structures or functions. In the provider I can see __cplusplus macro to 199703L so there's something strange in the configuration. Is CMake4Eclipse to pick the -std=c++11 option in the compile_commands.json in order to discover even C++11 options in this case? Is there any workaround?

**Comment by baldapps** [comment]
I meant 199711L

**Comment by 15knots** [comment]
cmake4eclipse should honor up the  `-std=c++11` option.

Can you post a commandline from the compile_commands.json here?
What are the first two lines from the Compiler Built-ins Detection Console for your project? 
Note that you will have to enable _Allocate console_... in the Providers tab of the project settings to see that.

**Comment by baldapps** [comment]
I post the first lines of complile_commands.json:

[
{
  "directory": "/home/foo/TestProject/build/Default",
  "command": "/usr/bin/c++  -Dtestproj_EXPORTS -I/home/foo/TestProject/src -I/home/foo/TestProject/build/Default/src   -DCMAKE_COMPILATION -std=c++11 -pedantic -Wall -Wextra -Wconversion -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused -fPIC   -o CMakeFiles/basicsw.dir/src/patterns/command/Executor.cpp.o -c /home/foo/TestProject/src/patterns/command/Executor.cpp",
  "file": "/home/foo/TestProject/src/patterns/command/Executor.cpp"
},

I can't access to the dev machine now so I will provide other information on Monday.

**Comment by 15knots** [comment]
Pls check the console output for the `__cplusplus macro ` definition.
Could be the gcc 4.8.3 ignores the `-std=c++11` option.

**Comment by baldapps** [comment]
It works using the option and compiling manually. However I just tried on my home workstation just to see the output, can you clarify the process? I did: Window->Preferences->C++->Build->Settings->Discovery->CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins and then I checked "Allocate console in console view". In the console view I see: CMake console, CDT Global Build console, CDT Build Console. In CMake console I see:

cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -G "Unix Makefiles" /home/foo/TestProject 
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/foo/TestProject/build/Default

Is it the expected output?

**Comment by 15knots** [comment]
**Compiler Built-ins Detection Console**.
You look at the **CMake console**!

Err, well: It says _compiler identification is GNU 7.5.0_ but your initial comment states
> I'm using GCC 4.8.3

**Comment by baldapps** [comment]
I can't see any "Compiler Built-ins Detection Console". Yes, I know that Gcc is 7.5, because as I said it was just a try on **my home workstation**. My dev workstation uses Gcc 4.8.3 but I can't access to it now.

**Comment by 15knots** [comment]
![Display Selected Console](https://user-images.githubusercontent.com/11367029/83912314-f613fb80-a76d-11ea-8d6c-cb8d80d026cd.png)

**Comment by baldapps** [comment]
As I said I can see there only three console: CMake console, CDT Global Build console, CDT Build Console. I'm using Eclipse 2020-03.

**Comment by baldapps** [comment]
![Screenshot_20200605_210011](https://user-images.githubusercontent.com/14140069/83913674-10e76f80-a770-11ea-898e-f48faf3da057.png)
![Screenshot_20200605_210256](https://user-images.githubusercontent.com/14140069/83913686-16dd5080-a770-11ea-9f10-05689b20fc4b.png)

**Comment by 15knots** [comment]
Forgot to say: Delete file build/<configname>/CMakeCache.txt first.
The parsers cache their findings for performance reasons and won't run (so no console) unless the json file get a newer timestamp.
The global build console will show the content of **Compiler Built-ins Detection Console**, too.

**Comment by baldapps** [comment]
I deleted the build directory and re-build the project. Still nothing. I can't see anything even in the global console. Really no idea.
