### ISSUE TITLE
Parse -include and -imacros compiler flags

### ISSUE THREAD

**Issue by simadin** [15knots/cmake4eclipse#138]
**Is your feature request related to a problem? Please describe.**
In our code we have few auto-generated header files that contain defines that configure any other file. We use compiler flags -include and -imacros to include them by compiler in all compile commands. But these flags are not parsed by cmake4eclipse, and when eclipse indexes the project, it assumes that all the defines in these files are undefined.

**Describe the solution you'd like**
Cmake4eclipse already has the option to parse compiler flags like -D and -I from compile_commands.json, and tell eclipse about defined flags and include directories. Also eclipse has the option to manually add included header files and macro files. Just need to add some code in cmake4eclipse flags parser to parse -include and -imacros flags, so these files will be included automatically by eclipse.

**Describe alternatives you've considered**
The alternative is to add them manually as user defined include files.

BTW, I tried add the relevant code by myself, but the build failed (even without any change) when maven tried to fetch some dependency. I tried both on eclipse-sdk and gitpod.io with the build command from the readme. It's my first time to use maven so maybe I missed something.

**Comment by 15knots** [comment]
What is the compiler you are using? 
If it is *not* gcc, can you point me to an command-line reference?

**Comment by simadin** [comment]
It's GCC. reference [here](https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/Preprocessor-Options.html).
I think that Clang has also support for -include but not -imacros.

**Comment by 15knots** [comment]
Closed in 61b51a67
