### ISSUE TITLE
Offline Installer

### ISSUE THREAD

**Issue by AndrewBrennanCiv** [15knots/cmake4eclipse#139]
Simply looking for an offline installer zip I can use to install this plugin on an air-gapped system.

**Comment by 15knots** [comment]
Am Mi., 8. Juli 2020 um 18:17 Uhr schrieb AndrewBrennanCiv <
notifications@github.com>:

> Simply looking for an offline installer zip I can use to install this
> plugin on an air-gapped system.
>

Read https://github.com/15knots/cmake4eclipse#p2-repositories

**Comment by AndrewBrennanCiv** [comment]
Thank you.
