### ISSUE TITLE
Cmake seems to ignore the environment set in Eclipse

### ISSUE THREAD

**Issue by drolevar** [15knots/cmake4eclipse#14]
When I add a variable to C++ Build->Environment or C++ Build->Build Variables, it's not present in the environment Cmake is used to run from.
For me it means I'll have to either modify my Cmake scripts or skip the plugin for the time being.

**Comment by 15knots** [comment]
Yes currently it does not pass extra variables to the process environment of the cmake process.
IMHO, as much configuration as possible should go in the CMakeLists.txt file, especially when you want to build the project from command-line (or are using a CI server).

What exactly is your use case?

**Comment by drolevar** [comment]
@15knots We have an embedded project, and the CMake script is used with different versions of the compiler and root FS. Those settings are set as environment variables. Currently they are being set with a shell script, but if I would like to use the same CMake project with your plugin (which I think is better than generated Eclipse project) then I'll need this functionality.

**Comment by 15knots** [comment]
OK, I see.
Do you need to pass extra envs to cmake, when it generates the build scripts (`cmake -G "Unix Makefiles"`) or do you want to pass extra envs to the buld tool (`/usr/bin/make` in this case)?

BTW: You might want to try CDT 9.0 RC 2, from their developer mailnig list I know CDT 9 will have cmake support.

**Comment by drolevar** [comment]
I do use toolchain files, however it still would be nice to be able to pass environment variables.
