### ISSUE TITLE
Run cmake and rebuild index without compiling

### ISSUE THREAD

**Issue by DennisSchiefer** [15knots/cmake4eclipse#143]
I would like to be able to only re-run cmake, re-discover everything, and rebuild the index -- all without actually building the project.

Reason:
Building the project can take pretty long locally. Most often, I am only interested in updated code-completion once I pull the latest version. Only rarely, I actually want to build locally.

One workaround that I could see is creating a no-op target in cmakelists.txt, but that feels more like a hack than an integrated solution.

**Comment by 15knots** [comment]
To work-around, you could make it call the 'help' target; it is always there.
Since CDT decides, whether to run the build scripts, this is not easy to accomplish. Cmake4eclipse hooks in as a build-script generator, but does not control to run the build scripts.

**Comment by DennisSchiefer** [comment]
Yes, that would likely work, too.

What I did in my pre-cmake4eclipse days:
Regular building was configured to just use ninja and whatever target I specified.
I also had a special build target in which I overwrote the build command to run cmake instead.
