### ISSUE TITLE
Clang Cross Compilation not supported

### ISSUE THREAD

**Issue by ghaith** [15knots/cmake4eclipse#145]
**Describe the bug**
When compiling a project with clang using the Target option, the builtins detector will not take the --target into account

**To Reproduce**
1. Create a CMake project with a toolchain file with a linux target
2. Load the project on Windows
3. See error

**Expected behavior**
The indexer should reference the correct headers

**Useful Information**
- cmake4eclipse version:  From Source
- Which OS do you use: Windows

I can submit a pull request for the issue soon. I found that an Arglet for "--target" is missing, I just added one that check with --target with a path after it as a quick test and added it to the gcc detector i didn't find a Clang detector

```
public static class Target_Clang extends BuiltinDetectionArgsGeneric implements IArglet {
		private static final Matcher[] optionMatchers = {
				/* "--sysroot=" quoted directory */
				Pattern.compile("--target=" + REGEX_INCLUDEPATH_QUOTED_DIR).matcher(""),
				/* "--sysroot=" unquoted directory */
				Pattern.compile("--target=" + REGEX_INCLUDEPATH_UNQUOTED_DIR).matcher(""),
				/* "-isysroot=" quoted directory */
				Pattern.compile("--target=" + REGEX_INCLUDEPATH_QUOTED_DIR).matcher(""),
				/* "-isysroot=" unquoted directory */
				Pattern.compile("--target=" + REGEX_INCLUDEPATH_UNQUOTED_DIR).matcher("")};

		/*-
		 * @see de.marw.cmake.cdt.lsp.IArglet#processArgs(java.lang.String)
		 */
		@Override
		public int processArgument(IParseContext parseContext, IPath cwd, String argsLine) {
			return processArgument(parseContext, argsLine, optionMatchers);
		}
	}
```

**Comment by 15knots** [comment]
Please submit a pull request.
Tests are welcome, too.
