### ISSUE TITLE
Update site is missing

### ISSUE THREAD

**Issue by tony--** [15knots/cmake4eclipse#148]
**Describe the bug**
When I visit [the update site](https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/) mentioned [in the README](https://github.com/15knots/cmake4eclipse#update-site), I get "400: Invalid request".

**To Reproduce**
1. Go to https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/
2. See error

**Expected behavior**
[The update site](https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/)  should exist at the location identified [in the README](https://github.com/15knots/cmake4eclipse#update-site).

**Screenshots**
<img width="740" alt="Screen Shot 2021-04-13 at 2 28 55 PM" src="https://user-images.githubusercontent.com/513830/114623805-9e370280-9c64-11eb-8369-7d3c752b8a68.png">

**Comment by 15knots** [comment]
The README states: _This composite update site is for use in a **Eclipse workbench**_.
Try  https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/p2.index , like the workbench will do.

**Comment by tony--** [comment]
Thanks @15knots!

**Comment by tony--** [comment]
I would like to read more about raw.githubusercontent.com before I close this one.  I think I might have some additional feedback.
