### ISSUE TITLE
bintray end of service

### ISSUE THREAD

**Issue by tony--** [15knots/cmake4eclipse#149]
**Describe the problem**
Currently p2 repositories are published to bintray, as described [in the README](https://github.com/15knots/cmake4eclipse#p2-repositories).  [According to the explainer](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), bintray stopped accepting new package submissions on March 31, 2021, so new versions of cmake4eclipse cannot be published there.  Additionally, bintray will stop serving packages on February 1, 2022.  

**Expected behavior**
A new p2 hosting solution is needed to publish p2 repositories for cmake4eclipse after 2.1.4.
A new p2 hosting solution is needed to host p2 repositories for older releases before bintray stops serving packages on February 1, 2022.  

**Screenshots**
<img width="1277" alt="Screen Shot 2021-04-13 at 2 31 58 PM" src="https://user-images.githubusercontent.com/513830/114624384-75633d00-9c65-11eb-81f9-3b458dacc98b.png">

**Comment by 15knots** [comment]
Yes, I am aware of the bintray sunset.
Do you know of any free hosting services? I tried jfrog artifactory but since a few days they force me to use a smartphone to log in.

**Comment by tony--** [comment]
Currently your github releases are just snapshots of the repo for a tag, but you can publish binaries too.
https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

Maybe you could move from bintray to github to have everything in one place?

**Comment by tony--** [comment]
To be clear, I haven't set this up one any of my repos so I don't have practical experience, but I use other repos that do this.  For example, AdoptOpenJDK has several repos dedicate to hosting their binaries.  Here is the JDK 11 releases page:
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases

**Comment by tony--** [comment]
Please let me know if this would not work for some reason.  I'm happy to help with some research on this topic.

**Comment by 15knots** [comment]
I do not like the idea to have github host the sources plus the released binaries very much. github.com will become a single point of failure then.
It will also make it painful if I decide to move the source to a different location.

**Comment by tony--** [comment]
Personally, hosting on github seems simplest to me and you could migrate later if you decide to move your source, but here are some other options.

You could migrate to sonatype.  It's not designed for P2 but you can publish artifacts there.  There is a blog post about migrating from bintray to maven central here: https://blog.sonatype.com/dear-bintray-and-jcenter-users-heres-what-you-need-to-know-about-the-central-repository

You could try AWS free tier: https://aws.amazon.com/free
It might be more effort to set up.
Google Cloud has a free tier also: https://cloud.google.com/free/docs/gcp-free-tier

You could email Digital Ocean - I read that they sometimes issue free credits to open source projects:
https://www.digitalocean.com/open-source/

**Comment by jolz** [comment]
maybe something here: https://free-for.dev/#/?id=cdn-and-protection (sorry, no own experience)

**Comment by tony--** [comment]
Apparently I was mistaken in my original comment when I stated, "Additionally, bintray will stop serving packages on February 1, 2022.".  Actually this only applied to JCenter (and for JCenter it has been changed to packages being served indefinitely).

Other bintray downloads, including cmake4eclipse, are no longer available as of [yesterday](https://status.bintray.com/incidents/5l4dhjq7g7mn).  Now all of [the files links](https://bintray.com/15knots/p2-zip/cmake4eclipse#files) return "Forbidden!".

**Comment by manschwetusCS** [comment]
Looks like, I tried to install cmake4eclipse, but no way.
Is it possible to attach latest release here as archive, as intermediate solution?
@15knots I know I owe you a test of a fix #119, is it in the latest release or would I need to use a special snapshot anyway?

**Comment by jannemann70** [comment]
@15knots : Very useful plugin - thanks a lot for your work! Hope you'll find a new suitable hosting service soon. Any actual news? I'm absolutely not familiar building Eclipse PlugIns. Do you have some starting point documentation for building this plugin from source?

**Comment by manschwetusCS** [comment]
@jannemann70 I tried, but it looks like, that sundown of bintray also affected hosting of some dependencies, so maven can't build a fresh checkout due to unavailable dependencies

**Comment by 15knots** [comment]
I am working on this to publish the binaries on github, please be patient.
In the mean time, you may find the p2 repo on GH Packages (https://github.com/15knots?tab=packages&repo_name=cmake4eclipse)

**Comment by 15knots** [comment]
In case anyone else is looking for a place to store files for free download, here's what I found:

1. Github pages. This is a maven repository. It requires user authentication to download. I managed to put together an update URL with authentication info like https://<user>:<GHP-token>@maven.pkg.github.com/15knots/cmake4eclipse/... That URL work with curl and wget, but not with eclipse.
2. Jfrog Cloud . Allows to store plain files (i.e. no maven layout enforced). It reached the free monthly usage limit after two weeks. Their web-UI forces me to buy a smartphone to log in.
3. Cloudsmith.io. Their web-UI confused me a little. I had to struggle a little to set up a robot account for uploading from travis-ci. According to the emails they sent me I'm not quite sure whether I had their free tier.

**Comment by rhaley-starfish** [comment]
Hi, not complaining, just posting more info. The site https://fifteenknots.jfrog.io/artifactory/p2-zip/cmake4eclipse-2.1.3.zip returns:

{
  "errors" : [ {
    "status" : 429,
    "message" : "You have reached your monthly quota for Data Transfer. To continue and start enjoying unlimited transfer, upgrade your subscription"
  } ]
}

Honestly I think sorceforge offers a far better service for a project like this. Also if interested in corporate sponsorship, I could talk to the owner at starfishmedical.com and see if we could do a mirror?

**Comment by mindThomas** [comment]
Can someone who has the zip files for the recent builds of `cmake4eclipse` and `cmakeed` please upload them to SourceForge?
https://sourceforge.net/projects/cmakeed/files/

**Comment by 15knots** [comment]
@rhaley-starfish  You get the 409 status because a single IP address downloads the latest revision every 2 minutes which exhasts the monthly quota for Data Transfer :-(
The same happened around April 15.

**Comment by mindThomas** [comment]
@15knots How about blocking them then: https://jfrog.com/blog/ip-restriction-with-white-cidr-and-black-cidr/

**Comment by danderson-presonus** [comment]
As mentioned on #153 , build-from-source seems to be broken, at least on Ubuntu 20.04.  Is there an un-listed dependency or something?  Some way for us to get this in the absence of hosting for the binaries?

**Comment by mandeepsingh-private** [comment]
[https://cloudsmith.io/~15knots/repos/p2-zip/packages/detail/cmake4eclipse-214zip-30l/#metadata](https://cloudsmith.io/~15knots/repos/p2-zip/packages/detail/cmake4eclipse-214zip-30l/#metadata)

This link worked for me. I downloaded the zip file and then in my eclipse pointed to downloaded zip to install it.
