### ISSUE TITLE
Composite update site references version 1.4.1

### ISSUE THREAD

**Issue by drolevar** [15knots/cmake4eclipse#15]
The composite update site still references version 1.4.1 instead of 1.4.2.
The readme file also mentions the link to version 1.4.1 under the description of 1.4.2.

**Comment by 15knots** [comment]
> The composite update site still references version 1.4.1 instead of 1.4.2.

Not sure, what's going wrong at your site. 
https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/compositeContent.xml already references cmake4eclipse-1.4.2.zip 

Plus 'Help|Check for Updates' find the new version here.
