### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS parser doesn't support target triplets for gcc

### ISSUE THREAD

**Issue by pgasior** [15knots/cmake4eclipse#16]
CMAKE_EXPORT_COMPILE_COMMANDS parser should support gcc target triplets such as `arm-none-eabi`. When I try to use such toolchain I get warning and no include paths are detected: `/blinky/build/Debug/compile_commands.json: No parser for command 'C:/ARM/gcc/5_4_2016q2/bin/arm-none-eabi-gcc.exe  -DSTM32F4 -DSTM32F429xx -IC:/ARM/stm32cmake/stm32-cmake/stm32-blinky -IC:/ARM/CUBE/F4/STM32Cube_FW_F4_V1.12.0/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/ARM/CUBE/F4/STM32Cube_FW_F4_V1.12.0/Drivers/CMSIS/Include -IC:/ARM/CUBE/F4/STM32Cube_FW_F4_V1.12.0/Drivers/STM32F4xx_HAL_Driver/Inc  -mthumb -fno-builtin -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -Wall -std=gnu99 -ffunction-sections -fdata-sections -fomit-frame-pointer -mabi=aapcs -fno-unroll-loops -ffast-math -ftree-vectorize -Og -g   -o CMakeFiles/stm32-blinky.dir/main.c.obj   -c C:/ARM/stm32cmake/stm32-cmake/stm32-blinky/main.c', skipped `

**Comment by 15knots** [comment]
The CMAKE_EXPORT_COMPILE_COMMANDS parser now knows about GCC cross compilers for C and C++ if the compiler executable follows the naming convention of
`<target_triplet>-gcc` or `<target_triplet>-g++`. 
Most of the cmake toolchain-files on the web follow that naming convention.

See definition of [target_triplet](http://wiki.osdev.org/Target_Triplet).
