### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS: Add more compiler options that affect built-in detection for gcc

### ISSUE THREAD

**Issue by ceggers-arri** [15knots/cmake4eclipse#163]
**Is your feature request related to a problem? Please describe.**
I use xc16-gcc. This compiler requires setting -mcpu=xxx for getting the correct set of built-in defines.

**Describe the solution you'd like**
Beside the arguments "-E -P -dM -Wp,-v", additional parameters are required
(e.g. ${CMAKE_C_FLAGS}).

**Describe alternatives you've considered**
Currently I use the "CDT Cross GCC Built-in Compiler Settings" provider instead.
This seems to work fine.

**Comment by 15knots** [comment]
Sorry, but since #157, there are no plans to maintain the CMAKE_EXPORT_COMPILE_COMMANDS* parsers any longer. The code for theses parsers has been ported to CDT-core (package org.eclipse.cdt.jsoncdb).
Please consider to file an issue in CDT.

BTW: Wouldn't it make sence to also recogize the `-march` and `-mtune` options? From what I understand the gcc manpage, these options also have an effect on compiler built-in values.

**Comment by ceggers-arri** [comment]
Thanks for for pointing this out. Seems that it's time to move to a more recent Eclipse/CDT...

> BTW: Wouldn't it make sense to also recognize the -march and -mtune options? From what I understand the gcc manpage, these options also have an effect on compiler built-in values.

Probably all options which affect the builtin preprocessor definitions / include paths should by recognized. But problems will arise if some settings are not consistent for all source files. Maybe the only way is to configure this manually (e.g. using the _GCC Cross GCC Built-in Compiler Settings_ plugin).

**Comment by 15knots** [comment]
@ceggers-arri: Do you know of more options that affect gcc built-in detection than the -`march`, -`mtune` and -`mcpu` options?
The detector in CDT already knows about `-std` and `-ansi`.

**Comment by ceggers-arri** [comment]
What about `-pthread`?

**Comment by 15knots** [comment]
Yep. It gives
`#define _REENTRANT 1`

**Comment by 15knots** [comment]
Created https://bugs.eclipse.org/bugs/show_bug.cgi?id=578223

**Comment by 15knots** [comment]
Closed in CDT
