### ISSUE TITLE
The script under "Build Targets" is not invoked

### ISSUE THREAD

**Issue by grachchr** [15knots/cmake4eclipse#168]
### Describe the bug
As a sample project I have chosen the C-flat project from the "cmake4eclipse-sample-projects" package. In this project I enable to build with docker.
My project setup is described below.

I am trying to include additional build scripts to the C-flat project via the "Build Targets". But the script is not invoked.

### Setup
Source code and project's are mounted at the same location within the container. The Eclipse ".project" file can refer relatively to the source code. This allows the indexer to work without errors.

Example-Tree:
```
/mnt
| - MyMount
    | - MyScripts
    | - MyCommonSrcs
    | - OtherEclipseProjects
    | - cmake4eclipse-sample-projects
        | - C-1src
        | - C-flat
            | - main.c
            | - .cproject
            | - .project
            | - CMakeLists.txt
```
Example for .project file:
```
<link>
  <name>My_Virtual_Link_SrcDir/main.c</name>
  <type>1</type>
  <locationURI>PARENT-2-PROJECT_LOC/My_Relative_Location_SrcDir/main.c</locationURI>
</link>
```
**Docker-Setup**
A Docker container have all my depencies installed (runtime configuration for building and debugging). There is no gcc and CMake installed on the host, only in the Docker container.

**Eclipse-Setup**
- Project: C++ Project
- Project Type: Cmake4eclipse (Toolchain: CMake driven)

**Eclipse-Docker-Setup**
- Enable "Build inside Docker Image".
`  EclipseProject -> Properties -> C/C++Build -> Settings -> Container Settings -> Build Inside Docker Image`
- Select a docker image
`  .. -> C/C++Build -> Settings -> Container Settings -> Image => docker.xxx.com/yyy/zzz:202009234`
- Mount host directories to docker
```
  .. -> C/C++Build -> Settings -> Container Settings -> Add 
         -> Container path => /mnt
         -> Mount a host directory or host file => /mnt
```
  In the directory /opt is my eclipse working space (/opt/eclipse/MyWs) 
```
  .. -> C/C++Build -> Settings -> Container Settings -> Add 
         -> Container path => /opt
         -> Mount a host directory or host file => /opt
```

### Describe the problem
Add additional build script to the C-flat project.
```
Build Target -> Target name => my_build
Build Target -> Build command => "/mnt/MyMount/MyScripts/my_build.sh" "arg1" "arg2"
```
Unfortunately the script ("/mnt/MyMount/MyScripts/my_build.sh") is not invoked. The "CDT Build Console" output is:
```
11:31:02 **** Build of configuration Debug for project C-flat ****
[Running in image <docker.xxx.com/yyy/zzz:202009234>]
/usr/bin/make arg1 arg2 my_build
make: *** No rule to make target 'arg1'.  Stop.
"/usr/bin/make arg1 arg2 my_build" terminated with exit code 2. Build might be incomplete.
``` 

### Expected behavior
I expect to invoke the script (/mnt/MyMount/MyScripts/my_build.sh arg1 arg2 my_build):
```
11:31:02 **** Build of configuration Debug for project C-flat ****
[Running in image <docker.xxx.com/yyy/zzz:202009234>]
/mnt/MyMount/MyScripts/my_build.sh arg1 arg2 my_build
```
In the versions before it worked.
OS: Debian 10 (Buster)
Eclipse : Version: **2020-06 (4.16.0)** Build id: 20200615-1200
cmake4eclipse **2.1.4**.202103291945
CMake version: 3.13.4

### Useful Information
OS: Debian 10 (Buster)
Eclipse: Version: **2021-12 (4.22.0)** Build id: 20211202-1639
cmake4eclipse **3.0.2**.202202072019
CMake version: 3.13.4

**Comment by 15knots** [comment]
Thank You for providing the wotkbench setup details for building in a docker container!

Let me note that this issue is **not** related to  building in a docker container. It is a regression due to the fact that I never thought that these 'Build Target' entries could be used as a replacement for Eclipse's _External Tools_ settings.
