### ISSUE TITLE
Cmake4eclipse User Guide:Tasks

### ISSUE THREAD

**Issue by woodz-** [15knots/cmake4eclipse#170]
Cant find that documentation for existing projects (Cmake4eclipse User Guide:Tasks) inside eclipse IDE, since the Help browser fails to serve (Version 2021-12):

    HTTP ERROR 500 org.apache.jasper.JasperException: PWC6033: Error in Javac compilation 
    for JSP PWC6197: An error occurred at line: 41 in the jsp file: /index.jsp PWC6199: Generated 
    servlet error: System cannot be resolved

Is the documentation out in the net anywhere?
Or even better, wouldn't it be possible to include this documentation to the this project's markdown?

**Comment by 15knots** [comment]
Sorry, I cannot reproduce the exception with cmake4eclise 3.0.2 here.

**Comment by woodz-** [comment]
Thanks for answering.
The exception is rising in Linux x86_64 cdt eclipse 2021-12 when choosing the Help menue and has nothing to do with cmake4eclise.

But since I can not watch the Help system from within eclipse because of this exception, my question was, whether the Information is available in the internet anywhere.

In your markdown, you mention, if one already has a cmake project, he should do:
Help: cmake4eclipse User Guide:Tasks

For me that means, if cmake4eclipse plugin is installed one can read instructions from within the eclipse Help.

But is that instruction also available on the net. Or wouldn't it be possible to include that instruction in your markdown, instead of pointing users to external resources?

**Comment by 15knots** [comment]
The online documentation is not written in markdown, it is in a HTML variant with some Eclipse-specific tags.
The raw help files can be found here: https://github.com/15knots/cmake4eclipse/tree/master/de.marw.cmake4eclipse.mbs.ui/doc/html

**Comment by woodz-** [comment]
OK, that's a bir a hassle to read.
I picked an earlier version of the IDE 2019-12.
The help browser will not rise an exception there, that's good.
Now I'd like to install cmake4eclipse in there.
The Marketplace is not an option, since it delivers always the latest version, currently 3.0.2.
When I am not too wrong, I guess I need some version around [R_v2.0.0](https://github.com/15knots/cmake4eclipse/releases/tag/R_v2.0.0)
I tried Install new Software... pointing to that URL, but there are no eclipse plugin packages found.
So the question is, is there a common resource from wehre to pick earlier versions into Available Software - work with  dialog?

**Comment by 15knots** [comment]
See https://github.com/15knots/cmake4eclipse#p2-repositories

**Comment by woodz-** [comment]
Oh, that was an accident.
Using cmake4eclipse-2.1.3.zip on IDE 2019-12 destroyed my cdt tooling. Now uninstalling cmake4eclipse doesn't repair it.
There is no zip for version 2.0.0, so I chose the next higher available.
It was a bad idea to do so, I wasn't aware of such a risk.
