### ISSUE TITLE
docker build and additional include pathes: eclipse doesn't find the includes

### ISSUE THREAD

**Issue by ChristianS99** [15knots/cmake4eclipse#172]
we have a project, that we need to build for different Ubuntu Versions, so we try to use docker container for this.

it's also build with cmake, so we are using cmake4eclipse (2.1.4.202105301214, i.e. most recent). Standard system headers are found and can be accessed with F3, but library headers, that need a -I compile directive don't work. My guess is, that the CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-Ins provider is prefixing the pathes with the right path, where eclipse copies them:

![grafik](https://user-images.githubusercontent.com/5791486/166246626-90b8705f-78a4-4b01-9715-e0a6e0a00505.png)

while the CMAKE_EXPORT_COMPILE_COMMANDS Parser provider doesn't:

![grafik](https://user-images.githubusercontent.com/5791486/166246899-3ac08e20-3f17-458d-ad61-d75bfbfdf2e8.png)

Not sure, though, if this plugin is faulty here or eclipse itself, but I guess, someone here can tell me :)

**Comment by 15knots** [comment]
First of all: Most recent version of cmake4eclipse is 3.0.3.

Could you tell **which** include paths specified through `-I` are missing in the CMAKE_EXPORT_COMPILE_COMMANDS Parser?

**Comment by ChristianS99** [comment]
> First of all: Most recent version of cmake4eclipse is 3.0.3.
Hm, my eclipse has 2.1.4.202105301214 and hitting the update button tells me, there are no updates. I have the Update Site enabled as stated in Readme. Don't know why I don't get the newer release...

> Could you tell **which** include paths specified through `-I` are missing in the CMAKE_EXPORT_COMPILE_COMMANDS Parser?
They are not missing, they are there like eg. /usr/include/sofia-sip-1.12. Problem is, that I don't have any include files there **in my host fs**, but in the docker image, there are includes at this location. After a build, eclipse copies headers from the docker image to my host fs some where in this longy workspace path.
See the first screenshot (sorry, the pathes aren't complete there, didn't notice):
These are the system pathes like /usr/include, /usr/local/include... prefixed with /home/chriss/Radiodata/DipraSwitch/eclipse-workspace/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/ubuntu-ds_20_04
the prefix is the location, where eclipse copies the headers after the build.
I guess, the problem that eclipse doesn't find the additional headers is, that this prefix is missing for the additional include pathes.

Example: The project is using Boost, that doesn't require an additional -I, because it is custom to write includes like #include <boost/regex.hpp> If I hit F3 on this include eclipse opens /home/chriss/Radiodata/DipraSwitch/eclipse-workspace/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/ubuntu-ds_20_04/usr/include/boost/regex.hpp as it should.

On the other hand, sofia-sip headers are (in the image) in a path like /usr/include/sofia-sip-2.12/sofia-sip/sip.h. This header get's copied by eclips to /home/chriss/Radiodata/DipraSwitch/eclipse-workspace/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/ubuntu-ds_20_04/usr/include/sofia-sip-1.12/sofia-sip/sip.h
It is used as #include <sofia-sip/sip.h> When I hit F3 on this header, eclipse doesn't find it, because, as I think, the additional include is /usr/include/sofia-sip-1.12 when it should be /home/chriss/Radiodata/DipraSwitch/eclipse-workspace/.metadata/.plugins/org.eclipse.cdt.docker.launcher/HEADERS/unix_var_run_docker_sock/ubuntu-ds_20_04/usr/include/sofia-sip-1.12/sofia-sip/sip.h

**Comment by 15knots** [comment]
What confuses me is: Where does the CMAKE_EXPORT_COMPILE_COMMANDS Parser get the include directories from? 
It just parses the compile_commands.json file produced by cmake. So my guess is that some of your CMakeLists.txt adds the include paths.

**Comment by ChristianS99** [comment]
yes, in my CmakeLists.txt, the packages are searched and include pathes added when needed. Just like usual.

**Comment by 15knots** [comment]
Not much what I could do here: The _CMAKE_EXPORT_COMPILE_COMMANDS  * Parser_ s have been deprecated and are no longer maintained #157.
Please update to the most recent version of CDT and cmake4eclipse and switch to the _CMake Compilation DB_ provider which is based on the code in CDT.
If you get the same behavior then, pls file a bug in CDT.

**Comment by ChristianS99** [comment]
Hm, still wasn't able to update cmake4eclipse plugin. After deinstalling, I was able to install cmake4eclipse in version 3.0.3. Don't know, what the problem was.
Now, I have CMake Compilation DB as include provider. unfortunately, it's worse than before. No headers from image are copied at all, eclipse tries to find headers with path from image on my host fs.
So practically not usable :(

Thx for looking into this, will try at CDT

**Comment by 15knots** [comment]
Could this be related to CDT Bug 579668 - Regression in Docker header file support?

**Comment by ChristianS99** [comment]
Yes, that looks like the problem I have. I'll keep an eye on it. THX!

**Comment by 15knots** [comment]
After som investigation I found that CDT's ContainerCommandLauncherFactory kicks in and adds the prefixes when the compiler is run to print its built-ins.
In contrast, the CMAKE_EXPORT_COMPILE_COMMANDS Parser does **not** run a program, hence no prefixes are added.

**Comment by ChristianS99** [comment]
thx, that seems better now.
at least the pathes in cmake Compilation DB are prefixed.
Still, the headers can't be opened, but that's probably because they are not copied from container to the host fs.
But that's not cmake4eclipse's fault, I guess
