### ISSUE TITLE
v3.0.4 fails to install in NXP MCUXpresso 11.5.1

### ISSUE THREAD

**Issue by bowerymarc** [15knots/cmake4eclipse#173]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here.

**Describe the bug**
Clean install of NXP MCUXpresso 11.5.1, trying to install cmake4eclipse from marketplace

**To Reproduce**
1. Go to Eclipse Marketplace
2. Click on cmake4eclipse
3. Scroll down to install

**Expected behavior**
Should install cleanly

**Screenshots**
attached.
![Screenshot 2022-05-19 170221](https://user-images.githubusercontent.com/5532521/169405762-881f655b-502d-47b7-b326-d762387d7336.png)

**Useful Information**
- cmake4eclipse version: 3.0.4 (marketplace still says 3.0.3)
- Which OS do you use:  Windows 10
- Cmake version:  3.22.3

***What is in Eclipse's Error Log?***
!ENTRY org.eclipse.equinox.p2.operations 4 10053 2022-05-19 16:57:03.833
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10053 2022-05-19 16:57:03.833
!MESSAGE Cannot complete the install because one or more required items could not be found.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2022-05-19 16:57:03.833
!MESSAGE Software being installed: cmake4eclipse 3.0.4 (de.marw.cmake4eclipse.feature.feature.group 3.0.4)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2022-05-19 16:57:03.833
!MESSAGE Missing requirement: cmake4eclipse CDT CMake build integration 1.0.4.202205162008 (de.marw.cmake4eclipse.mbs 1.0.4.202205162008) requires 'osgi.bundle; org.eclipse.cdt.core 7.3.0' but it could not be found
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2022-05-19 16:57:03.833
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2022-05-19 16:57:03.833
!MESSAGE From: cmake4eclipse 3.0.4 (de.marw.cmake4eclipse.feature.feature.group 3.0.4)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2022-05-19 16:57:03.833
!MESSAGE To: org.eclipse.equinox.p2.iu; de.marw.cmake4eclipse.mbs [1.0.4.202205162008,1.0.4.202205162008]
Sanitized stack traces:

**Additional context**
Same thing happens in MCUXpresso 11.4.1.
Same thing happens when installing from https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/

**Comment by ehntoo** [comment]
cmake4eclipse relies on CDT v 10.5 or newer and Eclipse v 2021-12 or newer. MCUXpresso 11.5.1 is based on CDT 10.3.3 and Eclipse v 2021-06. The previous 2.1.4 release of cmake4eclipse available from the install site should still work, or wait for the next MCUXpresso release that will hopefully upgrade to a newer Eclipse/CDT base.
