### ISSUE TITLE
Support multiple source location

### ISSUE THREAD

**Issue by ydaveluy** [15knots/cmake4eclipse#176]
**Is your feature request related to a problem? Please describe.**
cmake4eclipse only support to specify one source directory: project properties --> C/C++ General --> Paths and Symbols --> Source location.

e.g: For the following project architecture

```
project/
    include/
    src/
    CMakeLists.txt
```
It requires to specify "." as source location instead of include and src. This means that include and src folders does not have the C/C++ folder icon of CDT. Creating new class with the wizard generate protection guard with include prefix (e.g: #define INCLUDE_MYCLASS_HPP instead of MYCLASS_HPP). Renaming of source subfolder often breaks includes.

**Describe the solution you'd like**
I would like to be able to configure multiple source directories (e.g: src, src-gen, include, include-gen) and to configure the root cmake location separately (e.g: ".")

**Describe alternatives you've considered**

I tried the following patch that assume that if multiple source location are specified, the root folder is the project and it seems to work perfectly.
NB: This patch does not permits to configure the cmake root folder.
```

--- a/de.marw.cmake4eclipse.mbs/src/main/java/de/marw/cmake4eclipse/mbs/internal/BuildscriptGenerator.java
+++ b/de.marw.cmake4eclipse.mbs/src/main/java/de/marw/cmake4eclipse/mbs/internal/BuildscriptGenerator.java
@@ -208,13 +208,13 @@ public class BuildscriptGenerator implements IManagedBuilderMakefileGenerator2 {
         MultiStatus status = new MultiStatus(Activator.PLUGIN_ID, IStatus.ERROR, msg + " " + project.getName(), null);
         createErrorMarker(project, msg);
         return status;
-      } else if (srcEntries.length > 1) {
-        final String msg = "Only a single source directory is supported";
-        MultiStatus status = new MultiStatus(Activator.PLUGIN_ID, IStatus.ERROR, msg, null);
-        // if multiple projects are build, this information is lost when a new console is opened.
-        // So create a problem marker to show up in the problem view
-        createErrorMarker(project, msg);
-        return status;
+//      } else if (srcEntries.length > 1) {
+//        final String msg = "Only a single source directory is supported";
+//        MultiStatus status = new MultiStatus(Activator.PLUGIN_ID, IStatus.ERROR, msg, null);
+//        // if multiple projects are build, this information is lost when a new console is opened.
+//        // So create a problem marker to show up in the problem view
+//        createErrorMarker(project, msg);
+//        return status;
       } else {
         srcEntries = CDataUtil.resolveEntries(srcEntries, cfgDes);
       }
@@ -289,7 +289,7 @@ public class BuildscriptGenerator implements IManagedBuilderMakefileGenerator2 {
     } catch (IOException ignore) {
     }
     final IPath srcPath = srcEntry.getFullPath();
-    IContainer srcDir = srcPath.isEmpty() ? project : project.getFolder(srcPath);
+    IContainer srcDir = srcEntries.length > 1 || srcPath.isEmpty() ? project: project.getFolder(srcPath);
 
     checkCancel();
     MultiStatus status = invokeCMake(srcDir, buildFolder.getLocation(), console);

```

**Comment by 15knots** [comment]
Your proposed solutions implicitely requires that the CMakeLists.txt file is in the project root if more than one source locations is specified. This is not necessarily the case and might confuse users.
A better solution would be to ignore the source location at all for buildscript generation and let users specify a CMakeLists location instead.

**Comment by ydaveluy** [comment]
Yes I agree.
Are you interested by a PR ?

**Comment by 15knots** [comment]
Concerning the CMakeLists location, IMHO this should be independent of any project configuration (Debug/Release).
If you know how to store that CMakeLists location in the .cproject file, a PR is highly welcome.

**Comment by ydaveluy** [comment]
Ok please find this PR #177 

It stores in the .cproject the attribute rootDir:
`<storageModule buildDir="_build/${ConfigName}" dirtyTs="1668726139357" moduleId="de.marw.cmake4eclipse.mbs.settings" rootDir="">`

In case the attribute is not set and only one source location is specified, the source location is used (current behavior).

However this attribute is dependent from the configuration (Debug/Release): I don't know how to make it independent.

For your information, I think there is a bug at this [line](https://github.com/15knots/cmake4eclipse/blob/363360fe35f4b7f64754ca630cf06fb436947922/de.marw.cmake4eclipse.mbs.ui/src/de/marw/cmake4eclipse/mbs/ui/CMakePropertyTab.java#L157): it should be setText instead of insert.
I can update the PR to fix it if you wants.
