### ISSUE TITLE
Provide CTest view to run tests

### ISSUE THREAD

**Issue by ydaveluy** [15knots/cmake4eclipse#178]
**Is your feature request related to a problem? Please describe.**
Launching tests from a cmake project requires to add a build target "test" and test results are printed in the console.
There is no user-friendly way to run a specific test from the UI.

**Describe the solution you'd like**
It would be great to have a view similar to JUnit test or C/C++ Unit. It would permit to run a specific test from the UI in debug or release mode, status of executed tests, ...

The command `ctest --test-dir _build/Debug --show-only=json-v1` prints a json with for each test the command to run.
The CTest view could rely on this command to build the UI.
It could be possible to add in the contextual menu of the project a command "Test Project" next to "Build Project" and "Clean Project". This command would open the CTest view and run all tests. This command should be only available for projects with the cmake4eclipse builder.

**Comment by 15knots** [comment]
Sorry, this is out of scope of cmake4eclipse.
At least, I have not enogh time to code and maintain that.
