### ISSUE TITLE
CDT Build does not start (do anything) after cmake configuration

### ISSUE THREAD

**Issue by ToBoMi** [15knots/cmake4eclipse#184]
Hi, I started to test #175 and #180. Thanks for your help here.

### Testing with a production project

I use a production project for testing. I think it is a mid size project. I had to add the cmake executable folder to the path and then the project configures succeessfully for one configuration from the `CMakePresets.json`.

After that nothing happens. No build is started automatically.
_Interestingly the CDT build console opens, but remains empty._
I expect the CDT build to start automatically, because the cmake4eclipse help (internal eclipse help contents) in section "Creating a C or C++ Managed Build project and configuring it" state:

> 10.Build the project. This will first invoke cmake to generate the build scripts and then pass control to CDT to run the generated scripts.

I think that nothing happens because there are no outputs on the console and no binaries are build. (I do cross compile to arm hardware with gcc/g++ by the way).
I expect it to show something on that console because the eclipse cmake4eclipse help also states:
> To examine the full build log, open Eclipse`s Console View, then set it to display the CDT Global Build Console. There is also a CMake Console which will display the output of the most recent cmake invocation only. 

### Testing with a sample project

Since I don't get any output anywhere and I don't yet want to inspect the code I tested a [sample project](https://github.com/15knots/cmake4eclipse-sample-projects).
After telling cmake where to find the compiler and the generator (ninja) and test compile to a static library (compile a simple test program) it configures the project [C-multiconfig](https://github.com/15knots/cmake4eclipse-sample-projects/tree/master/C-multiconfig) sucessfully.
The build is automatically starts afterwards. (The build fails because of a wrong usage of the linker and I cannot see any invocation of the compiler, but I just wanted to test if a sample project automatically starts the build.

Can you help me finding the cause of the build not starting in the production project?

**Comment by 15knots** [comment]
Did you try to manually start the build? Maybe you missed to configure the project or workbench to build automatically?

**Comment by ToBoMi** [comment]
Uhm, I double clicked on the build target `all`. If this is a manual start, then yes.

_I have to admit that I don't really know if that is a target I want to build. I am not really familiar with make build targets in general, but `all` builds all, right? Cannot be that wrong._

**Comment by 15knots** [comment]
By convention, target `all` builds everything.
cmake also creates a target `help` that shows the available targets.
