### ISSUE TITLE
Support custom compilers

### ISSUE THREAD

**Issue by kuch3n** [15knots/cmake4eclipse#185]
**Is your feature request related to a problem? Please describe.**
AFAIK are different compilers not supported by CMake Compilation DB, like chc12.exe. But do have the same input arguments like `-I cool_header.h`, so would be awesome to see custom compilers supported.

Also, 

**Describe the solution you'd like**
Seperate checkbox and input field to give an compiler regex, just like `CDT GCC Build Output Parser`

**Describe alternatives you've considered**
A combination of `CDT GCC Build Output Parser` and `Compilation Database Parser` with regex `([^/\\\\]*)((g?cc)|([gc]\+\+)|(clang)|(chc12))`

**Additional context**
pretty please gib custom compilers support

**Comment by 15knots** [comment]
cmake4eclipse uses the Compilation DB parser in CDT cmake core build.
To support custom compilers, compiler vendors will have to implement a `IToolDetectionParticipant` and add it thtough teeh extension point `org.eclipse.cdt.jsoncdb.core.detectionParticipant.`
Basically, a `IToolDetectionParticipant` evaluates the compiler arguments of interest and ignores any others.
See [CDT's nvcc](https://github.com/eclipse-cdt/cdt/blob/main/jsoncdb/org.eclipse.cdt.jsoncdb.nvidia/src/org/eclipse/cdt/jsoncdb/nvidia/NvccToolDetectionParticipant.java) for an example.
