### ISSUE TITLE
Can be the path to CMakeLists.txt changed?

### ISSUE THREAD

**Issue by coran21** [15knots/cmake4eclipse#186]
I'm using your plugin with Zephyr RTOS which has the option to use a high-level build system called "sysbuild". To use it is necessary to add `-DAPP_DIR=....`   which tells the sysbuild where is the main application and change the path where cmake is looking for CMakeList.txt from the project path to the path where is the sysbuild. 
Currently, cmake4eclipse uses the project path, is there any possibility of changing this path to user-selected one?

Example:

current command:
`cmake -DCMAKE_BUILD_TYPE:STRING=Release -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON path_to_project `

expected command
`cmake -DCMAKE_BUILD_TYPE:STRING=Release -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON path_to_sysbuild`

**Comment by 15knots** [comment]
Yes, since v 4.0.0 this can be changed in the project properties on the node _Project Settings_

**Comment by coran21** [comment]
Yes, that worked, thank you!
