### ISSUE TITLE
"CMake Compilation DB" provider provides C++ include paths for C language

### ISSUE THREAD

**Issue by pitti98** [15knots/cmake4eclipse#189]
In "C/C++General/Preprocessor Include Paths/Entries" the include path list is the same for both languages, but for "GNU C", the C++ specific include paths should be missing.

If I enable console output for the discovery step, I can see that there are two runs, one for gcc and one for g++, so the lists really should be different.

Also, the macros are missing, and only the include paths are listed. I don't know if this is supposed to be like that or not. The old cmake4eclipse 2.x.x providers listed defines, and CDT's own providers do it as well.

cmake4eclipse version:  4.0.2

**Comment by 15knots** [comment]
The "CMake Compilation DB" provider does not maintain the entries per-language, it maintains it per-source-file. So it would not make sense to show macros in the tab.
The include paths of each source file are merged and added  to the project resource to make them show up in the UI in the includes folder. As a side effect, they get displayed in the provider's tab.

To see the effective include paths and macros of a file, open it in the editor and select 'Project | C/C++ Index | Create Parser Log file'.

**Comment by pitti98** [comment]
Oh, interesting. That also sounds like the "Compiler builtins" step is not needed at all anymore? But it also means a discovery call to the compiler must be done for each source file separately?
Or is the list of one source file a merge of the builtins discovery plus the -I and -D arguments from the commands.json?
I see two discovery calls, one for each language, so I'm a little confused as to how it works, because now you say "does not maintain the entries per-language".
But anyway, if it all works like it's supposed to work, then I guess it's not a bug, just me being confused.

**Comment by 15knots** [comment]
> Oh, interesting. That also sounds like the "Compiler builtins" step is not needed at all anymore? But it also means a discovery call to the

Not needed. The parser knows which compilers support built-in detection and handles that automatically.

> compiler must be done for each source file separately? Or is the list of one source file a merge of the builtins discovery plus the -I and -D arguments from the commands.json? I see two discovery calls, one for each language, so I'm a little confused as to how it works, 

One for each compiler, at least. But if you specify compiler option for a cmake target that affect built-ins (like -m32 for gcc), you will see two discovery calls.
