### ISSUE TITLE
Adding cmake cache entries corrupts the file .cproject

### ISSUE THREAD

**Issue by arnaud-m** [15knots/cmake4eclipse#191]
**Describe the bug**

The c++ project is no longer usable after adding a CMake cache entry.
_Project -> Properties -> C/C++ Build -> Cmake4eclipse -> CMake cache entries_.
Any operation on the project fails with the following error message: _Path must include project and resource name_.  

After some search, it appears that the entry below corrupts the .cproject file. 
```xml
<storageModule buildDir="" dirtyTs="1697785579512" moduleId="de.marw.cmake4eclipse.mbs.settings">
<options/>
<defs>
<def name="test" type="STRING" val="test"/>
</defs>
</storageModule>
```
The project is usable again by simply removing these lines from the .cproject file. 

**To Reproduce**
1. Go to a c++ project.
2. Add an entry to _Project -> Properties -> C/C++ Build -> Cmake4eclipse -> CMake cache entries_.
3. Restart eclipse.
4. Click on the project in the explorer, or try to build it, or to access the project settings

**Expected behavior**
Eclipse should restart normally with the newly added CMake cache entry,

**Useful Information**
- Eclipse version: Version: 2023-09 (4.29.0) ; Build id: 20230907-1323
- cmake4eclipse version:  4.0.2
- Which OS do you use: Fedora Linux 38
- Cmake version: 3.27.4

***What is in Eclipse's Error Log?***

Sanitized stack traces:
```
!ENTRY org.eclipse.e4.ui.workbench 4 2 2023-10-19 20:38:20.143
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench".
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /PROJECT
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2228)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
```

Thanks for your help.

**Comment by 15knots** [comment]
Sorry, I cannot reproduce this.

**Comment by arnaud-m** [comment]
Thank you for your response. 
Do you need any other information ?

**Comment by 15knots** [comment]
It does not seem to be related to the cache variable.
But I can reproduce the issue when I clear the build-root setting in the project properties.

**Comment by 15knots** [comment]
Can you confirm that this is not related to a CMake cache entry but to an empty build dir setting?

**Comment by arnaud-m** [comment]
Hello,

Indeed, the project and the build are working well when :
- I clear the buildDir setting ; 
- or I update the buildDir setting with the correct directory.

Thank you so much for your help !
