### ISSUE TITLE
The subdirectory entry is printed in red

### ISSUE THREAD

**Issue by inxksp** [15knots/cmake4eclipse#195]
When cmake parses a subdirectory (with the "--debug-output" option), it displays a message in red: Entering "subdirectory name" followed by "Returning to "project name"
Why is this message highlighted in red? Looks like a error, but it's not a error.
Is it possible to change the color for this type of message? Blue would be better

**Comment by 15knots** [comment]
Are you referring to the C++ build console here?
If so it is red because cmake prints the message to stderror.
You can change the colors in the workspace preferences.

**Comment by inxksp** [comment]
Yes, I mean the Eclipse console (STD Global console)
I don't want to change the color for stderr, red is good for errors
It's strange that CMAKE sends a message about the subdirectory to stderr.
It seems that in this case nothing can be fixed.
