### ISSUE TITLE
incompatibility with eclipse 2023-12

### ISSUE THREAD

**Issue by ydaveluy** [15knots/cmake4eclipse#198]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here.

**Describe the bug**
It is no possible to build project with eclipse 2023-12 (previously working with eclipse 2023-09)

When importing samples projects and building a popup with Problem Occured is opened. 

**To Reproduce**
1. clone https://github.com/15knots/cmake4eclipse-sample-projects
2. import samples projects in eclipse 2023-12
3. build projects

**Useful Information**
- cmake4eclipse version:  4.0.3
- Which OS do you use: Linux

***What is in Eclipse's Error Log?***
```
Errors running builder 'Cmake4eclipse buildscript generator' on project 'C-1src'.
Cannot invoke "org.eclipse.cdt.managedbuilder.core.IOutputType.getOutputExtensions(org.eclipse.cdt.managedbuilder.core.ITool)" because "outType" is null
Errors running builder 'Cmake4eclipse buildscript generator' on project 'C-flat'.
Cannot invoke "org.eclipse.cdt.managedbuilder.core.IOutputType.getOutputExtensions(org.eclipse.cdt.managedbuilder.core.ITool)" because "outType" is null
Errors running builder 'Cmake4eclipse buildscript generator' on project 'C-in-docker'.
Cannot invoke "org.eclipse.cdt.managedbuilder.core.IOutputType.getOutputExtensions(org.eclipse.cdt.managedbuilder.core.ITool)" because "outType" is null
Errors running builder 'Cmake4eclipse buildscript generator' on project 'C-inclpaths'.
Cannot invoke "org.eclipse.cdt.managedbuilder.core.IOutputType.getOutputExtensions(org.eclipse.cdt.managedbuilder.core.ITool)" because "outType" is null
Errors running builder 'Cmake4eclipse buildscript generator' on project 'C-multiconfig'.
Cannot invoke "org.eclipse.cdt.managedbuilder.core.IOutputType.getOutputExtensions(org.eclipse.cdt.managedbuilder.core.ITool)" because "outType" is null
Errors running builder 'Cmake4eclipse buildscript generator' on project 'C-subsrc'.
Cannot invoke "org.eclipse.cdt.managedbuilder.core.IOutputType.getOutputExtensions(org.eclipse.cdt.managedbuilder.core.ITool)" because "outType" is null
```

**Comment by jannemann70** [comment]
Same error on Windows with Eclipse 2023-12 and cmake4eclipse 4.03 installed - even after recreating project from scratch:
![2023-12-07_10h07_39](https://github.com/15knots/cmake4eclipse/assets/83762332/a415fcf5-c1df-4fe3-a479-6ee1602ad6d0)

**Comment by 15knots** [comment]
Seems the CDT guys have broken their API. Again.

**Comment by denmaus** [comment]
According to issue [419](https://github.com/eclipse-cdt/cdt/issues/419), the CDT team is working on their own cmake adoption, which is not as far progressed as cmake4eclipse.
So I guess they don't really care if their API changes break other plugins.

Could you already find out what the reason for the incompatibility is, are only some setups affected or is it a general problem?

**Comment by 15knots** [comment]
As a first measure: I disallowed to install it on CDT 11.4: f8088297d6447e953129eb021ed476d9d6c544aa

**Comment by jannemann70** [comment]
Version 5.0.0 works for me with CDT 11.4.
Thanks a lot!
