### ISSUE TITLE
Need instructions on how this plugin works with eclipse. ie Step 1, etc.

### ISSUE THREAD

**Issue by islanderjtn** [15knots/cmake4eclipse#2]

**Comment by ClaymorePT** [comment]
Please consider in supplying that information after the installation or at the github project main site, so that users can know about it! :)

**Comment by lmoellendorf** [comment]
The user guide tells that one has to enable CMake buildscript generation by open Project -> Properties dialog and expand teh C/C++ Build node. However, in cmake generated Eclipse project ther is no such node.
In Getting started I read "CMake for CDT requires a managed make C/C++ project to work with." Well I have a project defined in my CMakeLists.txt. How do I convert this to a managed make C/C++ project? I thought that this is exactly the job of cmake4eclipse? Isn't it?

**Comment by emilhuseynli** [comment]
After installing a plugin, i couldn't also figure out how to use it.  But couple of hours investigating helped and here is the clue: 1) import your cmake project with "Existing Code as Makefile Project" wizard; 2) go to project properties -> C/C++ Build and check "Generate Makefiles automatically"; 3) go to project properties -> C/C++ Build -> Tool Chain Editor and set "CMake Make Builder" as current builder; 4) build the project and you'll see how cmake was invoked, makefile generated and make executed. Feel free to ask additional questions if the steps above won't work.

**Comment by 15knots** [comment]
Sorry for the confusion, the documentation says
> CMake for CDT requires a managed make C/C++ project to work with

but the word **make** is plainly wrong, it should be omitted. See [Issue #5](https://github.com/15knots/cmake4eclipse/issues/5#)

To get start, try the following in Eclipse
- Check out the source code.
- Open the new C/C++ project wizard (`File|New|C Project` or `File|New|C++ Project`).
- Make sure the project location points to root dir of your checked out files
- For the project type, select `Executable`. You may also select `Shared Library` or `Static Library`, it does not matter, that information comes from your *CMakeLists.txt*. **Do not select `Makefile project` here!**
- Finish project creation.
- Go to project properties -> C/C++ Build and check `Generate Makefiles automatically`
- Go to project properties -> C/C++ Build -> Tool Chain Editor and set `CMake Make Builder` as current builder.
- If (for example) your top level *CMakeLists.txt* resides in subdir `src`, go to Project Properties|C/C++ General|Path and Symbols||Source Location and adjust the source folder to point to the `src` subdir.
- Build the project  This will first invoke cmake to generate the build scripts and the will invoke  make.
- Bug alert: If you see messages indicating 'build/Debug/CMakeCache.txt' is not accessible, try to create *build/Debug/* manually once, then re-build. See https://github.com/15knots/cmake4eclipse/issues/3#issuecomment-108998786 for details.

Do not try to import the Eclipse project that was generated by cmake, that will put you on the `Makefile project` route!

And finally: This is not a mailing list!
Please subscribe to the [mailing list](http://groups.google.com/d/forum/cmake4eclipse-users) for diskussions.

**Comment by 15knots** [comment]
R 1.3.5 comes with online help describing the steps above.
