### ISSUE TITLE
Cmake4eclipse Managed Build wizard missing

### ISSUE THREAD

**Issue by bw35** [15knots/cmake4eclipse#200]
**Describe the bug**
When installing cmake4eclipse 5.0.0 in Eclipse CDT 2023-12, no new Cmake4eclipse projects can be created since the corresponding new project wizard is missing.

**To Reproduce**
1. Install Eclipse CDT for Embedded 2023-12
2. Install the Cmake4eclipse plugin 5.0.0 from the marketplace
3. Restart Eclipse
4. Open a workspace
5. File / New / C/C++ Project
6. The Cmake4eclipse project template is missing from the list

**Expected behavior**
The Cmake4eclipse project template should be contained in the list as it was the case with prior versions.

**Screenshots**
These are the choices I get with the new installation:
![image](https://github.com/15knots/cmake4eclipse/assets/14139370/34fe8071-8547-4b80-b5bf-1098820331a0)

These are the choices with the previous version:
![image](https://github.com/15knots/cmake4eclipse/assets/14139370/2d69c6df-d03a-4989-9a05-f09c4aff2e9b)
Note that there are two CMake categories.

**Useful Information**
- cmake4eclipse version: 5.0.0
- CDT version: 2023-12 4.30.0 Eclipse IDE for Embedded C/C++ Developers (includes Incubating components, Build id: 20231201-2043
- Which OS do you use: Windows 10
- Cmake version: 3.28

***What is in Eclipse's Error Log?***
No traces related to de.marw.

**Comment by 15knots** [comment]
Sorry, I cannot reproduce this (with pain CDT).

**Comment by bw35** [comment]
I was able to solve the problem. The issue is caused by missing privileges during plugin installation. The Windows Eclipse installer puts Eclipse to C:\Program Files\eclipse...  by default, which isn't user-writable. To install the plugin successfully, Eclipse must be run as Administrator. Otherwise the installation fails silently and the Cmake4eclipse new project wizard is missing.
