### ISSUE TITLE
Cmake file-api support

### ISSUE THREAD

**Issue by inxksp** [15knots/cmake4eclipse#202]
**Is your feature request related to a problem? Please describe.**
Eclipse cannot display the project tree structure well. Especially if there are external source code files that are not inside the project directory

**Describe the solution you'd like**
This can be done if you use the cmake file-api instead of parsing compile_commands.jsion.
https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html
I think it's time to switch to file-api because... this method is more universal and provides much more information about the project

**Describe alternatives you've considered**
I looked at how it works in QtCreator and Visual Studio Code. They have made very good progress on this

**Additional context**
Here is an example:
Before running the project configuration, you need to create the query file /build/Debug/.cmake/api/v1/query/query.json:
{"requests":[{"kind":"cache","version":2},{"kind":"codemodel","version":2},{"kind":"toolchains","version":1},{"kind":"cmakeFiles","version":1}]}

Cmake then creates response files in /build/Debug/.cmake/api/v1/reply:
![image](https://github.com/15knots/cmake4eclipse/assets/114681702/e7deb415-4d3f-44dc-b4e9-048768fcbf3e)

These files contain all the necessary information about the project

**Comment by 15knots** [comment]
> **Is your feature request related to a problem? Please describe.**
> Eclipse cannot display the project tree structure well. Especially if there are external source code files that are not inside the project directory

That is correct. If you want files and folders that are stored in locations in the file system outside of the project's location, you have to configure _linked resources_. You will find any instruction on _linked resources_ in the eclipse help.

**Comment by inxksp** [comment]
Of course, you can manually add directories. You can build the entire project in Eclipse without cmake.
But we are talking about supporting cmake projects!
VS and QtCreator have already implemented file-api support. Eclipse is lagging behind.
