### ISSUE TITLE
Add selection of docker network type when building in container

### ISSUE THREAD

**Issue by Leifsuon** [15knots/cmake4eclipse#203]
My docker image used for building my CMake based project requires reaching resources on my network.
However, the docker related settings provided in CMake4Eclipse doesn't let me choose network mode for the launched docker container.

Please add the possibility to choose at least **--net host**  option when launching the specified docker container, but if possible add more settings from the Eclipse Docker Tooling plugin.

An alternative solution would be to instead allow attaching a running container instead of launching a new. That way I could launch it manually with all needed settings.

**Comment by 15knots** [comment]
Sorry, the Container Settings tab comes from CDT itself. Did you try the docker workbench preferences?

**Comment by Leifsuon** [comment]
Ok, thanks for your quick response. 
I'll contact the CDT team instead.
