### ISSUE TITLE
cmake4eclipse should handle CDT variables instead of just eclipse core variables

### ISSUE THREAD

**Issue by drolevar** [15knots/cmake4eclipse#23]
cmake4eclipse plugin seems to ignore CDT variables like ${ProjDirPath}
Would be nice to have when a toolchain file is referenced from a location inside the project.

**Comment by 15knots** [comment]
Could you please explain what _referenced from a location inside the project._ does mean?

**Comment by nolange** [comment]
I suppose he meant passing a file in the project as parameter to cmake.

In case this is bug report is not clear, you can`t access system or userdefined variables that are managed in the [Build Variables preferences](https://help.eclipse.org/neon/topic/org.eclipse.cdt.doc.user/reference/cdt_u_pref_build_vars.htm?cp=8_4_6_1_0), particularly when defining cmake cache variables

**Comment by nolange** [comment]
Further, if setting/override any environment Variables in CDT (like PATH) will have no effect, the base Eclipse definitions will be used

**Comment by drolevar** [comment]
I'm currently using project_loc variable here. When I tried using ProjDirPath it didn't work.
![screenshot from 2017-04-20 10-57-00](https://cloud.githubusercontent.com/assets/14980349/25222323/72911a84-25b8-11e7-9879-c4b9d0a4980b.png)

**Comment by 15knots** [comment]
Could you post the cmake invokation line shown in 'CMake Console' here.

I cannot reproduce it here, I get
`cmake ... -DVAREXPAND:FILEPATH=/home/.../cmake4eclipsecdt/testprojects/C-subsrc/src/../bald -G "Unix Makefiles" /home/.../cmake4eclipsecdt/testprojects/C-subsrc/src` which shows that variables get properly expanded.

**Comment by kevemueller** [comment]
I am now using cmake4eclipse with multiple projects / multiple configurations and experience problems with the evaluation of the variables as well.
When changing environments, the evaluation _sometimes_ sticks to the value used in the old environment, _sometimes_ it does not evaluate at all (logs an Exception).
Even more striking is when _sometimes_ an unrelated project is built into the currently active project, e.g. I have project Test1 and Test2, both are in a built status and have an install target running by default installing the executables into ${project_loc}/target/${config_name:${project_name}}.
Changing and building Test2 also builds Test1 (already unexpected, but in its proper location) and then installs it into Test2/target (unexpected and disturbing).

So far I can only achieve a consistent evaluation of variables, when I run Build Configurations/Build all.
I have no simple case that removes the _sometimes_ from the above description.

**Comment by 15knots** [comment]
Indeed, the plugin uses `org.eclipse.core.variables.VariablesPlugin` to expand variables. The VariablesPlugin only knows a few variables like project_loc. You can see the full list of variables, if you open a _Run configuration_ and open the _Variables..._ dialog.

The CDT project re-invented the wheel and introduced the `org.eclipse.cdt.core.cdtvariables.ICdtVariableManager` which is pre-populated with all system environment vars and gives you the ${ConfigName} plus the stuff you add under Build Variables in the project dialog..
