### ISSUE TITLE
Error upgrading to 1.4.6

### ISSUE THREAD

**Issue by JeffBail** [15knots/cmake4eclipse#25]
I tried to upgrade to 1.4.6 but I got the following error:
An error occurred while collecting items to be installed
session context was:(profile=epp.package.cpp, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,de.marw.cdt.cmake.core,1.3.7.201703201434
No repository found containing: org.eclipse.update.feature,de.marw.cdt.cmake,1.4.6.201703201434

I have cmake4eclipse setup as a software site with URL https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/

I'm running Eclipse 4.6.2 with CDT 9.2.0 on Ubuntu 16.04.2

**Comment by TheBigFred** [comment]
Hi, I have the same issue.
I use this url 

> jar:https://bintray.com/artifact/download/15knots/p2-zip/cmake4eclipse-1.4.6.zip!/

as workaround.

In my work office, I have a lot of problems with eclipse update in general. In my case, I ask to me if the network filtering is not the source of the problems.

Fred.

**Comment by 15knots** [comment]
Am Mittwoch, 22. März 2017, 11:24:30 schrieb JeffBail:

Hi Jeff,
> I tried to upgrade to 1.4.6 but I got the following error:
> An error occurred while collecting items to be installed
> session context was:(profile=epp.package.cpp,
> phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=,
> action=). No repository found containing:
> osgi.bundle,de.marw.cdt.cmake.core,1.3.7.201703201434 No repository found
> containing: org.eclipse.update.feature,de.marw.cdt.cmake,1.4.6.201703201434
> 
> I have cmake4eclipse setup as a software site with URL
> https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-> update/

I get the same here. Will investigate...

Martin

> 
> I'm running Eclipse 4.6.2 with CDT 9.2.0 on Ubuntu 16.04.2

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by 15knots** [comment]
Silly typo, but hard to spot:-)
