### ISSUE TITLE
A build or clean without build directory will try to use "rm"

### ISSUE THREAD

**Issue by nolange** [15knots/cmake4eclipse#32]
Hello, it seems that a clean operation will be executed by some kind of "Parent Builder" if cmake was not run before (and the files are missing), even if a build is requested.
First, this fails on Windows as there is no rm executable, and more importantly it will deduce some names from the project and sources and tries to delete them - in some unspecified directory.

eg. the attached Project will output the following, note that this doesn`t care at all about the CMake files and instead guesses the names:

11:16:26 **** Clean-only build of configuration Release for project uit_mon ****
rm -rf uit_mon src/main.d src/main.o 
Cannot run program "rm": Launching failed

[uit.zip](https://github.com/15knots/cmake4eclipse/files/919011/uit.zip)

(A workaround is to disable the "clean" checkbox in C/C++ Build -> Behaviour, then build once)

**Comment by 15knots** [comment]
Yes, this is known behavior, but I could not find a way to stop CDT from running `rm -rf`.
But it does not harm:
-  on windows, because it always will fail due to the lag of the `rm` command.
- on linux, since it tries to invoke rm without any file name argument, which will make rm fail.

**Comment by nolange** [comment]
Well,on Linux, if I happen to have a directory uit_mon in whatever directory rm is executed, then its gone.
On Windows, I cant build either, because eclipse tries to do a clean first if the build directory is not configured.

So Id consider this problematic

**Comment by 15knots** [comment]
`rm -rf` on linux does nothing. So no problem here.
On Windows, why does your eclipse try to do a **clean** first before build?

**Comment by nolange** [comment]
CDT does a clean before a build (on Linux and Windows), if the directory is missing. Check with the attached project, see the content of my build console. The **why** is something I hope you can figure out.
```
14:05:41 **** Clean-only build of configuration Release for project uit_mon ****
rm -rf src/main.d src/main.o uit_mon 

14:05:41 Build Finished (took 77ms)
```
