### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser double backslashes on windows

### ISSUE THREAD

**Issue by 15knots** [15knots/cmake4eclipse#34]
`compile_commands.json`file contain double backslashes on windows. Include directories specified in cmakelists might not be properly passed to the CDT indexer.
`{
  "directory": "D:/cevdata/.interface_simple",
  "command": "C:\\MinGW-w64\\bin\\i686-w64-mingw32-c++.exe    @CMakeFiles/ccd-rt_te_interface_simple.dir/includes_CXX.rsp -g   -o CMakeFiles\\ccd-rt_te_interface_simple.dir\\simple_te.cpp.obj -c D:\\cevdata\\.interface_simple\\simple_te.cpp",
  "file": "D:/cevdata/.interface_simple/simple_te.cpp"
},
`

**Comment by nolange** [comment]
It seems that include directives (**-I**) don`t contain backslashes. (sending them through `Path.toRealPath()` probably doesnt hurt...)

```
{
  "directory": "D:/temp/example/build/Release",
  "command": "C:\\PROGRA~2\\GNUTOO~1\\62017-~1\\bin\\AR10B2~1.EXE  -DHSE_VALUE=24000000 -DQDECT -DSTM32F303xC -DUSE_STDPERIPH_DRIVER -ID:/temp/stm32_library/Device/ST/STM32F30x/Include -ID:/temp/stm32_library/include -ID:/temp/stm32_library/STM32F30x_StdPeriph_Driver/config -ID:/temp/stm32_library/STM32F30x_StdPeriph_Driver/inc  -Os -DNDEBUG   -ffunction-sections -fdata-sections -Wall -Wpointer-arith -Wsign-compare -fstrict-overflow -Wdeprecated --pipe -fmessage-length=0 -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-enums -fno-exceptions -fno-rtti -Wnoexcept -std=gnu++11 -o CMakeFiles\\aufsteckmodule.dir\\src\\device.cpp.obj -c D:\\temp\\example\\src\\device.cpp",
  "file": "D:/temp/example/src/device.cpp"
},
```

**Comment by 15knots** [comment]
> (-I) don't contain backslashes

weird. but thanks for reporting. Will check what happens in MinGW next time I get  a wondows machine.

**Comment by 15knots** [comment]
Verified, include directories don't contain backslashes (at least in MinGW). 
Closing this.
