### ISSUE TITLE
Multiple targets

### ISSUE THREAD

**Issue by stayprivate** [15knots/cmake4eclipse#35]
Hello,

First time user of cmake4eclipse. 

The project I'm working was handled properly by cmake4eclipse, good start.  The project consist of multiple target (libs and executables).  Cmake4eclipse created a build target at the root of the project but it did not create individual build target for each target. Is there any way targets.

I also could not find a way to enabled parallel build.  This setting is usually in the Behavior tab of "C/C Build) but when set to cmake builder it is not there anymore.

Regards,
Mario

**Comment by 15knots** [comment]
What are you referring to when you speak of a _build target_? 
The plugin just invokes cmake with the `CMakelists.txt` file that you write. Its up to cmake to generate the makefiles.
If send a link to your project on github, so I will have a look at it.

**Comment by 15knots** [comment]
There is no option to en/disable parallel builds at the moment. Only CDT\`s `Internal Bullder` supports that, but that builder will not work with this plugin.
You may also switch your project to generate [Ninja](https://ninja-build.org/)   build scripts; ninja does parallel builds by default and runs the build much faster than make.

**Comment by nolange** [comment]
You can open the view "Build targets" and add them manually. There is no way it happens automatically right now.

You can enable parallel builds in the `Builder Settings` by manually editing the "Build Command" - set this to `make -j4` for example.
But you should just use ninja if you can

**Comment by stayprivate** [comment]
Ok thanks.  And Ninja work great ;-)
