### ISSUE TITLE
Build occurs in eclipse install directory

### ISSUE THREAD

**Issue by giraldeau** [15knots/cmake4eclipse#38]
Create a cmake project, build once, then delete the build directory and build again. The build directory occurs under the eclipse install directory: 

```
11:36:29 AM **** Buildscript generation of configuration Debug for project cmake-tutorial
cmake -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles" /home/francisg/shared/cmake-tutorial 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/francisg/eclipse/cpp-neon/eclipse
```

When building once again, the build occurs in the right directory `/path/to/project/build/Debug`.

**Comment by 15knots** [comment]
Could this be related to issue https://github.com/15knots/cmake4eclipse/issues/26?

What is the working directory of your eclipse process?

**Comment by giraldeau** [comment]
You are right, it looks like the same problem. I installed from the Eclipse Marketplace, I don't know if that version includes the fix.

`CDT CMake build integration	1.4.8.201705201727	de.marw.cdt.cmake.feature.group`

**Comment by 15knots** [comment]
1.4.8 contains the fix. 
Looks like you hit the  magic in CDT`s Spawner class.

I have no ideas how to circumvent that:-(

**Comment by giraldeau** [comment]
Awesome fix, thanks!
