### ISSUE TITLE
Enabling build output parser does not pass necessary arguments to cmake

### ISSUE THREAD

**Issue by giraldeau** [15knots/cmake4eclipse#39]
In `Project -> Properties -> C/C++ General -> Preprocessor Include Paths -> Providers` enabling `CMAKE_EXPORT_COMPILE_COMMANDS` and/or `CDT GCC Build Output Parser` has no effect. Deleting the build directory and rebuilding, the cmake command does not have the required arguments:

```
cmake -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles" /home/francisg/shared/cmake-tutorial
```

Providing manually the required options to cmake on the command line, the file `compile_commands.json` is generated as expected:
```
$ cmake -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles" /home/francisg/shared/cmake-tutorial -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```

**Comment by 15knots** [comment]
Which version of the plugin do you use?

Version 1.2.8 adds ```-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON``` to the cmake invokation, if CMAKE_EXPORT_COMPILE_COMMANDS Parser is enabled. See [BuildscriptGenerator#buildCommandline()](https://github.com/15knots/cmake4eclipse/blob/master/de.marw.cdt.cmake.core/src/main/java/de/marw/cdt/cmake/core/internal/BuildscriptGenerator.java#L402)

**Comment by giraldeau** [comment]
I installed the cmake plugin from the Eclipse Marketplace today and the version is `1.4.8.201705201727`, which should add the arguments, but doesn't.

**Comment by 15knots** [comment]
I use CDT v. 9.1.2, which do you use?
What does the eclipse lof file say? Any exception thrown?

**Comment by giraldeau** [comment]
The CDT installation is version `9.2.1.201704050430`. There is only some random noise related to `_pixman_error_log` on the console output where eclipse was started and there is not exception occuring. Thanks!

**Comment by 15knots** [comment]
Maybe you are looking at an outdated cmake log.
Please check `.settings/language.settings.xml`whether the CompileCommandsJsonParser is really enabled. It should contain a line with `<provider-reference id="de.marw.cmake.cdt.language.settings.providers.CompileCommandsJsonParser" ref="shared-provider"/>`

**Comment by giraldeau** [comment]
The setting was correct inside `language.settings.xml`. I think you are right, I was looking at an old cmake log output. When changing the settings under Providers is changed, cmake is not invoked to apply the new settings on the next build. If the CMakeCache.txt file is deleted, then cmake is called with the proper arguments.

**Comment by 15knots** [comment]
If it is working, please close this issue. Or leave a comment...

**Comment by giraldeau** [comment]
I see two options: either adding the to the doc that the user has to remove CMakeCache (but kinda weak), or make sure cmake runs again after the setting is modified (bullet proof). For instance, cmake should be triggered if the last execution timestamp is less than the last setting modification timestamps.

**Comment by 15knots** [comment]
So is it working fo you?

Currently, cmake invocation is triggered if `CMakeCache.txt` does not exist or if the user selected a different buildscript-generator.

But usually, people do not change their project settings very often.
