### ISSUE TITLE
Default build location (request honor Eclipse build directory spec)

### ISSUE THREAD

**Issue by arette** [15knots/cmake4eclipse#4]
The default of putting build_scripts under build/<configuration name> is a poor choice: you're assuming the name of my Eclipse project corresponds to some actual location on my filesystem (which, in my case, it does not).  My Eclipse project is named AE3007C2, but the root is at AE3007/C2.  I would request that cmake4eclipse honor the Eclipse build directory instead of the current default behavior for improved flexibility/robustness to cover a wide variety of end user environments.

**Comment by 15knots** [comment]
Am Donnerstag, 4. Juni 2015, 12:45:05 schrieb arette:
> The default of putting build_scripts under build/<configuration name> is a
> poor choice: you're assuming the name of my Eclipse project corresponds to
> some actual location on my filesystem (which, in my case, it does not).  My
> Eclipse project is named AE3007C2, but the root is at AE3007/C2.  I would

The plugin actually puts build scripts under 
<project_location>/build/<configuration name>, where project_location expands 
to the absolute filesystem path of the project. 

> request that cmake4eclipse honor the Eclipse build directory instead of the

Please clarify 'Eclipse build directory'.

There is a field in the projects properties dialog named 'Build directory'. 
You may have noticed that this field is *not* editable if 
C/C++ Build| Builder Settings| Generate Makefiles automatically
is unchecked.
If you uncheck that, neither CDT makefile generation nor the plugin�s 
buildscript generation will happen; CDT expects You to provide the build 
scripts yourself.

**Comment by arette** [comment]
based on your description, it may be that this feature request would also require modification to Eclipse itself.  Nonetheless, I desire the ability to specify to cmake4eclipse (and Eclipse for that matter) where my build directory is rather than being forced to use <project_location>/build/<configuration name>.

**Comment by 15knots** [comment]
Am Dienstag, 9. Juni 2015, 12:47:40 schrieb arette:
> based on your description, it may be that this feature request would also
> require modification to Eclipse itself.  Nonetheless, I desire the ability
> to specify to cmake4eclipse (and Eclipse for that matter) where my build
> directory is rather than being forced to use
> <project_location>/build/<configuration name>.

cmake4eclipse currently enforces a hard-coded location of the build directory 
relative to the eclipse project location on disk (CDT does so, too).

It would be possible to change the hard-coded default add an extra input field 
in the UI to a project-relative folder to use as the build directory. But for 
users it might be confusing to have two different input fields for the 
directory.
That folder might be a linked folder, which can point to a filesystem 
location outside of the project�s fs location (I guess that�s your use case: 
Sources on NFS/CIFS, generated/object files on local disk?).


-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by arette** [comment]
no, all of my sources are local.  I just don't like being told that things MUST go in folder called 'build'.  I would like to be able to specify a different directory name (still ok if it's relative to project dir), e.g. 'win32'.  So, in that case, the plug-in would use <project_location>/win32/<configuration name>.  Make sense?

**Comment by 15knots** [comment]
CDT managed build does not allow the user to change the build location, must be fixed in CDT.
