### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser doesn't work if compiler command doesn't contain full path

### ISSUE THREAD

**Issue by radovanovic** [15knots/cmake4eclipse#41]
For example if in CMakeLists.txt I have

`set(CMAKE_CXX_COMPILER "clang++")`

there would be bunch of errors reported

!ENTRY de.marw.cmake 2 0 2017-07-12 17:47:17.122
!MESSAGE /fEngine/build/Default/compile_commands.json: No parser for command 'clang++ -DfEngine_EXPORTS -I/usr/local/include/c++/v1 -I/usr/local/include -fPIC -std=c++1y -stdlib=libc++ -DFENGINE_BUILD -include /home/rivan/workspace/fEngine/src/fEngine/pch.hpp -o CMakeFiles/fEngine.dir/templates/TemplateFileTagFactory.cpp.o -c /home/rivan/workspace/fEngine/src/fEngine/templates/TemplateFileTagFactory.cpp', skipped

if I instead put

`set(CMAKE_CXX_COMPILER "/usr/bin/clang++")`

everything works perfectly.

**Comment by 15knots** [comment]
reopen, see https://github.com/15knots/cmake4eclipse/issues/40#issuecomment-314906950
