### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser fails for command paths using a forward slash

### ISSUE THREAD

**Issue by NikBrg** [15knots/cmake4eclipse#44]
I am using cmake4eclipse on Windows with MSYS2. Unfortunately, the CMAKE_EXPORT_COMPILE_COMMANDS Parser fails to recognize the command parser due to forward slashes in the command path: 

> /Project/compile_commands.json: No parser for command 'D:/Project/Tools/MSYS2/mingw64/bin/cc.exe -DSTM32F205xx -DUNITTEST @CMakeFiles/usbh.dir/includes_C.rsp -O3 -DNDEBUG   -fprofile-arcs -ftest-coverage -o CMakeFiles/usbh.dir/STMicro/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c.obj   -c D:/Project/EclipseWS_MSYS2/PogoSMAC/src/main/ThirdParty/STMicro/Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c', skipped

If all forward slashes ("/") are replaced by double backslashes ("\\"), everything works as expected.

**Comment by 15knots** [comment]
Which cmake version do you use?

**Comment by NikBrg** [comment]
CMake 3.8.1 (from MSYS2 MinGW repository)

**Comment by 15knots** [comment]
cmake version 3.5.2 produces
`C:\\MinGW\\bin\\gcc.exe`. Looks like the cmake guys changed it since then
