### ISSUE TITLE
Feature Request: Populate CMake cache entries from a file.

### ISSUE THREAD

**Issue by niecore** [15knots/cmake4eclipse#46]
The CMake command line tool has the option "-C" which allows the user populate the initial cache of CMake options from a file.

It would be useful to have this option also available in cmake4eclipse.

**Comment by niecore** [comment]
offtopic: is this project planned to be upstreamed to eclipse cdt?

**Comment by 15knots** [comment]
Currently, there are no plans to integrate it in CDT. Those guys rolled their own cmake support in CDT 9.1

**Comment by niecore** [comment]
Thank's for the Implementation.
