### ISSUE TITLE
No parallel build available

### ISSUE THREAD

**Issue by eugenwintersberger** [15knots/cmake4eclipse#52]
When choosing `Gnu Make Builder` in the project properties I can set the number of cores I would like to use for the build. However, when I switch the builder to `CMake Builder (portable)` this option vanishes. 
How can I use parallel builds with `CMake` generated Makefiles?

**Comment by 15knots** [comment]
Use the `ninja` generator, ninja has parallel build enabled by default (and BTW is much faster).

The plugin is agnostic of the actual  build tool, the build tool is chosen by cmake.  And as being agnostic, it does not know **which build tool** supports parallel build and **which options** have to be passed to that tool.
Someone will have to create and maintain a database of build tools supporting parallel build and their options to accomplish that.

**Comment by eugenwintersberger** [comment]
Ok. Got your point. Ninja works well on all platforms. Thanks for the advice. I will close this issue.
