### ISSUE TITLE
Cannot generate solution files for MS Visual Studio`

### ISSUE THREAD

**Issue by eugenwintersberger** [15knots/cmake4eclipse#53]
When running from Eclipse on Windows it is not possible to let CMake generate output files for Visual Studio. Once can do this easily on the command line. This is really annoying as with this feature available we could use Eclipse also on Windows for code development :(

Is there a reason why this is not implemented?

**Comment by 15knots** [comment]
If you already use Visual Studio, why do you need Eclipse to generated build scripts for it?

**Comment by eugenwintersberger** [comment]
Actually all my build files are generated with CMake. I use Eclipse merely for editing code and git (as far as it is possible with EGit). I would like to use Eclipse on all platforms and consequently use only the command line tools of Visual Studio. Anyhow, ninja works also well on Windows so I can close this too :)

**Comment by kevemueller** [comment]
IMO, working 99% in Eclipse, switching to Visual C++ is harder than adding 4 entries into a dropdown.
I have performed a workaround invoking a batch command that replaces the command line and invokes Cmake. It works as expected.
I have configured "cmake --build . --target " as the make command, again working as expected.
Please consider adding the items to the dropdown - or making the dropdown editable.
