### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser with intel mpi compiler wrapper

### ISSUE THREAD

**Issue by thierrydha** [15knots/cmake4eclipse#56]
In Problems view I get the message "No parser for command /path_to_wrapper/mpiicpc.
Is there a way to get the parser to recognise this compiler?

**Comment by 15knots** [comment]
It is possible to specify a version suffix, but that won`t help in your case.
See discussion for [issue 43](https://github.com/15knots/cmake4eclipse/issues/43#issuecomment-315188456).
