### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser: Add workaround for relative include path produced by cmake`s ninja generator

### ISSUE THREAD

**Issue by moetka** [15knots/cmake4eclipse#57]
The Ninja generator produces relative paths without regard to the actual settings in include_directories() or target_include_directories. See
[compile_commands.json.txt](https://github.com/15knots/cmake4eclipse/files/1466942/compile_commands.json.txt)

cmake4eclipse turns those paths (../../include in the provided example) into "C:/include" in the Project Explorer on Windows.

The setup is a 64-bit Windows 7 machine with 32-bit eclipse-cdt installation
Version: Oxygen.1 Release (4.7.1)
Build id: 20170914-1200

**Comment by 15knots** [comment]
Relative paths work here under Linux with ninja generator and cmake 3.5.2.
Which version of cmake do you use?

**Comment by moetka** [comment]
cmake version 3.9.1
ninja version 1.7.2

The includes are specified in the top CMakeLists.txt with
`include_directories("${PROJECT_SOURCE_DIR}/include" "${PROJECT_SOURCE_DIR}/include/include2")`

The resulting project explorer looks like this
![project-explorer-wrong-include-paths](https://user-images.githubusercontent.com/33627415/32769222-48d7e0fe-c91b-11e7-8372-2ab17e92594d.png)
although the project resides in C:\git\arm_cross_gcc

The entries in the properties of Preprocessor Include Paths, Macros etc. look like this by the way
![preprocessor-include-paths-macros-etc](https://user-images.githubusercontent.com/33627415/32769938-0e5d7698-c91e-11e7-9fca-f148b5768f09.png)

**Comment by moetka** [comment]
I have moved the project to C:\git\additional_folder\arm_cross_gcc. The resulting project explorer layout 
![project-explorer-wrong-include-paths](https://user-images.githubusercontent.com/33627415/32770441-fa04c33e-c91f-11e7-90a6-8b134ee31a2e.png)

It seems as if the project root folder is prepended to the relative paths provided by the parser, while the build folder should be used:
C:\git\additional_folder\arm_cross_gcc\\..\\..\include
-> C:\git\include

C:\git\additional_folder\arm_cross_gcc\build\DBG_GCC_HOST\\..\\..\include
-> C:\git\additional_folder\arm_cross_gcc\include

**Comment by 15knots** [comment]
How do you set the include directories in your CMakeLists.txt?
If you simply use
`include_directories(  ../../include)` cmake will get it wrong.
Use
`include_directories(  ${PROJECT_SOURCE_DIR}../../include)` instead.

The parser itself does not modify or interpret any include path it found. Paths a forwarded as-is to the CDZ indexer.

**Comment by moetka** [comment]
The include folder is a subdir of the project root, so I use
`include_directories("${PROJECT_SOURCE_DIR}/include" `

**Comment by 15knots** [comment]
Your CMakeLists.txt  looks ok.

As you can see in the screenshots above, the Includes folder in the Project Explorer view show the absolute paths of your include dir. The grayed path entries indicate that these directories do not exist.

Anyway, it looks like we hit a bug in [cmake #13894](https://gitlab.kitware.com/cmake/cmake/issues/13894) which may take some time to resolve.
Fortunately, the `compile_commands.json` file contains the absolute working directory, so it will be possible to work around the bug by adding it, if necessary.
