### ISSUE TITLE
CMAKEFILES_EXPORT_COMPILES_COMMANDS not used/updated in Eclipse project

### ISSUE THREAD

**Issue by tp-pitc** [15knots/cmake4eclipse#62]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## (If Bug Report) Brief Summary

When using the CMAKEFILES_EXPORT_COMPILES_COMMANDS include files defined in CMakeLists.txt show up in the preprocessor and include section of the Project preferences 
but not in the includes section of the project tree and a reference to an include file is not found.
### What is the expected behavior?

After parsing the include files I expected the tree to be populated and the unresolved include file reference fixed.
### What behavior are you observing?

No resolution of includes files specified in the CMAKEFILES_EXPORT_COMPILES_COMMANDS
### Provide the steps to reproduce the issue, if applicable:

1. 
1. 
## Useful Information
Which OS do you use: Ubuntu 16.04LTS
Cmake version: 3.5.1
compile_commands.json contents:
[
{
  "directory": "/home/tom/Workspaces/PITC_Plugin/test_plugin/build/Release",
  "command": "/usr/bin/c++   -D-std=c11 -DNDEBUG -Dmyplugin_EXPORTS -I/home/tom/Workspaces/PITC_Plugin/test_plugin/src -I/home/tom/SIMDIS/PluginAPI -I/home/tom/SIMDIS/PluginAPI/STD -I/home/tom/SIMDIS/PluginAPI/PluginClient  -O3 -DNDEBUG -fPIC   -o CMakeFiles/myplugin.dir/MyPlugin.cpp.o -c /home/tom/Workspaces/PITC_Plugin/test_plugin/src/MyPlugin.cpp",
  "file": "/home/tom/Workspaces/PITC_Plugin/test_plugin/src/MyPlugin.cpp"
}
]

**Comment by 15knots** [comment]
This is known, but unwanted behavior. You will have to open the 'Preprocessor Include Paths...' page in the project Properties dialog and click 'apply' to update the 'Includes' folder of the C++ Projects view..
You may want to follow the discussion on the [CDT mailing list](https://dev.eclipse.org/mhonarc/lists/cdt-dev/msg32555.html).

**Comment by tp-pitc** [comment]
Nope that (clicking on the preprocessor apply) does not change the includes folder of the C++ Projects view. Yes there is a refresh but it stays the same.
The entries are displayed correctly in the preprocessor page of the properties of the project.
Also the two symbols I defined in the cMakeLists.txt are not found anywhere in the project view. The two symbols are like -DNDEBUG and -Dstd=c11.
I need the first define to set up my code properly.

**Comment by 15knots** [comment]
After some investigation, I found the "Includes" folder is only updated when the project is (re-)opened.
CDT caches this information and I found no (non-hackish) way to invalidate the caches.

**Comment by tp-pitc** [comment]
Thanks for investigating. I know it is frustrating.
However the close then reopen (in my version of Eclipse CDT - 9.1- buried inside MyEclipse) has no effect. The include files are just not being used.

**Comment by 15knots** [comment]
Do they show up after a restart of the workbench?
I tested it with CDT 8.1.0, which version do you use?

**Comment by tp-pitc** [comment]
I have cdt 9.1.0 (org.eclipse.cdt - 9.1.0.201609121658)
Only the standard g++ includes are shown never any includes via cmake and more importantly maybe, never any that I manually add myself? As a result lots of unresolved include files showing in the CDT.
I wonder if I should uninstall CDT and reinstall along with cmake4eclipse plugin?

**Comment by 15knots** [comment]
Re-Install won't help.
Do your include paths show up in the the project properties "Preprocessor Include Path.." page (on the "Entries tab with "Show built-in checked"?

**Comment by tp-pitc** [comment]
Well, things have changed.
I decided to delete the project from Eclipse CDT then start again. I set up the cmake4eclipse as the generator etc then did a build. Now the include files show up. I have no idea how things changed. I have done this a few times and did not get this result. Baffled.
Yes the include files show up in the Preprocessor Include Path page on the project properties.
Now the unresolved includes are resolved.
I do have an anomaly though. Not sure if related but it is suspicious.
Error: "must #include <typeinfo> before using typeid	test_plugin		line 145, external location: /home/tom/SIMDIS/PluginAPI/PluginClient/Constants/ConstantsVariableType.h	C/C++ Problem
This particular file has #include <typeinfo> at the top of the file but getting an error on line 145 (and others) indicating that it is not being found by the compiler. The include file can be opened using the CDT and it does go to the correct place (here it is /usr/include/c++/4.9/typeinfo). So not sure why it is complaining.

**Comment by 15knots** [comment]
Glad to hear it works now. Could it be that you copied your CDT project (`.cproject`, `.project`) in the file-system instead of creating it in Eclipse? CDT uses unique ID in its storage, but if you copy the file the IDs loose uniqueness.
Concerning the `#include`problem, this is definitely a C/C++ problem. cmake4eclipse just generates the build scripts, the build itself is up to CDT.
