### ISSUE TITLE
Buildfile generation error occurred

### ISSUE THREAD

**Issue by Yanpas** [15knots/cmake4eclipse#63]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description

Build command fails

### Provide the steps to reproduce the issue, if applicable:

1. Create any cmake project, open it's location as new c/c++ project
2. Choose current builder in toolchain editor (no matter 'cmake make builder' or 'cmake builder protable')
3. Click Build
4. Onlu build dir created and there is an error in console:
```
Buildfile generation error occurred..
cmake exited with status 1. See CMake console for details.
Build stopped..
```

## Useful Information
Which OS do you use: Linux
Cmake version: 3.5.1

**Comment by Yanpas** [comment]
On the other hand running cmake manually works fine (`cmake ..` from build directory)

**Comment by 15knots** [comment]
May I ask what details show in the CMake console?

**Comment by Yanpas** [comment]
Well, that's interesting for me too. I don't know where is this console

**Comment by jerroydmoore** [comment]
Under the Console window, under the "Displayed Selected Console" menu item, there should be a "CMake console [<PROJECT_NAME>]"

**Comment by 15knots** [comment]
Closing this after more that a year waiting for feedback
