### ISSUE TITLE
Project is fully reindexed after each build

### ISSUE THREAD

**Issue by asterkrans** [15knots/cmake4eclipse#64]
- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
With CMake Builder, the whole project is reindexed after each build. The long reindexing times makes the plugin unusable to me.

## (If Bug Report) Brief Summary
With CMake Builder, the whole project is reindexed after each build. It takes 5 minutes of indexing before I can work again after a build. (Just as if I run "Index -> Reindex")
With Gnu Make Builder, the reindexing finishes immediately after a build. (Just as if I run "Index -> Update with modified files"

I consider this as a bug since the indexing behavior of CMake Builder should be the same as for Gnu Make Builder. The long reindexing times makes the plugin unusable to me.

I would like the CMake Builder to trigger a "Index -> Update with modified files" and not a "Index -> Reindex" after a build.

## Useful Information
cmake4eclipse verssion:   CMake for Eclipse	1.0.0.27G-cCLC6h7735G575C737A	cmake4eclipse	null
Which OS do you use: Linux Ubuntu 16.04.2 LTS
Cmake version: 3.6.1

**Comment by 15knots** [comment]
> cmake4eclipse verssion: CMake for Eclipse 1.0.0.27G-cCLC6h7735G575C737A 
Where did you install that version from? 
Current version is CDT CMake build integration	1.9.0.201712152024
Please install that version from the Eclipse marketplace and try again.

Anyway, I do not see how the builder can affect indexing. Its code simply does not trigger indexing, it just invokes `make` (or `ninja`).

**Comment by asterkrans** [comment]
Hi!

I got the right version. I have installed cmake4eclipse version 1.0.0.27G-cCLC6h7735G575C737A, which requires de.marw.cdt.cmake.feature.group version 1.9.0.201712152024. I installed it from https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update/ by drag and drop from Oomp Repository Explorer View.

I have added a new build target just for testing this indexing problem: Build targets -> Create... on the project. I use "echo" as the build command, and "hello" as the build target. I get this full reindexing if the CMake Builder toolchain is selected, but only a quick (1s) indexing when Gnu Make Builder is used.

Maybe the CMake Builder toolchain updates something that has to do with indexing if used? Or is the build command triggered differently in the two toolchains? It could be a setting that depends on selected toolchain, but I have looked through the properties without finding anything.

**Comment by asterkrans** [comment]
I don't know if CompileCommandsJsonParser.java is run after a CMake Builder build, and not if Gnu Make Builder is used? In that case I might have found something. A store.clear() is done after storing timestamp. This will cause getIndexManager().reindex() to be executed every time.

        if (store.lastModified < tsJsonModified) {
          // must parse json file...
          // store time-stamp
          store.lastModified = tsJsonModified;
          store.clear();

**Comment by 15knots** [comment]
You are right, that code should be
`store.clear();
store.lastModified = tsJsonModified;
`

**Comment by asterkrans** [comment]
I'm sorry but the project is not open source. Thank you for the fast feedback.

**Comment by 15knots** [comment]
Would you try the fix in update site https://dl.bintray.com/15knots/p2-zip/cmake4eclipse-1.9.1.zip and report again here?

**Comment by asterkrans** [comment]
Thank you! It works fine now.

**Comment by 15knots** [comment]
published release 1.9.1, you may remove the update site mentioned above from your Eclipse workbench.
