### ISSUE TITLE
Editable default CMakeLists.txt file location

### ISSUE THREAD

**Issue by JanLalisGL** [15knots/cmake4eclipse#66]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [ ] Bug Report  
- [X] Enhancement Request

## Brief Description
Editable default CMakeLists.txt file location

### Provide the steps to reproduce the issue, if applicable:

1. 
1. 
## (If Enhancement Request) Describe it. 
Is it possible to set default CMakeLists.txt file location? Currently it is in source folder, but I want to use project folder location

## Useful Information
cmake4eclipse verssion: 1.9.1.201801231306
Which OS do you use: Ubuntu 16.04
Cmake version:

**Comment by 15knots** [comment]
cmake requires a  `CMakeLists.txt` file being located in in the top-level source directory. Just configure your project directory as the source directory (AFAICT this is the default on newly created C projects).
