### ISSUE TITLE
how to use this plugin?

### ISSUE THREAD

**Issue by robby14** [15knots/cmake4eclipse#7]
Hello, I'm sorry for the dumb question but I'm really not able to understand how this plug in works, it's written that it "automatically generates buildscripts for the Eclipse CDT", but when?
I mean when I use eclipse to write a program in c I press "build" and then "run", now I have a cmake project which obviously doesn't work natively on eclipse, so I installed it and now? Do I have to configure it to make convert this cmake project into something runnable for eclipse?

Thank you so much.

**Comment by robby14** [comment]
I finally got how to made it work after few days, but now I have this error:
make: *** No rule to make target `clean'
why?

**Comment by 15knots** [comment]
Possibly a dup of #2 ?
If not, please provide the CMake console putput and build output.

**Comment by robby14** [comment]
Yeah partially yes, indeed I followed that to use it but what I wrote in the previous comment is what I get when I try to build the project. I don't know what do you mean with "cmake console output"  but the console of eclipse is empty since that it doesn't let me run the project because of the error

**Comment by 15knots** [comment]
Console
![eclipse-console-view](https://cloud.githubusercontent.com/assets/11367029/11666822/abc00e94-9dee-11e5-9286-aad6f450bb07.png)

Most probably you switched to the wrong builder.That happens easily if you change the toolchain.
In the project settings, make sure you have
1. `C/C++ Build | Builder Settings | Builder Type` set to `External builder`
2.  `C/C++ Build | Tool Chain Editor | Current builder` set to either `CMake Builder (portable)` or `CMake Make Builder`.

**Comment by robby14** [comment]
First of all, thank you for your help :)
Anyway, I already had both things setted as you said, but it doesn't work

**Comment by robby14** [comment]
I don't know if it's important or not, by the way, I also have:
C/C++ Build | Tool Chain Editor | Cross GCC

**Comment by 15knots** [comment]
The setting of 
`C/C++ Build | Tool Chain Editor | Current toolchain` should not matter, as long as the builder is configured as in 
https://github.com/15knots/cmake4eclipse/issues/7#issuecomment-163002803.

You may find working projects at https://github.com/15knots/cmake4eclipse/tree/master/testprojects. You can try to copy one of these (.project and .cproject only) into you project sources and modify it.
If your project is on github, I can have a look at it.

**Comment by robby14** [comment]
I tried importing as "existing code as makefile project" using your project "C-1src" but it doesn't work too, I tried using all the option under "toolchain for indexer settings" (in the windows where I have to specify the location source code of the makefile project), that is: cross gcc, gnu autotools toolchain and linux gcc.
When I try to build it the error that I get is: 
make: *** No rule to make target `all'. 

As regards the project I'm trying to import is this one: 
https://github.com/Darredevil/RIOT/tree/add_lwm2m_cli/pkg/wakaama
or  this one:
https://github.com/eclipse/wakaama

Thank you again for all the help :)

**Comment by 15knots** [comment]
Well, the first wakaama project above already has a makefile, so there is no need to use this plugin to generate one. 

https://github.com/eclipse/wakaama/tree/master/core contains a `CMakelists.txt` file, but it is incomplete. You will not be able to generate makefiles from that `CMakelists.txt`, not even with the `cmake` commandline tool.
LMGTFY: https://projects.eclipse.org/projects/technology.wakaama says:
> Wakaama is not a library but files to be built with an application. It is written in C and designed to be portable on POSIX compliant systems.

Pleas consult the cmake and/or the wakaama  documentation how to include it in your project.
