### ISSUE TITLE
Cannot Build For Other Build Configurations 

### ISSUE THREAD

**Issue by jerroydmoore** [15knots/cmake4eclipse#70]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  
- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
Cannot Build For Other Build Configurations 

## (If Bug Report) Brief Summary
After building the project, if you switch build configurations, and try to build, nothing happens. There aren't any errors in the Error Log. There isn't any updates in the Cmake Console. There aren't any new entries in the Problems view. A workaround is to clean the project or delete the build directory, then Cmake4Eclipse builds. By "switch build configurations," I mean changing the build config from DEBUG to RELEASE, or RELEASE to DEBUG.

### What is the expected behavior?
After building the project, if you switch build configurations and try to build, it should produce a binary based on the other build configuration.

### What behavior are you observing?
After building the project, if you switch build configurations and try to build, nothing happens.

### Provide the steps to reproduce the issue, if applicable:
1. Create a new Cmake project
1. Ensure the build configuration is set to DEBUG
1. Build the project
1. Verify the DEBUG binary is there.
1. Switch the build configuration to RELEASE and build the project
1. Verify the RELEASE binary is not there.

## Useful Information
cmake4eclipse verssion: de.marw.cmake v1.4.0 and de.marw.cdt.cmake.core v1.8.0
Which OS do you use: Ubuntu 16.04
Cmake version: 3.5.1

**Comment by 15knots** [comment]
> 1. Create a new Cmake project

How did you create that project?
Do you have experimental cmake support from CDT installed and used  the 'Create CMake project' wizard? If so, consider to consult the CDT documentation.

`cmake4eclipse` is around since 2013 and is designed to work with C- or C++ projects. Consult the plugin`s help pages in Eclipse so see how to enable it.

**Comment by 15knots** [comment]
Closing this after more that a year waiting for feedback
