### ISSUE TITLE
Support for Ninja/NMake Makefiles generator

### ISSUE THREAD

**Issue by SNiLD** [15knots/cmake4eclipse#71]
**This is a...**  

- [ ] Bug Report  
- [X] Enhancement Request

## Brief Description

There is no way to select generator to use. 

## (If Enhancement Request) Describe it. 

It seems to default to "MinGW Makefiles" in Windows which only results in error line:

`CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.`

The line that cmake4eclipse tries to use to generate the project is:

`cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -G "MinGW Makefiles" "D:\\projects\\project\\Sources" `

I don't have MinGW, I'm developing for Visual Studio 2017 with Ninja. If you build cmake project from command-line you can tell it to use Ninja generator with -G"Ninja" and it works as expected. It would be nice if this Ninja project (or even NMake Makefiles project) could be used with cmake4eclipse.

## Useful Information
cmake4eclipse version: 1.11.0.201802241905
Which OS do you use: Windows 10 64-bit
CMake version: 3.10.2
Eclipse version: Oxygen.2 Release (4.7.2)
CDT version: 9.4.2.201802122019
Build environment: Microsoft Visual Studio 2017 Express for 32-bit applications with Ninja

**Comment by SNiLD** [comment]
Oh there actually is a way to change the generator. It's just not documented anywhere:
`Project -> C/C++ Build -> CMake -> Host OS overrides -> Windows -> Buildscrit generator (-G)`.

Selecting Ninja from this dialogue makes it call `-G Ninja` generator but it doesn't use the environment that eclipse was started with.

I start Eclipse with Visual Studio 2017 development environment batch file (`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat`) and the correct INCLUDE, LIB, LIBPATH, PATH variables are shown in `Window -> Preferences -> C/C++ -> Build -> Environment -> Select...`.

However when cmake is run through cmake4eclipse it detects Visual Studio 2010 Express which I also have installed but not in PATH. If I run cmake manually from VsDevCmd.bat environment on the command-line the correct compiler version is detected.

**Comment by SNiLD** [comment]
Seems that while creating the by: `File -> New -> C/C++ Project -> C++ Managed Build` and **NOT** selecting `Microsoft Visual C++` prevents invalid LIB, INCLUDE, LIBPATH, etc entries to be discovered.

This is probably a bug in the way the C/C++ Visual C++ Support module from CDT works and not related to cmake4eclipse.

I leave the instructions here in the hope that they'll help others who try to develop with Visual Studio 2017 and Eclipse CDT Oxygen.2 with cmake4eclipse.

**Comment by SNiLD** [comment]
Not using `Microsoft Visual C++` toolchain makes Ninja builds find the correct compiler but doesn't actually help Eclipse CDT Indexer. It can't find the proper paths and symbols. So I guess there's no other way but to wait for the Eclipse CDT people fix the toolchain.

**Comment by kevemueller** [comment]
cmake4eclipse works fine with Ninja + Visual Studio command lines and the current Eclipse CDT. As you found out, Ninja can now be specified in the overrides.
Please do not start eclipse from within the Visual Studio command line (VsDevCmd.bat), just specify the needed environment variables inside Eclipse Build Configuration under "C/C++ Build // Environment"
There are a lot of variables to define, so I built a small hack to grab the environment variables set by vcvars and place them into the .cproject. 
This way you can have multiple architectures/VS toolchains managed by Eclipse CDT and built alongside each other.

**Comment by SNiLD** [comment]
That's great news! Can you share the hack? I had to move from Eclipse to VS Code because of this and I miss eclipse. :)

**Comment by kevemueller** [comment]
I have cleaned up and published the hack at kevemueller/cdt_grabenv
Feel free to test and provide feedback.
Ninja works fine with cmake4eclipse, but MSVC toolchain needs some hacks, see #59.

**Comment by SNiLD** [comment]
I can't get Ninja working better than what I found out in this ticket before; the indexer still fails with all the files that come from external libraries (like Qt for example).

What I did:
1. Install Eclipse CDT Oxygen.3
2. Install cmake4eclipse
3. File -> New -> C/C++ Project -> C++ Managed Build
   1. Empty project (Cross GCC Toolchain, nothing else is even available)
   2. Debug and Release Configurations (like provided by default)
4. Project -> Properties -> C/C++ Build:
   1. Behavior: Enable parallel build
   2. CMake -> Host OS overrides -> Windows -> Buildscript generator (-G): Ninja
   3. Tool Chain Editor -> Current builder: CMake Builder (portable)

I then ran your hack tool for the .cproject file which generated multiple variables under the C/C++ Build -> Environment. However the results from this are not any different compared to if I launch Eclipse from the VS2017 DevEnvCmd and do the steps provided above.

I can build the project normally and I can go to classes defined within my project but can't access any external dependencies (like Qt for example).

**Comment by kevemueller** [comment]
This  looks more like a CDT troubleshooting to me. 
You seem to be missing   C/C++ Visual C++ Support, org.eclipse.cdt.msw.feature.group, Eclipse CDT please install it (CDT Optional Features). Without this, you have no chance to get Eclipse closer to MSVC.
Cross GCC Toolchain is for sure not ok if you want to build MSVC.
The toolchain should be "Microsoft Visual C++"

In your CMakeLists.txt set(CMAKE_EXPORT_COMPILE_COMMANDS ON).

Under C/C++ General/Preprocessor Include Paths, Macros, etc.. enable the CMAKE_EXPORT_COMMANDS Parser.

This should give you a usable environment within CDT.

**Comment by SNiLD** [comment]
With the Visual C++ Support plugin it tries to use Visual Studio 2010 and it's no wonder since that's the way the Visual C++ Support plugin is built. It has hard coded parameters set up for Visual Studio 2010 only. So unfortunately the way you describe thing does not work (even with your hack).

**Comment by 15knots** [comment]
Closing this, as it turn into a discussion that should happen on the mailing list.
