### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser: Build Configurations

### ISSUE THREAD

**Issue by caselitz** [15knots/cmake4eclipse#72]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

I feel there goes something wrong with the CMAKE_EXPORT_COMPILE_COMMANDS Parser handling Eclipse Build Configurations... what I observed:

When I create a new project with a `Debug` and a `Release` configuration, everything (resolving includes based on parsed path etc.) works fine if I perform a build having the `Debug` configuration active. Even when I switch to `Release` now, it works.

However, if I directly (without performing a build in `Debug`) switch the active configuration to `Release` after creating a project, it does NOT work (includes are not resolved etc.). I need to go back to `Debug`, build (so that CMake creates `project/build/Debug/compile_commands.json`), and switch back to `Release`.

The parsing of the right `compile_commands.json` seems to work. At least when I look at the Settings Entries and switch the configuration between Debug and Release the correct include path and defines from `project/build/Debug/compile_commands.json` or `project/build/Release/compile_commands.json` respectively are displayed.

So I wonder what"s going wrong here. Does it always parse/use the stuff from the `Debug` configuration (which is the first, maybe this matters?) even though it displays differently in the Setting Entries? It is expected behaviour that build configurations should be completely independent and if I switch, re-indexing based on the active configuration should happen, right?

**Comment by caselitz** [comment]
I saw [this issue](https://github.com/15knots/cmake4eclipse/issues/70), but I don't think it's related. I cannot reproduce the bug described there. I created a new Eclipse C++ Project.

**Comment by 15knots** [comment]
IIUC, the include paths show up as expected in the Project properties dialog, but **not** in the _Includes folder_ in the project view?

**Comment by caselitz** [comment]
Exactly, that's the case for `Release`. For `Debug`, it works (the include folder appears). And once it's done for `Debug` and I switch back to `Release` it works there as well - because the includes from `Debug` are still used (which is actually wrong, it should use the includes from  `Release`).

**Comment by 15knots** [comment]
Sorry, bad news.
The include folder seem to own a weird mechanism to  update its view. I could not find a way to programmatically trigger an update.
Sometimes it updates only if you close and re-open the project, sometimes it updates if you click apply in the project properties dialog.

**Comment by caselitz** [comment]
But the issue I described is not about _updating_. Even if I close/open Eclipse or the project or manually trigger re-indexing, the problem (not using includes from `Release` / keeping them from `Debug`) persists. Maybe update triggering is another (additional) issue...

**Comment by asterkrans** [comment]
In the preferences for Indexer, can you check which build configuration is used?
I have "Use active build configuration" selected, and indexing seems to work fine for me when switching configurations.

Maybe you don't have CMAKE_EXPORT_COMPILE_COMMANDS Parser configured right for both configurations? I find the [all configurations] option in project properties a bit buggy. Better to look at Debug and Release settings separately.

**Comment by caselitz** [comment]
> In the preferences for Indexer, can you check which build configuration is used?
I have "Use active build configuration" selected, and indexing seems to work fine for me when switching configurations.

Thank you. Actually I had `Use a fixed build configuration` and `Debug` selected, so what I observed is expected behaviour. So **it's not a bug, it's a feature (of Eclipse)** - this issue can be closed. :)

**Comment by 15knots** [comment]
THX to @asterkrans !
