### ISSUE TITLE
Cmake Error Parser only works in Cmake Console

### ISSUE THREAD

**Issue by asterkrans** [15knots/cmake4eclipse#73]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
Cmake Error Parser only works in Cmake console, making CMake warnings in CDT Build Console go unnoticed.

## (If Bug Report) Brief Summary
When I have made changes to CMake files and build a make target, CMake is triggered from make. This makes the CMake output appear in the regular CDT Build Console instead of the CMake Console.

Cmake Error Parser only parses CMake Console, making CMake errors in the build console go unnoticed.

I don't see the use of a special console for CMake output, and would suggest that it's removed all together. It's just annoying that sometimes the wrong Console is shown. 

### What is the expected behavior?
CMake errors should show up in Problems view.

### What behavior are you observing?
CMake errors from CDT Build Console does not show up in Problems view.

### Provide the steps to reproduce the issue, if applicable:
1. Build project once.
2. Introduce a CMake warning.
3. Build project.
4. The CMake warning can be seen in CDT Build Console, but not in Problems view.

## Useful Information
cmake4eclipse verssion: 1.9.1 
Which OS do you use: Ubuntu
Cmake version: 3.6.1

**Comment by asterkrans** [comment]
Thank you for explaining the issue.

I would really like to get the cmake error parsing working. I will try redirecting stderr to stdout and see if that helps. Otherwise I'll serialize the output from make by just buffering stderr and writing it out to stdout in the end. I suppose it would be possible to do even smarter parsing to improve the interleaving.

I guess I should invoke make with one of the --output-sync flags too, since I do parallell builds.

I'll report back how it works for me. If you ever decides to remove the cmake error parser from cmake4eclipse, then maybe you could provide it as a separate plugin?

**Comment by 15knots** [comment]
> I'll report back how it works for me. If you ever decides to remove the cmake error parser from cmake4eclipse, then maybe you could provide it as a separate plugin?

As it turns out now, the parser is useless. It is fed by CDT with the output of the CDT Build Console which does not contain any output from cmake. 
I had to introduce the CMake Console  because CDT re-creates the console each time a build is run, so the output of cmake written to a CDT Build Console gets lost.

The parser itself is only one java-file plus an entry in the plugin.xml. Making a single file a separate plugin is just overkill IMHO 
But the license is EPL, so you could simply copy the code and improve it.

**Comment by asterkrans** [comment]
**You may close this issue.** I'll post an update here within a couple of weeks when I had time to experiment a bit with stderr/stdout intermixing.

**If you are interested in how I use cmake4eclipse, I'll try to explain it here: (I'm not sure I'm able to explain it good enough, but I'll try)**
I normally do not use the CMake Console at all. I create my Eclipse projects from a template using a python script. Indexing my projects takes a long time. To make the first-time-indexing right when importing it, I have to generate the cmake_compile_commands.json file from my project-generation-script before importing my project in Eclipse for the first time. So usually cmake4eclipse doesn't run cmake explicitly.

I have a build-helper-script that I invoke from eclipse when building. For example I have a clean target that will clean the whole build directory and directly rebuild cmake to make a cmake_compile_commands.json available again.

Since all make commands are already invoked through my build-helper-script, it's a good place to also fix stderr/stdout intermixing. I will later modify my make wrapper to print the saved log from this first-time cmake output the first time a build is done from eclipse, to make the error parser see the output.

**Comment by asterkrans** [comment]
By the way, Are Cmake errors ever automatically cleared from the Problems view? If so, when?

**Comment by 15knots** [comment]
Am Samstag, 24. März 2018, 15:53:12 CET schrieb Oscar Asterkrans:
...
> normally do not use the CMake Console at all. I create my Eclipse projects
> from a template using a python script. Indexing my projects takes a long

If you create new .cproject and language-settings.xml from templates, be 
warned: CDT uses UUIDs to differentiate its build configurations. As a 
consequence, different eclipse projects will share their settings, if you 
change e.g. the build configuration in projectA, these changes will also apply 
to the configuration in other projects
NEVER COPY CDT project files, unless you are a friend of strange behavior.

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by 15knots** [comment]
Am Samstag, 24. März 2018, 15:59:37 CET schrieb Oscar Asterkrans:
> By the way, Are Cmake errors ever automatically cleared from the Problems
> view? If so, when?

No, they aren't cleared. The parser stems from the early infancy of the 
project and never did parse cmake output after I introduced the Cmake Build 
console.

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by asterkrans** [comment]
> CDT uses UUIDs to differentiate its build configurations. 
I do search and replace of id:s with generated new UUID:s. It seems to work. I bumped into that "strange behavior quite fast as I have multiple projects open simultaneously.

**Comment by 15knots** [comment]
Found a way to make the cmake error parser work: Do not rely on the CDT console output sniffer, which intermixes stderr and stdout, but pass stderr and stdout to an error parser which uses the stream directly, bypassing CDT`s console output sniffer.

**Comment by asterkrans** [comment]
Nice! Thank you.

**Comment by 15knots** [comment]
Could you provided some cmake output containing error/warning to help improve this?
Currently I only have
1. CMake Error at CMakeLists.txt:19  ...
2. CMake Warning at CMakeLists.txt:19 ...
3. CMake Error in CMakeLists.txt:19 ...
4. CMake Error ... 
5. output of the MESSAGE() command

**Comment by 15knots** [comment]
Fixed in release 1.12.2
