### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser problem

### ISSUE THREAD

**Issue by caselitz** [15knots/cmake4eclipse#74]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

It seems the CMAKE_EXPORT_COMPILE_COMMANDS Parser does NOT properly parse the following excerpt from the `compile_commands.json`:

```
{
  "directory": "/home/username/workspace/projectname/build/Release/projectname/foldername",
  "command": "/usr/bin/c++  -Dprojectname_ROOT_DIR=\\\"/home/username/workspace/projectname\\\" -Dfilename_EXPORTS -Dqh_QHpointer -DvtkFiltersFlowPaths_AUTOINIT=\"1(vtkFiltersParallelFlowPaths)\" -DvtkIOExodus_AUTOINIT=\"1(vtkIOParallelExodus)\" -DvtkIOGeometry_AUTOINIT=\"1(vtkIOMPIParallel)\" -DvtkIOImage_AUTOINIT=\"1(vtkIOMPIImage)\" -DvtkIOSQL_AUTOINIT=\"2(vtkIOMySQL,vtkIOPostgreSQL)\" -DvtkRenderingContext2D_AUTOINIT=\"1(vtkRenderingContextOpenGL)\" -DvtkRenderingCore_AUTOINIT=\"4(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingFreeTypeOpenGL,vtkRenderingOpenGL)\" -DvtkRenderingFreeType_AUTOINIT=\"2(vtkRenderingFreeTypeFontConfig,vtkRenderingMatplotlib)\" -DvtkRenderingLIC_AUTOINIT=\"1(vtkRenderingParallelLIC)\" -DvtkRenderingVolume_AUTOINIT=\"1(vtkRenderingVolumeOpenGL)\" -isystem /opt/ros/kinetic/include/opencv-3.3.1-dev -isystem /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv -I/usr/local/include/eigen3 -I/home/username/workspace/projectname/projectname -I/usr/include/vtk-6.2 -I/usr/include/freetype2 -I/usr/include/x86_64-linux-gnu/freetype2 -I/usr/include/jsoncpp -I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent -I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu -I/usr/include/hdf5/openmpi -I/usr/include/libxml2 -I/usr/include/tcl -I/usr/local/include/pcl-1.8 -I/usr/include/eigen3 -I/usr/include/ni -I/usr/include/openni2 -I/home/username/workspace/projectname/external/libname   -march=native  -O3 -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/filename.dir/filename.cc.o -c /home/username/workspace/projectname/projectname/foldername/filename.cc",
  "file": "/home/username/workspace/projectname/projectname/foldername/filename.cc"
}
```

I think the critical part (added by `${PCL_INCLUDE_DIRS}`) is

```
-Dqh_QHpointer -DvtkFiltersFlowPaths_AUTOINIT=\"1(vtkFiltersParallelFlowPaths)\" -DvtkIOExodus_AUTOINIT=\"1(vtkIOParallelExodus)\" -DvtkIOGeometry_AUTOINIT=\"1(vtkIOMPIParallel)\" -DvtkIOImage_AUTOINIT=\"1(vtkIOMPIImage)\" -DvtkIOSQL_AUTOINIT=\"2(vtkIOMySQL,vtkIOPostgreSQL)\" -DvtkRenderingContext2D_AUTOINIT=\"1(vtkRenderingContextOpenGL)\" -DvtkRenderingCore_AUTOINIT=\"4(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingFreeTypeOpenGL,vtkRenderingOpenGL)\" -DvtkRenderingFreeType_AUTOINIT=\"2(vtkRenderingFreeTypeFontConfig,vtkRenderingMatplotlib)\" -DvtkRenderingLIC_AUTOINIT=\"1(vtkRenderingParallelLIC)\" -DvtkRenderingVolume_AUTOINIT=\"1(vtkRenderingVolumeOpenGL)\"
```

which also avoids that the stuff afterwards get properly parsed (include directories missing).

Do you see any reasons why the parser is currently not able to parse this? Is it related to the `\"...\"` stuff? Could the parser be fixed or is that actually wrong CMake code from the PCL library?

**Comment by caselitz** [comment]
So I guess the goal would be that e.g. `-DvtkFiltersFlowPaths_AUTOINIT=\"1(vtkFiltersParallelFlowPaths)\"` gets parsed as a Symbol with the name `vtkFiltersFlowPaths_AUTOINIT` and the value `1(vtkFiltersParallelFlowPaths)`.

**Comment by caselitz** [comment]
Thanks for investigating this @15knots.

First, I think I've to correct myself, instead of

> So I guess the goal would be that e.g. `-DvtkFiltersFlowPaths_AUTOINIT=\"1(vtkFiltersParallelFlowPaths)\"` gets parsed as a Symbol with the name `vtkFiltersFlowPaths_AUTOINIT` and the value **`1(vtkFiltersParallelFlowPaths)`**.

the goal should be `"1(vtkFiltersParallelFlowPaths)"`.

From what I understood (from what you said about the unit test), what I currently get is `\"1(vtkFiltersParallelFlowPaths)\"`. This is different from "the goal", but should not break things.

My main concern is (to quote me):

> which also avoids that the stuff afterwards get properly parsed (include directories missing).

Could it be that the thing actually breaks down due to the brackets or commas in the VTK macros, e.g., `-DvtkIOSQL_AUTOINIT=\"2(vtkIOMySQL,vtkIOPostgreSQL)\"`?

Regarding PCL: It is a cross-platform library targeting all kind of compilers. I'm not sure whether the issue is introduced by how PCL "includes" VTK, or if it's an issue with VTK itself (which is also a very popular cross-platform library). Anyhow, since for me they are 3rd party libraries, I can hardly control their CMake code.

**Comment by 15knots** [comment]
After reading _man cpp_ again I would state that
`-DvtkIOSQL_AUTOINIT=\"2(vtkIOMySQL,vtkIOPostgreSQL)\"` in the compile_commands.json should be seen by a C compiler (and parsed by cmake4eclipse) as

Macro name: vtkIOSQL_AUTOINIT
Macro value: "2(vtkIOMySQL,vtkIOPostgreSQL)"`

where the value is a **string literal**. In a C source file, that would be equivalent to a preprocessor directive like
#define vtkIOSQL_AUTOINIT "2(vtkIOMySQL,vtkIOPostgreSQL)"`

My guess is that the `-Dprojectname_ROOT_DIR=\\\"/home/username/workspace/projectname\\\" ` in the json file is fooling my parser.
Apart from that, it could be that the parsing of macro values of string literal or character literal type is broken. Need some more unit tests:-)

**Comment by caselitz** [comment]
> After reading man cpp again I would state that
> `-DvtkIOSQL_AUTOINIT=\"2(vtkIOMySQL,vtkIOPostgreSQL)\"` in the compile_commands.json should be seen by a C compiler (and parsed by cmake4eclipse) as
> 
> Macro name: vtkIOSQL_AUTOINIT
> Macro value: "2(vtkIOMySQL,vtkIOPostgreSQL)"`
> 
> where the value is a string literal. In a C source file, that would be equivalent to a preprocessor directive like
> #define vtkIOSQL_AUTOINIT "2(vtkIOMySQL,vtkIOPostgreSQL)"`

I agree (except for the ` in the end of the value, maybe that was not on purpose, or why that?).

> My guess is that the `-Dprojectname_ROOT_DIR=\\\"/home/username/workspace/projectname\\\"` in the json file is fooling my parser.

I think this part is indeed not parsed correctly in a sense that the result of the value is not `"/home/username/workspace/projectname"` (which it would ideally be) but instead `\\\"/home/username/workspace/projectname\\\"` - however, this is expected behavior if I understood you correctly and in the end a problem with all the escaping (so the problem is already in the generation of the json file and not an issue of the parser). This is NOT causing the parser to break down (i.e. that stuff afterwards is not parsed anymore), I think I saw this working in files without the other VTK macro stuff.

> Apart from that, it could be that the parsing of macro values of string literal or character literal type is broken. Need some more unit tests:-)

Yes, that would be nice...

**Comment by 15knots** [comment]
AFAICT, parsing of macro values with a type of string literal or character literal is definitely broken.
Fixing this will require to simplify the parser pattern first and the adding new tests and patterns.
