### ISSUE TITLE
Unable to fetch latest version from update site

### ISSUE THREAD

**Issue by solomax** [15knots/cmake4eclipse#81]
- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
Repository at https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update is configured to provide 1.11.2 but there is no such version on bintray

## (If Bug Report) Brief Summary
We have this as tycho repo definition:
```
                <repository>
                        <id>cmake4eclipse</id>
                        <url>https://raw.githubusercontent.com/15knots/cmake4eclipse/master/releng/comp-update</url>
                        <layout>p2</layout>
                </repository>
```
while trying to updated we got:
```
Caused by: org.eclipse.equinox.p2.core.ProvisionException: Authentication failed for jar:https://dl.bintray.com/15knots/p2-zip/cmake4eclipse-1.11.2.zip!/.
```

While checking bintray I find out 1.11.1 is the latest version ....

### What is the expected behavior?
There should be no errors

### What behavior are you observing?
while trying to updated we got:
```
Caused by: org.eclipse.equinox.p2.core.ProvisionException: Authentication failed for jar:https://dl.bintray.com/15knots/p2-zip/cmake4eclipse-1.11.2.zip!/.
```

## Useful Information
cmake4eclipse verssion: latest
Which OS do you use: Ubuntu 16.04
Cmake version: 3.10.0

**Comment by 15knots** [comment]
Sorry, forgot to publish it on bintray.com.
Published it just now.

**Comment by solomax** [comment]
Thanks a lot
Works as expected!
