### ISSUE TITLE
Poor workbench startup performance due to doing a IIndexManger.reindex()

### ISSUE THREAD

**Issue by jponroy** [15knots/cmake4eclipse#85]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
When CMAKE_EXPORT_COMPILE_COMMANDS Parser is enabled, index is rebuilt each time i restart Eclipse.

## Brief Summary
When i debug the plugin, in tryParseJson function, store.lastModified line 234 is always equals to 0. Storing of time stamp seems not working.
``
Thread [Worker-0] (Suspended (breakpoint at line 234 in CompileCommandsJsonParser))	
	CompileCommandsJsonParser.tryParseJson(boolean) line: 234	
	CompileCommandsJsonParser.registerListener(ICConfigurationDescription) line: 614	
	LanguageSettingsProvidersSerializer.reRegisterListeners(ICProjectDescription, ICProjectDescription) line: 1375	
	XmlProjectDescriptionStorage.setCurrentDescription(ICProjectDescription, boolean) line: 386	
	XmlProjectDescriptionStorage.setLoaddedDescriptionOnLoad(IProject, ICProjectDescription) line: 357	
	XmlProjectDescriptionStorage.getProjectDescription(int, IProgressMonitor) line: 256	
	CProjectDescriptionManager.getProjectDescriptionInternal(IProject, int) line: 426	
	CProjectDescriptionManager.getProjectDescription(IProject, int) line: 408	
	CProjectDescriptionManager.getProjectDescription(IProject, boolean, boolean) line: 402	
	CProjectDescriptionManager.getProjectDescription(IProject, boolean) line: 395	
	CProject.computeSourceRoots() line: 608	
	CProject.computeChildren(OpenableInfo, IResource) line: 629	
	CProject.buildStructure(OpenableInfo, IProgressMonitor, Map<ICElement,CElementInfo>, IResource) line: 593	
	CProject(Openable).generateInfos(CElementInfo, Map<ICElement,CElementInfo>, IProgressMonitor) line: 261	
	CProject(CElement).openWhenClosed(CElementInfo, IProgressMonitor) line: 427	
	CProject(CElement).getElementInfo(IProgressMonitor) line: 305	
	CProject(CElement).getElementInfo() line: 295	
	CProject(Parent).getChildren() line: 55	
	CProject(CElement).accept(ICElementVisitor) line: 524	
	PDOMUpdateTask.createDelegate(ICProject, IProgressMonitor) line: 105	
	PDOMUpdateTask.run(IProgressMonitor) line: 86	
	PDOMIndexerJob.run(IProgressMonitor) line: 155	
	Worker.run() line: 55	
``
### What is the expected behavior?
Storing of time stamp should working.

### What behavior are you observing?
index is rebuilt each time i restart Eclipse even if compile_commands.json doesn't change.

### Provide the steps to reproduce the issue, if applicable:
1. Enable CMAKE_EXPORT_COMPILE_COMMANDS Parser in preprocessor include path settings
1. Restart Eclipse

## Useful Information
cmake4eclipse verssion: 1.12.0
Which OS do you use: Red Hat 6.9
Cmake version: 3.4.2

**Comment by 15knots** [comment]
Neither the detected macros and include paths nor the timestamp is persisted between eclipse workbench sessions. On workbench startup, the macros and path are not present and the detection **has** to run, otherwise the user will have to do something that triggers the detection (e.g. delete the cmakecache.txt file and start a build).

IMHO, CDT is not really prepared to handle macros and include paths that are detected at build time like cmake4eclipse does.

If you suffer poor startup performance due to re-indexing, all I can do is to not triggering re-indexing on startup, but the CDT javadocs (almost non-existent, btw) give no clue what the user experience will be then.

**Comment by jponroy** [comment]
Ok i understand. Another strategy should to compare the last modified date of compile_commands.json file and the last modified date of .metadata/.plugins/org.eclipse.cdt.core/aproject.12345789.pdom file containing the indexing result.

**Comment by 15knots** [comment]
As already stated:

> Neither the detected macros and include paths nor the timestamp is persisted between eclipse workbench sessions.

Please clarify what your problem is with the timestamp not being persisted.

**Comment by jponroy** [comment]
The problem i encounter is a poor startup due to re-indexing ( taking 1h 30 min in my case ) whereas there is no changes in compile_commands.json file. As timestamp information cannot be persisted between Eclipse session as you said, a solution to avoid useless re-indexing should to compare the last modified date of compile_commands.json file and the last modified date of .metadata/.plugins/org.eclipse.cdt.core/aproject.12345789.pdom file containing the indexing result.
Another question : why a full reindexing, an index update is not enough?

**Comment by 15knots** [comment]
The reindex() call was added in order to populate the 'Includes' folder in the project view on startup and after each change to the CMakelists.txt.
Since the 'Includes' folder  still does update unreliably, I whish to remove the reindex() call at all.
