### ISSUE TITLE
Fails to run cmake on Mac OSX

### ISSUE THREAD

**Issue by ghost** [15knots/cmake4eclipse#87]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description

The plug-in fails on Mac OSX. 

## (If Bug Report) Brief Summary

It has all the dev tools installed including clang, cmake, make etc. It fails to find cmake command though it is available on system path. The plugin defaults to Ninja where as makefile would have been most preferred. 

### What is the expected behavior?

It should invoke cmake and generate unix makefiles under build/default directory. Additionally, it should set include/lib paths for the cdt intellisense to work. 

### What behavior are you observing?

Completely fails on Mac OSX. No make files are generated. Defaults to Ninja build where as unix make files should have been preferred. 

### Provide the steps to reproduce the issue, if applicable:

1. Install Eclipse Photon C++ edition. Install xcode, developer tools, compiler tool chain etc. 
2. Install latest cmake using brew, brew install cmake 
2. Install cmake4eclipse from eclipse marketplace 
3. Create a simple Cmake project 
4. Plugin fails 

## Useful Information
cmake4eclipse verssion: 1.12.0
Which OS do you use: MAC OSX High Sierra  v 10.13.6
Cmake version: 3.12.0

**Comment by 15knots** [comment]
> The plugin defaults to Ninja where as makefile would have been most preferred.
...
> Create a simple Cmake project

How exactly did you create the Cmake project?
Most likely you are building with CDT*s cmake support.
To verify, please check out one of the example projects at https://github.com/15knots/cmake4eclipse-sample-projects and build it. Check if there is a `cmake console` after building.

**Comment by testtaco** [comment]
yes you are right. Eclipse photon-cpp comes with built-in CMake support. I've removed the build-in CDT Cmake support. I am getting the following error 

```
Buildfile generation error occurred..
cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -G "Unix Makefiles" /Users/pintu/dev/algotradingengine 
Cannot run program "cmake": Unknown reason

Error: Program "cmake" not found in PATH
PATH=[/usr/bin:/bin:/usr/sbin:/sbin]

Build stopped..
```

**Comment by testtaco** [comment]
my cmake is installed under /usr/local/bin
```
which cmake
/usr/local/bin/cmake

```

**Comment by 15knots** [comment]
Check _Project properties | C/C++ Build | Build Variables | Show system vars_ whether the PATH variable contains /usr/local/bin.
And give the example project a try.

AFK for watching the lack of moon now.

**Comment by testtaco** [comment]
worked! Thanks
Edited 
```
Project Properties | C/C++ Build | Environment 

edited PATH, added /usr/bin/local
```

I am still stuck with a failing intellisense. In my project there are multiple custom include paths. Is there a way by which these are added automatically ?
