### ISSUE TITLE
Parsing of compile_command.json should retain any "--sysroot" argument during compiler internals discovery

### ISSUE THREAD

**Issue by kpansky** [15knots/cmake4eclipse#89]
**This is a...**  
- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
When parsing the compile_command.json the sysroot argument does not appear to be used for the discovery of the CMAKE_EXPORT_COMPILE_COMMANDS parser.  

## Brief Summary
With cross-compile toolchains that do not specify a fixed sysroot (e.g. Yocto/OpenEmbedded SDK toolchains) this causes the system search paths reported by the compiler to be excluded from the "#include<...> search starts here:" section.  Result is that the indexer will not be able to find any of the system header directories.

### What is the expected behavior?
Expected behavior would be to use the --sysroot parameter if specified during internals discovery.

### Provide the steps to reproduce the issue, if applicable:
1.  source an Yocto/OpenEmbedded SDK environment setup
2.  start eclipse
3.  attempt to build a helloworld.cpp with CMake 
4.  disable CDT GCC Built-in Compiler Settings, enable CMAKE_EXPORT_COMPILE* providers
4.  Notice "stdio.h" cannot be found

## Useful Information
cmake4eclipse verssion: 1.12.1
Which OS do you use: Linux
Cmake version: 3.8.2

**Comment by 15knots** [comment]
The  CMAKE_EXPORT_COMPILE_COMMANDS* parsers do not claim to fully support gcc, so I would not see this issue being a bug
The parsers support POSIX compatible compilers (-D, -U -I options) for various platforms, including gcc-cross-compiler variants..
As a goodie, the -isystem option provided by gcc and clang is recognized.
The parsers do NOT aim to understand any option of any of the compilers it supports. Implementing that would require a complete re-write. Unless someone comes with a pull request, I#m not willing to implenet a full command-line option parser for gcc for your exotic use-case.

So try to get a compiler that has the proper sysroot set at configure time.
