### ISSUE TITLE
Improve support for code-completion and symbol browsing in CDT source editors

### ISSUE THREAD

**Issue by 15knots** [15knots/cmake4eclipse#9]
CDT needs to know about non-standard include paths and preprocessor macros.
Currently, the CMake Build Output Parser of the plugin tries to get this information from the **build output** and feeds it to the CDT indexer. Parsing the build output to feed the indexer works well on linux with make and gcc. This cannot work if
- the build tool does not print the compiler commands (as with ninja),
- the cmake generator decides to pass compiler commands in files (as
with make under windows),
- the compiler arguments are not POSIX compatible ('-D' for marcos, '-I' for
include dirs, command name 'cc') as with the microsoft compiler.

Since cmake v. 2.8.11, `cmake` can be instructed to write this information to a j**son-formatted file**. A new LanguaseSettingsProvider should be added which parses that file and feeds the indexer.

**Comment by 15knots** [comment]
Added a new LanguaseSettingsProvider  named `CMAKE_EXPORT_COMPILE_COMMANDS Parser`.

**Comment by isavaskan** [comment]
I have some problem about indexing. C++ editor cannot recognize definitions and includes defined in CMakeLists.txt
System information: 
Eclipse Oxygen.2 
CDT 9.4.0   
CDT CMake build integration	1.9.1.201801231306
OS: Win10
Build system: MSYS2

An example Foo project attached.  If you look at main.cpp line 8, you will see that it is shown as deactivated. Bu it should be activated by macro definition.

[Foo.zip](https://github.com/15knots/cmake4eclipse/files/1780621/Foo.zip)

**Comment by isavaskan** [comment]
Ok, I see. In the project properties "Preprocessor Include Paths, Macros etc. ->Providers -> CMAKE_EXPORT_COMPILE_COMMANDS Parser" should be checked.
