### ISSUE TITLE
Index only used files

### ISSUE THREAD

**Issue by dumarjo** [15knots/cmake4eclipse#92]
If you have any question, please **consult the <a href="http://groups.google.com/d/forum/cmake4eclipse-users">mailing list</a> first** before you raise issues here 

**This is a...**  

- [] Bug Report  
- [X ] Enhancement Request

## Brief Description

Indexer is very slow when using project with many files. Many files in the project are not part of the build. I can set filters to remove then, but i think is not the right direction. 

### What is the expected behavior?

The indexer should only parse the files used in compilation database and not the entire files.
### What behavior are you observing?

The indexer is indexing all files

## Useful Information
cmake4eclipse verssion: latest
Which OS do you use: windows
Cmake version: 3.12

**Comment by 15knots** [comment]
> Many files in the project are not part of the build.

Just to clarify: Are these many files C/C++ files? IIUC, the indexer only considers C/C++/ASM files.

**Comment by 15knots** [comment]
I have no clue on how the indexer gets to know whether a file is part of the build or not. 
But the CMAKE_EXPORT_COMPILE_COMMANDS Parser already adds source file information to the detected macros and include paths, so maybe that is the information the indexer needs.

**Comment by dumarjo** [comment]
Hi,

I' don't know much about the indexer too. But What I can tell, is more file we have in the project (use or not) more longer is take to start the build. We have a project with about 5000 files ( lots of sources libraries) and probably we use 1000 of those files, and it take 10s juste to start the build. 

I will try to play a bit with source filter tabs to see if it help.

**Comment by dumarjo** [comment]
Hi,
setting up the source filter help. So for now, it's a good workaround. Do you think your plugin can set those filter based on compilation database ?

Jonathan

**Comment by 15knots** [comment]
> Do you think your plugin can set those filter based on compilation database ?

Some concerns:
- Bad user experience, if some code changes user controlled settings without any feedback.
- Which criteria to use to set the filter? Number of CPU cores? Number of source files? Used/unused-source-file ration?

**Comment by dumarjo** [comment]
Hi,
I see this feature like any other managed CDT project. If the file is not compiled, you need to manually exclude the file from build. (The Source Filter is the same as Ressource Configuration->Exclude from build). The files have now a special icon that tell the user that the file is not compiled in. 

One of the settings I wish to have it working is the one in the indexer page. 

![image](https://user-images.githubusercontent.com/16599413/48199377-e03c1b80-e329-11e8-9477-b7c863bd91a7.png)

When I uncheck this option, my perception is that only file that are indexed are the files included in the compile_database. 

I thnik that if that setting is respected, this could be a good improvement on indexing. 

Let me know what is your vision on that setting ?

Regards

Jonathan

**Comment by 15knots** [comment]
> When I uncheck this option, my perception is that only file that are indexed are the files included in the compile_database.

**Does** that setting actually affect indexing on your side? 
And what is the `compile_database`? With cmake4eclipse, your CMakeLists.txt are the sole source of truth.

> I thnik that if that setting is respected, this could be a good improvement on indexing.

What should cmake4eclipse do to respect that setting? The plugin detects macros and include paths of the files that are **part of the build only** and passed these (including the file names) to the indexer. If the indexer chooses to index **each** file in the project, what can the plugin be changed?

**Comment by dumarjo** [comment]
Hi,
> > When I uncheck this option, my perception is that only file that are indexed are the files included in the compile_database.
> 
> **Does** that setting actually affect indexing on your side?
No righ now this doesn't affect the indexed files
> And what is the `compile_database`? With cmake4eclipse, your CMakeLists.txt are the sole source of truth.
This file is compile_commands.json. This file content only files/command use in the build. 
> 
> > I thnik that if that setting is respected, this could be a good improvement on indexing.
> 
> What should cmake4eclipse do to respect that setting? The plugin detects macros and include paths of the files that are **part of the build only** and passed these (including the file names) to the indexer. If the indexer chooses to index **each** file in the project, what can the plugin be changed?

I think the plugin can (if possible, i'm not a java or eclipse dev) change the "exclude from build" property of file that are not included in the current build (in the compile_commands.json file). 

Jonathan

**Comment by 15knots** [comment]
According to https://codeyarns.com/2015/10/11/how-to-exclude-files-from-eclipse-indexer/ you should try to do the following to exclude files from being indexed:

- Go to project Properties -> C/C++ General -> Paths and Symbols.
- Go to Source Location tab, click on your project name and choose Edit Filter.
- In the Edit Filter dialog, add the files you want to be excluded from indexing.

**Comment by dumarjo** [comment]
Hi,

Ok then I close this topic.

Regards

Jonathan

**Comment by gentooise** [comment]
Thumb up for this issue. I think that automatically excluding files from build could be an advantage for projects having different source files according to each eclipse Build Configuration (e.g. think about architecture-specific files such as `arch` directory in Linux Kernel project). I don't think this is such a corner case, many cross-platform projects may be like this.

See my related issue [here](https://github.com/15knots/cmake4eclipse/issues/121). I think that excluding from build all the files not present in `compile_commands.json` would automatically solve my issue as well (together with the Indexer `Index source files not included in the build` option pointed by @dumarjo).

> Sorry, I do not plan to add code to automatically mark source files as excluded from build. Reasons are:
> 
> * Bad user experience, if some code changes user controlled settings without any feedback.
> * It is not really proven that excluding files from the build would speed up indexing.
> * Your use case -- only 1000 out of 5000 source files are actually part of the build -- is really a corner case. Additional code that can detect unused sources would slow down the IDE of nearly each other user of cmake4eclipse.

I understand your points about bad user experience and performance, but what if the feature would be disabled by default and could be enabled at need?

**Comment by dumarjo** [comment]
Hi,

Juste to add a note, Clion does exactly this. Do not index file that are not present in the compilation database. 

Jonathan
