### ISSUE TITLE
Provide programmatic access to CMake configuration

### ISSUE THREAD

**Issue by kutschkem** [15knots/cmake4eclipse#95]
**This is a...**  

- [ ] Bug Report  
- [X] Enhancement Request

Currently the packages needed to programmatically access the configuration are not exported. My use case is that I want to automatically configure a new project with certain options. My current workaround is to have a fragment which exports the package.

CDT exports their configuration packages marked as internal. If you consider these packages internal, then that would be a possible way for you to discourage usage, but still allow it.

Specifically, the packages I use are 

de.marw.cdt.cmake.core.internal.settings,
de.marw.cdt.cmake.core.internal

See also this [question/answer](https://stackoverflow.com/a/53085642/1319284) on SO for context.

**Comment by 15knots** [comment]
BTW: I already tried to create a wizard that helps to set up a CDT project with cmake support. it is in the `NewProjectWizard` branch.
But I gave up after I realized that it is not possible without using CDT API marked as internal.
But maybe you want to put such a wizard on the marketplace as cmake4eclipse's evil twin :-D
