### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins - Missing include paths when --sysroot compiler option is given

### ISSUE THREAD

**Issue by asterkrans** [15knots/cmake4eclipse#96]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

## Brief Description
Include paths are correctly reported from compiler using your options **"-E -P -dM -Wp,-v /home/ocp/eclipse-workspace093/.metadata/.plugins/de.marw.cmake/spec.cpp"**. However, some of the reported paths are missing in the list of paths seen under **CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins** provider in properties.

I also got about 500 built-in macros. I have not verified if all of them are present. Are there any maximum number of items in the **CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins** list?

## (If Bug Report) Brief Summary
STDERR from command **arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi -E -P -dM -Wp,-v /home/ocp/eclipse-workspace093/.metadata/.plugins/de.marw.cmake/spec.cpp** is:
```
ignoring nonexistent directory "/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/local/include"
ignoring nonexistent directory "/opt/ocp/5.2.6/sysroots/x86_64-ocpsdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/7.3.0/../../../../../arm-poky-linux-gnueabi/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/include/c++/7.3.0
 /opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/include/c++/7.3.0/arm-poky-linux-gnueabi
 /opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/include/c++/7.3.0/backward
 /opt/ocp/5.2.6/sysroots/x86_64-ocpsdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/7.3.0/include
 /opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/lib/gcc/arm-poky-linux-gnueabi/7.3.0/include
 /opt/ocp/5.2.6/sysroots/x86_64-ocpsdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/7.3.0/include-fixed
 /opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/include/
End of search list.
```
The header paths seen in provider in Eclipse are:
```
/opt/ocp/5.2.6/sysroots/x86_64-ocpsdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/7.3.0/include
/opt/ocp/5.2.6/sysroots/x86_64-ocpsdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/7.3.0/include-fixed
```

### What is the expected behavior?
All header paths added to the list.

### What behavior are you observing?
Missing header paths.

## Useful Information
- cmake4eclipse version: 1.12.2.20180922195
- Which OS do you use: Ubuntu 
- Cmake version: 3.8.2
#### What is in Eclipse's Error Log?

Sanitized stack traces:

**Comment by asterkrans** [comment]
One thought: Are you parseing STDOUT and STDERR independently? Otherwise i guess header paths and defines gets mixed in the compiler output.

**Comment by 15knots** [comment]
The missing include paths are those you specified with the **--sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi**  argument .The Built-Ins-detector does not pass that argument to gcc (or any other compiler).
Try to add the missing dirs in your cmake-toolchain file.

**Comment by asterkrans** [comment]
Yes, the plugin does pass the --sysroot option. As I wrote above, I DO see a call from your plugin that looks like this:
`arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi -E -P -dM -Wp,-v /home/ocp/eclipse-workspace093/.metadata/.plugins/de.marw.cmake/spec.cpp `

My CXX environment variable is set to:
`arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi`
In CMake, the flags are populated here:
`CMAKE_CXX_COMPILER_ARG1:STRING=  -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi`

I don't want to hard code the different paths found under **/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi**. The paths are compiler built-ins and will change when I switch the compiler.

Of course I know that my sysroot is located in **/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi**, but I have no way of knowing about which sub-directories under sysroot that the indexer needs, without asking the compiler. That is what a compiler built-in provider should solve.

I really appreciate your cmake4eclipse plugin, and as I said I would like to use your **CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins** provider. The **CDT Compiler Built-ins** provider add all my include paths correctly, but I got other issues with that plugin (as I mentioned above).

Thank you very much!

**Comment by asterkrans** [comment]
Just to clarify a bit more:
- Your built-in provider does the **correct call** to my compiler
- My gcc compiler **correctly outputs** all needed built-in header paths. (To STDERR, defines goes to STDOUT)
- Your built-in provider just pick up two of the required built-in header paths. This makes eclipse indexing not working.
- Of course building my stuff works. I dont need to (and should not) provide compiler built-ins in my cmake-toolchain file.

**Comment by 15knots** [comment]
> Yes, the plugin does pass the --sysroot option. As I wrote above, I DO see a call from your plugin that looks like this:
arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi -E -P -dM -Wp,-v /home/ocp/eclipse-workspace093/.metadata/.plugins/de.marw.cmake/spec.cpp 

Where did you see that command? The plugins does not show it in the Eclipse console view.
And if you look at the [code](https://github.com/15knots/cmake4eclipse/blob/master/de.marw.cmake/src/main/java/de/marw/cmake/cdt/language/settings/providers/builtins/CompilerBuiltinsDetector.java#L187), you will see that it only passes the options `-E -P -dM -Wp,-v` to the compiler., No `--sysroot` .

**Comment by asterkrans** [comment]
> Where did you see that command? The plugins does not show it in the Eclipse console view.
> And if you look at the code, you will see that it only passes the options -E -P -dM -Wp,-v to the compiler., 
> No --sysroot.
I wrapped my compiler with a script that logs arguments for each call. It is obvious that the call is from your plugin since no one else compiles the dummy-file **.plugins/de.marw.cmake/spec.cpp**. Another useful way to intercept system calls such as exec* on linux is strace.

In CompilerBuiltinsDetector.java, I guess that:
```
command = arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi -E -P -dM -Wp,-v /home/ocp/eclipse-workspace093/.metadata/.plugins/de.marw.cmake/spec.cpp

args = -E -P -dM -Wp,-v /home/ocp/eclipse-workspace093/.metadata/.plugins/de.marw.cmake/spec.cpp
```
(So, command is what I set my CXX env variabe to.)

I'm not familiar with the Eclipse API. Does the code below take care of parseing STDOUT and STDERR separately? Header paths goes to STDERR and defines goes to STDOUT.
```
      // NOTE: we need 2 of this, since the output streams are not synchronized, causing loss of
      // the internal processor state
      final BuiltinsOutputProcessor bop1 = createCompilerOutputProcessor(entries, builtinDetectionType);
      final BuiltinsOutputProcessor bop2 = createCompilerOutputProcessor(entries, builtinDetectionType);
      int state = launcher.waitAndRead(new OutputSniffer(bop1), new OutputSniffer(bop2), monitor);
```

**Comment by 15knots** [comment]
> In CompilerBuiltinsDetector.java I guess that 
> `command = arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi`

A guess. CXX env var with value
`arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi`
is put by cmake into compile_commands.json as
`  "command": "/usr/bin/arm-poky-linux-gnueabi-g++ -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/5.2.6/sysroots/cortexa7hf-neon-poky-linux-gnueabi  -g   -o CMakeFiles/main.dir/main.c.o   -c /home/.../C-inclpaths/src/main.c"`
which is seen by the CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins parser as a compiler executable
`/usr/bin/arm-poky-linux-gnueabi-g++`.

No --sysroot  option is passed to compiler call for built-in detection.

**Comment by 15knots** [comment]
> Well, it should pass also the sysroot option as it is important for getting the built-ins right.

That would require a major re-design to the plugin's detection logic. Unless someone comes up with a pull request, I do not plan to implements that. It is too much work and just GCC specific, IMHO.
It would be much easier to write a wrapper-script that invokes g++ with the --sysroot argument and pass that in CXX envvar. Just make sure the wrapper script name ends with `-g++` or `-gcc`.

> Also, it does seem to pass sysroot 

It does NOT. Seen here on the debugger and also in the (currently unreleased) console view.

**Comment by asterkrans** [comment]
--sysroot is not gcc specific. It's used in most cross-compilers. Also clang and armcc for example. But sysroot is far from the only flag that affects builtins. I think the other ones on my command line above may be important for some builtin defines.

As I said, I see the options propagated correctly to the g++ call. Maybe I can try the console view later to have it verified in yet another way.

As I pointed out above, I'm wondering if there possibly could be a race condition in the output from g++, that goes both to stdout and stderr??

**Comment by asterkrans** [comment]
Also note that embedded development (Using cross compiler) is a large part of Eclipse C/C++ usage since most vendors provide their Eclipse based IDE with custom support for their debuggers and trace equipment etc. (Texas Instruments: Code Composer Studio, ARM: DS-6 (Development Studio), Freescale: CodeWarrior etc)

**Comment by asterkrans** [comment]
I see now using your console that at least with cmake4eclipse 1.13.0, --sysroot is not provided, just as you said:
/opt/sysroots/x86_64-ocpsdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -E -P -dM -Wp,-v /home/xxxx/eclipse-workspace/.metadata/.plugins/de.marw.cmake/spec.cpp 

I think this is a bug, but the _CDT Built-in Compiler Settings_ plugin can be used instead as a workaround.

You may close this issue if you which to.

**Comment by daniel-dnil** [comment]
@asterkrans : Wouldn't the solution I'm proposing here: https://github.com/15knots/cmake4eclipse/issues/108#issuecomment-460664838 work also for allowing to add a --sysroot option in your case? I.e. we allow the user to manually specify (through the GUI) which options that should be provided to the compiler when extracting the "compilers built-ins"?

**Comment by 15knots** [comment]
@asterkrans Please leave a reply on my post at https://github.com/15knots/cmake4eclipse/issues/108#issuecomment-489425453.
